### ISSUE TITLE
[XrdHttp] Regression in header parsing

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#2273] opened 2024-05-19 08:09 UTC
In 7514bcb4dbf9c83110c1c28b8f531f32ebf8e6a7 / #2255, @ccaffy introduced the following code:

```c
        // A \r\n was detected
        if(BuffUsed()) {
          if(CurrentReq.request == CurrentReq.rtUnset){
            // The first line has a "\n" at the beginning
            // Bad request
            return SendSimpleResp(400, nullptr, nullptr, "Got first line break before the HTTP verb", 0, false);
          } else {
            // We are getting the headers from the buffer and we detected the header end.
            // Though, there is still data to read from the buffer, continue to read!
            continue;
          }
        }
        // We have detected the header end and no data remains in the buffer, we stop this loop
```

The `else` case here is not correct.  After the `\r\n`, the client has indicated the end-of-headers and the remainder of the buffer is the body of the request.

I suspect it might have worked in hand-testing -- probably many clients have a slight pause between the headers and the body that cause the request to be split into two packets.  However, testing with my `golang` client causes an immediate failure.

Symptoms of issue: after issuing the request, the client hangs indefinitely because the server believes there are more headers coming (it's not handling the body) while the client is waiting for the response.

Example log output (removing some Pelican wrapper text and empty lines):
```
240519 09:57:32 5379 http_Protocol: read 525 of 1048576 bytes
240519 09:57:32 5379 http_Protocol:  rc:60 got hdr line: PROPFIND /test/SomeDirectoryThatDoesNotExist:%29/ HTTP/1.1
240519 09:57:32 5379 http_Protocol:  Parsing first line: PROPFIND /test/SomeDirectoryThatDoesNotExist:%29/ HTTP/1.1
240519 09:57:32 5379 http_Protocol:  rc:30 got hdr line: Host: F4HP7QL65F.local:65381
240519 09:57:32 5379 http_Protocol:  rc:32 got hdr line: User-Agent: pelican-client/dev
240519 09:57:32 5379 http_Protocol:  rc:21 got hdr line: Content-Length: 203
240519 09:57:32 5379 http_Protocol:  rc:34 got hdr line: Accept: application/xml,text/xml
240519 09:57:32 5379 http_Protocol:  rc:23 got hdr line: Accept-Charset: utf-8
240519 09:57:32 5379 http_Protocol:  rc:19 got hdr line: Accept-Encoding: 
240519 09:57:32 5379 http_Protocol:  rc:23 got hdr line: Authorization: Bearer
240519 09:57:32 5379 http_Protocol:  rc:45 got hdr line: Content-Type: application/xml;charset=UTF-8
40519 09:57:32 5379 http_Protocol:  rc:10 got hdr line: Depth: 1
240519 09:57:32 5379 http_Protocol:  rc:23 got hdr line: Accept-Encoding: gzip
240519 09:57:32 5379 http_Protocol:  rc:2 got hdr line: 
240519 09:57:32 5379 http_Protocol:  rc:28 got hdr line: <d:propfind xmlns:d='DAV:'>
240519 09:57:32 5379 http_Protocol:  rc:12 got hdr line: \t\t\t<d:prop>
240519 09:57:32 5379 http_Protocol:  rc:21 got hdr line: \t\t\t\t<d:displayname/>
240519 09:57:32 5379 http_Protocol:  rc:22 got hdr line: \t\t\t\t<d:resourcetype/>
240519 09:57:32 5379 http_Protocol:  rc:26 got hdr line: \t\t\t\t<d:getcontentlength/>
240519 09:57:32 5379 http_Protocol:  rc:24 got hdr line: \t\t\t\t<d:getcontenttype/>
240519 09:57:32 5379 http_Protocol:  rc:17 got hdr line: \t\t\t\t<d:getetag/>
240519 09:57:32 5379 http_Protocol:  rc:25 got hdr line: \t\t\t\t<d:getlastmodified/>
240519 09:57:32 5379 http_Protocol:  rc:13 got hdr line: \t\t\t</d:prop>
240519 09:57:32 5379 anon.0:23@localhost http_Protocol:  rc:0Header not yet complete.
```

You can see clearly where the webdav body is being parsed as a header.

Reverting the PR fixed my unit test.

**Comment by ccaffy** [comment] 2024-05-21 08:54
Many thanks @bbockelm for your ticket! The following python program was used for tests to reproduce the issue in @1964 and to fix it.

```python
import os
import pycurl

curl = pycurl.Curl()

curl.setopt(pycurl.URL, "https://xrootd.cern.ch:1096/tmp/BIGFILE_5GB_COPY")
curl.setopt(pycurl.HTTPHEADER, ["test: test\n"])

TEST_DATA = "This is some text 0x1d bytes."

curl.setopt(curl.VERBOSE, 1)

def print_traffic(msg_kind, msg):
  if msg_kind < 1 or msg_kind > 4:
    return
  if msg_kind % 2 ==0:
    print("[%2d]> %s" % (msg_kind, str(msg)))
  elif msg_kind % 2 == 1:
    print("[%2d]< %s"  % (msg_kind, str(msg)))

curl.setopt(pycurl.DEBUGFUNCTION, lambda x, y: print_traffic(x, y))

class StringReader:
  def __init__(self, data):
    self.pos = 0
    self.data = data
  def read(self, size):
    ret = self.data[self.pos:self.pos+size]
    self.pos=self.pos+size

    if len(ret) == 0:
      self.pos = 0
    return ret

curl.setopt(pycurl.UPLOAD, 1)
stringreader = StringReader(TEST_DATA)
curl.setopt(pycurl.READFUNCTION, stringreader.read)

curl.perform()

print(curl.getinfo(pycurl.HTTP_CODE))

curl.setopt(pycurl.UPLOAD, 1)
curl.perform()
print(curl.getinfo(pycurl.HTTP_CODE))
```

Unfortunately as you said and I did not know this could happen, a client may send the headers + the body in the same request, so my `else` above is indeed wrong. Sorry for that!

**Comment by ccaffy** [comment] 2024-05-21 13:27
I unfortunately am not sure on how to fix that issue though. I managed to fix your case by considering every `\r\n` the end marker of a header line.

But then, the RFC (https://datatracker.ietf.org/doc/html/rfc2616#section-19.3) says that : 
> The line terminator for message-header fields is the sequence CRLF.
   However, we recommend that applications, when parsing such headers,
   recognize a single LF as a line terminator and ignore the leading CR.

In the case of https://github.com/xrootd/xrootd/issues/1964 , a header containing `\n\r\n` (e.g: `Test: test\n` sent via curl would look like `Test: test\n\r\n`) would terminate the header parsing no matter what... Considering `\r\n` the end marker of a header line is very clean, but according to the RFC, I cannot do that. Hence why I continued to read from the buffer until the very end.

@abh3 or @bbockelm I'm opened for suggestions :) Thanks ahead!

**Comment by bbockelm** [comment] 2024-05-21 13:47
So, the question is basically "how quickly should XrdHttp give up on an invalid request?", right?

In the original case where there's a `\n\r\n` sequence due to a `\n` at the end of the header, if we follow the RFC advice, one interpretation interpretation is to consider the `\n` the end of the header and the subsequent `\r\n` as the end of the request.  That means any subsequent data is part of a second request (which is malformed and should get a HTTP 400 Malformed Request followed by a shutdown of the TCP connection).

Thus, following the advice in the RFC would cause us to treat the first, malformed request as valid and then respond to the second request as if it were malformed (precisely what Elvin didn't want in the first place!).

I suppose that you could also ignore the RFC and, if you see the client switching from `\r\n` to `\n` in the header line breaks, assume the client is generating a malformed request and respond to the first request with a HTTP 400.  That way, you give the correct response to the first, malformed request and shutdown the TCP connection prior to responding to the second one.  That'd give a better hint of where the problem is!

**Comment by ccaffy** [comment] 2024-05-21 13:58
> I unfortunately am not sure on how to fix that issue though. I managed to fix your case by considering every `\r\n` the end marker of a header line.
> 
> But then, the RFC (https://datatracker.ietf.org/doc/html/rfc2616#section-19.3) says that :
> 
> > The line terminator for message-header fields is the sequence CRLF.
> > However, we recommend that applications, when parsing such headers,
> > recognize a single LF as a line terminator and ignore the leading CR.
> 
> In the case of #1964 , a header containing `\n\r\n` (e.g: `Test: test\n` sent via curl would look like `Test: test\n\r\n`) would terminate the header parsing no matter what... Considering `\r\n` the end marker of a header line is very clean, but according to the RFC, I cannot do that. Hence why I continued to read from the buffer until the very end.
> 
> @abh3 or @bbockelm I'm opened for suggestions :) Thanks ahead!

Actually, I can see the code here is doing a comparison assuming that `\r\n` has been provided by the client:   https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpReq.cc#L159

**Comment by ccaffy** [comment] 2024-05-21 14:00
> So, the question is basically "how quickly should XrdHttp give up on an invalid request?", right?
> 
> In the original case where there's a `\n\r\n` sequence due to a `\n` at the end of the header, if we follow the RFC advice, one interpretation interpretation is to consider the `\n` the end of the header and the subsequent `\r\n` as the end of the request. That means any subsequent data is part of a second request (which is malformed and should get a HTTP 400 Malformed Request followed by a shutdown of the TCP connection).
> 
> Thus, following the advice in the RFC would cause us to treat the first, malformed request as valid and then respond to the second request as if it were malformed (precisely what Elvin didn't want in the first place!).
> 
> I suppose that you could also ignore the RFC and, if you see the client switching from `\r\n` to `\n` in the header line breaks, assume the client is generating a malformed request and respond to the first request with a HTTP 400. That way, you give the correct response to the first, malformed request and shutdown the TCP connection prior to responding to the second one. That'd give a better hint of where the problem is!

Thanks @bbockelm I'm perfectly happy with ignoring the RFC and send a malformed request to the first client's request. As you said, it would allow to have a good hint of where the problem is ;)

**Comment by abh3** [comment] 2024-05-21 16:10
Sorry to add to the din here. What I don't get is that having the sequence \n\r\n (or even \n\n) does indeed cleanly separate two requests. However, the second request need not be malformed by definition, should it? What about two stacked http requests. Does the RFC prohibit sending a new request before receiving a response to the previous request?
________________________________

**Comment by ccaffy** [comment] 2024-05-22 06:48
Hi Andy,

Well, there is no cleanly separated requests. Having `\n\n` or `\n\r\n` just stops the header parsing while there is still data in the buffer to read related to headers. In my example above, the effect that I observed is that the `100-Continue` header is not parsed by the server because the header parsing stopped, then the server does not send anything to the client (which hangs waiting for 100-continue) and at the same time, is waiting for data coming from the client (and hangs because no data is coming from the client).

**Comment by abh3** [comment] 2024-05-22 07:01
OK, I must admit the protocol is pretty deficient of you ask me. Not only that, but there are also so many open-ended cases that I doubt any server or client actually works correctly n all possible cases even if they are technically following the protocol.
________________________________

**Comment by abh3** [comment] 2024-05-22 07:03
But one more thing. So, is it correct to say that while explicitly not allowed, technically it is impossible for the client to stack http requests as there is no sequence that delineates two requests.
________________________________

**Comment by ccaffy** [comment] 2024-05-22 07:20
I don't think we can stack two HTTP requests as the parsing of the first line and the header parsing is done only once per request. Plus, the HTTP request has a state number depending on which step we are in the HTTP exchange.

**Comment by abh3** [comment] 2024-05-22 07:33
Yeah, I see this being discussed a lot and that http/1 doesn't work with stacked requests. That of course makes http/1 one of the least performant protocols over a WAN. Seems like http/2 tried to address that problem.
________________________________

**Comment by bbockelm** [comment] 2024-05-22 17:11
@abh3 - indeed, it's one of the big deficiencies of HTTP/1.

What you call "stacked requests" is typically called "pipelining" by HTTP/1.  Pipelining is permissible and possible to implement within HTTP/1.

However, historically, the implementations have been so inconsistent and bad that it's rarely enabled.  There's a huge number of framing issues and issues with error conditions that servers and clients got wrong.

Curl, for example, took a long time to enable it -- and then later dropped support once HTTP/2 was sufficiently deployed.  [Here's their writeup](https://daniel.haxx.se/blog/2019/04/06/curl-says-bye-bye-to-pipelining/); they basically said "good riddance".

The Xrootd implementation of HTTP-TPC does enable pipelining in curl -- but I suspect it's barely used (and definitely off in RHEL9).  The overhead of each file transfer for HTTP-TPC + FTS is so enormous (processes are spawned, database commits are made) that they overwhelm the RTT costs saved by pipelining.

**Comment by ccaffy** [comment] 2024-05-24 07:04
Done and merged to devel via https://github.com/xrootd/xrootd/pull/2275 @bbockelm , please re-open if the fix did not make your go client working (it should now!)

**Closed by ccaffy** 2024-05-24 07:04 UTC
Labels: bug (non-critical)
