### ISSUE TITLE
readdir call fails on redirector

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1174] opened 2020-04-06 02:25 UTC
Attempting `gfal-ls` on a redirector fails:
```
$ gfal-ls  root://xrootd.physik.uni-bonn.de:1094//cephfs/grid/atlas/atlaslocalgroupdisk/ 
gfal-ls error: 115 (Operation now in progress) - Failed reading directory: [ERROR] Error response: No such file or directory (Unknown error 400)
```
The log of the redirector contains:
```
200406 04:22:46 32643 acc_Audit: XXX grant gsi aeb776c8.0@lxplus787.cern.ch readdir /cephfs/grid/atlas/atlaslocalgroupdisk/
200406 04:22:46 32643 ofs_opendir:XXX Unable to open directory /cephfs/grid/atlas/atlaslocalgroupdisk/; no such file or directory
```
The directory exists, but is only visible on the actual DTNs. Contacting a DTN directly or using "xrdfs ls" or using WebDAV works well, but it seems the redirector looks that up in the local filesystem instead of redirecting to the DTNs. 

This is in a setup with `cms.dfs limit 0 lookup distrib mdhold 0 redirect immed retries 2` set on the redirector, the redirector itself has no access to the file system. 
It breaks functional tests by ATLAS since LsDir using the gfal2 tools fails. 

This is using `v4.11.3`.

**Comment by wyang007** [comment] 2020-04-06 02:38
This is probably related to a discussion Petr and I had: https://its.cern.ch/jira/browse/DMC-1206
I used 4.11.1 at the server side.

--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

**Comment by olifre** [comment] 2020-04-06 02:52
Indeed! 
I think the cause is that gfal-ls uses readdir internally, which probably causes this difference in behaviour. This leads me to believe it is an xrootd bug (of course, modifying gfal2 would also workaround it). 
I believe the observation by Petr concerning WebDAV in this situation (duplicate entries) may also be worth an issue report.

**Comment by wyang007** [comment] 2020-04-06 02:55
I think under the hood both gfal-ls and xrdfs use the XrdCl library. The good thing is that Michal is in charge of both now.

--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

**Comment by simonmichal** [comment] 2020-04-06 16:43
Hi guys,

xrdfs is issuing a deep locate to get the list of server having the directory and only then is sending the dirlist request directly to the data servers. I definitely can change gfal2 behaviour to the same thing. @abh3 : Could you comment on how the redirector is handling the kXR_dirlist and if the directory needs to be visible to the redirector?

Cheers,
Michal

**Comment by xrootd-dev** [comment] 2020-04-06 21:41
The redirector, by default, sends the client to a server that has the 
directory. Theree are other ways of configuring this but mostly for DFS 
and proxy server setups.

**Comment by abh3** [comment] 2020-04-07 00:15
I suppose I should also add, in the case of DFS setups where you specified that directories will be visible to the re-director. The re-director merely checks for the directory's existence but still redirects the client to the data server which will read the directory. So, if gfal-ls is not honoring the re-directions (which apparently it is not) then it won't work.

**Comment by simonmichal** [comment] 2020-04-07 12:46
From what I see gfal2 is simply using `XrdCl::FileSystem::DirList`. Now, from what @olifre reported, he sees in the redirector logs:

> 200406 04:22:46 32643 ofs_opendir:XXX Unable to open directory /cephfs/grid/atlas/atlaslocalgroupdisk/; no such file or directory

this would indicate that the redirector tried to verify directory existence although it was configured not to: `lookup distrib`

@olifre could you export XRD_LOGLEVEL=Dump, rerun gfal-ls and post the client logs here?

**Comment by olifre** [comment] 2020-04-07 16:01
@simonmichal I attach both server-side logs (starting the server with "xrootd -d", slightly obfuscated and removing the initial authentication part) as [xrootd-filtered.txt](https://github.com/xrootd/xrootd/files/4445661/xrootd-filtered.txt) and an almost unobfuscated 
[clientlog.txt](https://github.com/xrootd/xrootd/files/4445670/clientlog.txt). They are not from the very same run, but the behaviour is the same ;-). 

In case you want to test yourself, we have endpoints with ATLAS, OPS, DTEAM and WLCG VO (just let me know and I can point you to them).

**Comment by simonmichal** [comment] 2020-04-07 17:17
@olifre : thanks a lot for your feedback! From the logs one can clearly see the manager is not redirecting on `kXR_dirlist`!

First, the client tries to stat the directory:

> [2020-04-07 17:58:24.212639 +0200][Dump   ][AsyncSock         ] [xrootd.physik.uni-bonn.de:1094 #0.0] Wrote a message: kXR_stat (path: //cephfs/grid/atlas/atlaslocalgroupdisk/?xrd.gsiusrpxy=/tmp/x509up_u38502, flags: none) (0x800dfc0), 97 bytes
> [2020-04-07 17:58:24.212651 +0200][Dump   ][AsyncSock         ] [xrootd.physik.uni-bonn.de:1094 #0.0] Successfully sent message: kXR_stat (path: //cephfs/grid/atlas/atlaslocalgroupdisk/?xrd.gsiusrpxy=/tmp/x509up_u38502, flags: none) (0x800dfc0).
> [2020-04-07 17:58:24.212663 +0200][Dump   ][XRootD            ] [xrootd.physik.uni-bonn.de:1094] Message kXR_stat (path: //cephfs/grid/atlas/atlaslocalgroupdisk/?xrd.gsiusrpxy=/tmp/x509up_u38502, flags: none) has been successfully sent.
> [2020-04-07 17:58:24.212686 +0200][Debug  ][ExDbgMsg          ] [xrootd.physik.uni-bonn.de:1094] Moving MsgHandler: 0x8002b70 (message: kXR_stat (path: //cephfs/grid/atlas/atlaslocalgroupdisk/?xrd.gsiusrpxy=/tmp/x509up_u38502, flags: none) ) from out-queu to in-queue.
> [2020-04-07 17:58:24.212698 +0200][Dump   ][PostMaster        ] [xrootd.physik.uni-bonn.de:1094 #0.0] All messages consumed, disable uplink
> [2020-04-07 17:58:24.227681 +0200][Dump   ][XRootDTransport   ] [msg: 0x950] Expecting 32 bytes of message body
> [2020-04-07 17:58:24.227700 +0200][Dump   ][AsyncSock         ] [xrootd.physik.uni-bonn.de:1094 #0.0] Received message header for 0x950 size: 8
> [2020-04-07 17:58:24.227717 +0200][Dump   ][AsyncSock         ] [xrootd.physik.uni-bonn.de:1094 #0.0] Received message 0x950 of 40 bytes
> [2020-04-07 17:58:24.227725 +0200][Dump   ][PostMaster        ] [xrootd.physik.uni-bonn.de:1094 #0] Handling received message: 0x950.
> [2020-04-07 17:58:24.227804 +0200][Dump   ][XRootD            ] [xrootd.physik.uni-bonn.de:1094] Got kXR_redirect response to message kXR_stat (path: //cephfs/grid/atlas/atlaslocalgroupdisk/?xrd.gsiusrpxy=/tmp/x509up_u38502, flags: none): xrootd008.physik.uni-bonn.de, port 1094

the manager is redirecting the client to `xrootd008.physik.uni-bonn.de`.

> [2020-04-07 17:58:24.350899 +0200][Dump   ][AsyncSock         ] [xrootd008.physik.uni-bonn.de:1094 #0.0] Wrote a message: kXR_stat (path: //cephfs/grid/atlas/atlaslocalgroupdisk/?xrd.gsiusrpxy=/tmp/x509up_u38502, flags: none) (0x800dfc0), 97 bytes
> [2020-04-07 17:58:24.350912 +0200][Dump   ][AsyncSock         ] [xrootd008.physik.uni-bonn.de:1094 #0.0] Successfully sent message: kXR_stat (path: //cephfs/grid/atlas/atlaslocalgroupdisk/?xrd.gsiusrpxy=/tmp/x509up_u38502, flags: none) (0x800dfc0).
> [2020-04-07 17:58:24.350927 +0200][Dump   ][XRootD            ] [xrootd008.physik.uni-bonn.de:1094] Message kXR_stat (path: //cephfs/grid/atlas/atlaslocalgroupdisk/?xrd.gsiusrpxy=/tmp/x509up_u38502, flags: none) has been successfully sent.
> [2020-04-07 17:58:24.350935 +0200][Debug  ][ExDbgMsg          ] [xrootd008.physik.uni-bonn.de:1094] Moving MsgHandler: 0x8002b70 (message: kXR_stat (path: //cephfs/grid/atlas/atlaslocalgroupdisk/?xrd.gsiusrpxy=/tmp/x509up_u38502, flags: none) ) from out-queu to in-queue.
> [2020-04-07 17:58:24.350945 +0200][Dump   ][PostMaster        ] [xrootd008.physik.uni-bonn.de:1094 #0.0] All messages consumed, disable uplink
> [2020-04-07 17:58:24.368834 +0200][Dump   ][XRootDTransport   ] [msg: 0xf1610] Expecting 44 bytes of message body
> [2020-04-07 17:58:24.368860 +0200][Dump   ][AsyncSock         ] [xrootd008.physik.uni-bonn.de:1094 #0.0] Received message header for 0xf1610 size: 8
> [2020-04-07 17:58:24.368874 +0200][Dump   ][AsyncSock         ] [xrootd008.physik.uni-bonn.de:1094 #0.0] Received message 0xf1610 of 52 bytes
> [2020-04-07 17:58:24.368883 +0200][Dump   ][PostMaster        ] [xrootd008.physik.uni-bonn.de:1094 #0] Handling received message: 0xf1610.
> [2020-04-07 17:58:24.368957 +0200][Dump   ][XRootD            ] [xrootd008.physik.uni-bonn.de:1094] Got a kXR_ok response to request kXR_stat (path: //cephfs/grid/atlas/atlaslocalgroupdisk/?xrd.gsiusrpxy=/tmp/x509up_u38502, flags: none)

and everything went fine, but then the client sends `kXR_dirlist` to the manager (`xrootd.physik.uni-bonn.de:1094`):

> [2020-04-07 17:58:24.501107 +0200][Dump   ][FileSystem        ] [0x80031c8@xrootd.physik.uni-bonn.de:1094] Sending kXR_dirlist (path: //cephfs/grid/atlas/atlaslocalgroupdisk/)
> [2020-04-07 17:58:24.501116 +0200][Dump   ][XRootD            ] [xrootd.physik.uni-bonn.de:1094] Sending message kXR_dirlist (path: //cephfs/grid/atlas/atlaslocalgroupdisk/)
> [2020-04-07 17:58:24.501127 +0200][Debug  ][ExDbgMsg          ] [xrootd.physik.uni-bonn.de:1094] MsgHandler created: 0x8003a00 (message: kXR_dirlist (path: //cephfs/grid/atlas/atlaslocalgroupdisk/) ).
> [2020-04-07 17:58:24.501138 +0200][Dump   ][PostMaster        ] [xrootd.physik.uni-bonn.de:1094 #0] Sending message kXR_dirlist (path: //cephfs/grid/atlas/atlaslocalgroupdisk/) (0x8002190) through substream 0 expecting answer at 0
> [2020-04-07 17:58:24.501207 +0200][Dump   ][AsyncSock         ] [xrootd.physik.uni-bonn.de:1094 #0.0] Wrote a message: kXR_dirlist (path: //cephfs/grid/atlas/atlaslocalgroupdisk/) (0x8002190), 64 bytes
> [2020-04-07 17:58:24.501223 +0200][Dump   ][AsyncSock         ] [xrootd.physik.uni-bonn.de:1094 #0.0] Successfully sent message: kXR_dirlist (path: //cephfs/grid/atlas/atlaslocalgroupdisk/) (0x8002190).
> [2020-04-07 17:58:24.501231 +0200][Dump   ][XRootD            ] [xrootd.physik.uni-bonn.de:1094] Message kXR_dirlist (path: //cephfs/grid/atlas/atlaslocalgroupdisk/) has been successfully sent.
> [2020-04-07 17:58:24.501237 +0200][Debug  ][ExDbgMsg          ] [xrootd.physik.uni-bonn.de:1094] Moving MsgHandler: 0x8003a00 (message: kXR_dirlist (path: //cephfs/grid/atlas/atlaslocalgroupdisk/) ) from out-queu to in-queue.
> [2020-04-07 17:58:24.501246 +0200][Dump   ][PostMaster        ] [xrootd.physik.uni-bonn.de:1094 #0.0] All messages consumed, disable uplink
> [2020-04-07 17:58:24.515558 +0200][Dump   ][XRootDTransport   ] [msg: 0x53c0] Expecting 96 bytes of message body
> [2020-04-07 17:58:24.515587 +0200][Dump   ][AsyncSock         ] [xrootd.physik.uni-bonn.de:1094 #0.0] Received message header for 0x53c0 size: 8
> [2020-04-07 17:58:24.515602 +0200][Dump   ][AsyncSock         ] [xrootd.physik.uni-bonn.de:1094 #0.0] Received message 0x53c0 of 104 bytes
> [2020-04-07 17:58:24.515611 +0200][Dump   ][PostMaster        ] [xrootd.physik.uni-bonn.de:1094 #0] Handling received message: 0x53c0.
> [2020-04-07 17:58:24.515641 +0200][Dump   ][XRootD            ] [xrootd.physik.uni-bonn.de:1094] Got a kXR_error response to request kXR_dirlist (path: //cephfs/grid/atlas/atlaslocalgroupdisk/) [3011] Unable to open directory /cephfs/grid/atlas/atlaslocalgroupdisk/; no such file or directory

but this time the manager is not redirecting, it is just returning an error.

**Comment by olifre** [comment] 2020-04-07 17:37
@simonmichal Thanks, that looks like a bug on the XRootD end... 
For comparison, it seems `xrdfs ls` issues `kXR_locate` to the manager and then contacts all the separate nodes (eight on our case) one by one, retrieving `kXR_dirlist` from each of them (and then probably merging / unifying the lists locally). So it never contacts the manager with `xKR_dirlist`, which explains why it does not show this issue.

**Comment by abh3** [comment] 2020-04-07 20:08
Ah, I looked at the code and, yes, the opendir() does not redirect. I vaguely recall this was intentional given Babar's work flow. They would always do a stat() and then do an dirlist at that location. That workflow no longer exists so there is no reason to keep this behavior. I will fix this and it can be back ported to 4.12.0 (or earlier if there is a need for that).

**Comment by abh3** [comment] 2020-04-08 04:17
This has been fixed via commit a20fe39385e7c02f09e64befd349a7ca8a9a707f for R5. I will leave this open so that we can get confirmation whether or not that this will be back-ported to 4.x.y.

**Comment by simonmichal** [comment] 2020-04-08 07:48
@abh3 : I would say yes, we back port it to stable-4.12.x.

**Comment by abh3** [comment] 2020-04-08 15:46
@michal OK, but part of it will be a dirty back-port so let's talk about 
it offline.

**Comment by simonmichal** [comment] 2020-04-09 16:05
I think we are all set, can we close the issue?

**Comment by xrootd-dev** [comment] 2020-04-09 18:33
Indeed, we can.

**Comment by abh3** [comment] 2020-04-09 18:33
Fixed.

**Closed by abh3** 2020-04-09 18:33 UTC

**Comment by olifre** [comment] 2020-06-05 10:55
For future reference, in case somebody stumbles upon this in the future:
- This went into 4.12.1. 
- Since it caused issues with existing consumers (DPM), the default behaviour was reverted in 4.12.2. 
- With 4.12.2, you can now set `ofs.dirlist remote` to get the behaviour asked for in this issue. 

Works well here :-).

**Comment by simonmichal** [comment] 2020-06-05 11:01
@olifre : thanks for reminding me about it, I'll include this in the release announcement!

**Comment by olifre** [comment] 2020-06-05 11:01
@simonmichal Thanks! We are upgrading just now, and indeed the feature works as expected :-).

**Comment by ivmfnal** [comment] 2020-06-30 14:10
Hello. I am reading this thread and I want to make sure I understand it correctly that ofs.dirlist controls how "xrdfs ls" works - whether the request is handled locally by the redirector or by the client contacting each individual server directly ? Or do I get it wrong ?

**Comment by abh3** [comment] 2020-06-30 19:46
No, the ofs.dirlist is there strictly for opendir() calls. The issue is 
that xrdfs ls does a locate ahead of the opendeir() because it wants to be 
nice and give you a composite directory listing. If the server is 
unclustered this works just fine. If servers are clustered (i.e. headed by 
a redirector) this usually works fine as well. The only case it breaks 
down is wen the servers share a common file system. While the end results 
is correct the whole process is very slow. We have a couple of ways around 
this and will be implementing at least one of those to mitigate the issue. 
Anyway, the default for ofs.dirlist provides full backward compatibility 
(i.e. things work as before the introduction of eh directive).
