### ISSUE TITLE
xrdcp crash below XrdCpFile::Extend()

### ISSUE THREAD

**Issue by jmuf** [xrootd/xrootd#1040] opened 2019-08-19 06:57 UTC
FYI - 3 backtraces by the same user/client host/pathnames, within a few minutes. No coredumps available. Version is "xrootd-client-4.9.1-1.el7".
```
backtrace:
:Core was generated by `xrdcp -rv /afs/cern.ch/cms/[snip]/ root://eoscms//eos/cms/[snip]'.
:Program terminated with signal 11, Segmentation fault.
:#0  0x00007f4026c8b71c in free () from /lib64/libc.so.6
:#0  0x00007f4026c8b71c in free () from /lib64/libc.so.6
:#1  0x00007f4027835a6a in XrdOucNSWalk::~XrdOucNSWalk() () from /lib64/libXrdUtils.so.2
:#2  0x00007f4027a97dd4 in XrdCpFile::Extend(XrdCpFile**, int&, long long&) () from /lib64/libXrdAppUtils.so.1
:#3  0x00007f4027a96d03 in XrdCpConfig::Config(int, char**, int) () from /lib64/libXrdAppUtils.so.1
:#4  0x0000000000404cc0 in main ()
```
```
backtrace:
:Core was generated by `xrdcp -rv /afs/cern.ch/cms/[snip]/ root://eoscms//eos/cms/[snip]'.
:Program terminated with signal 11, Segmentation fault.
:#0  0x00007fe8a830371c in free () from /lib64/libc.so.6
:#0  0x00007fe8a830371c in free () from /lib64/libc.so.6
:#1  0x00007fe8a8eada6a in XrdOucNSWalk::~XrdOucNSWalk() () from /lib64/libXrdUtils.so.2
:#2  0x00007fe8a910fdd4 in XrdCpFile::Extend(XrdCpFile**, int&, long long&) () from /lib64/libXrdAppUtils.so.1
:#3  0x00007fe8a910ed03 in XrdCpConfig::Config(int, char**, int) () from /lib64/libXrdAppUtils.so.1
:#4  0x0000000000404cc0 in main ()
```
```
backtrace:
:Core was generated by `xrdcp -rv /afs/cern.ch/cms/[snip]/ root://eoscms//eos/cms/[snip]'.
:Program terminated with signal 6, Aborted.
:#0  0x00007fa1a56652c7 in raise () from /lib64/libc.so.6
:#0  0x00007fa1a56652c7 in raise () from /lib64/libc.so.6
:#1  0x00007fa1a56669b8 in abort () from /lib64/libc.so.6
:#2  0x00007fa1a56a7e17 in __libc_message () from /lib64/libc.so.6
:#3  0x00007fa1a5746b67 in __fortify_fail () from /lib64/libc.so.6
:#4  0x00007fa1a5744ce2 in __chk_fail () from /lib64/libc.so.6
:#5  0x00007fa1a625f9fd in XrdOucNSWalk::setPath(char*) () from /lib64/libXrdUtils.so.2
:#6  0x00007fa1a625fa99 in XrdOucNSWalk::Index(int&, char const**) () from /lib64/libXrdUtils.so.2
:#7  0x00007fa1a64c0d19 in XrdCpFile::Extend(XrdCpFile**, int&, long long&) () from /lib64/libXrdAppUtils.so.1
:#8  0x00007fa1a64bfd03 in XrdCpConfig::Config(int, char**, int) () from /lib64/libXrdAppUtils.so.1
:#9  0x0000000000404cc0 in main ()
```

**Comment by abh3** [comment] 2019-08-19 22:24
Hi Jan,

Could you install the debug-infos so we can get statement numbers? I 
assume this is reproducible and likely has something to do with the 
contents of the directory. So, perhaps you could send me (i.e. not post) 
the ls -LR of the stuff you are trying to copy.

Andy

**Comment by abh3** [comment] 2020-11-19 20:38
We have tried reproduce this and were unable to do so. Since we moved onto several releases ahead, I am closing this. Should tis happen again, please create a new ticket.

**Closed by abh3** 2020-11-19 20:38 UTC
Labels: bug (non-critical)
