### ISSUE TITLE
Xrootd configuration certain parameters cannot be redefined

### ISSUE THREAD

**Issue by efajardo** [xrootd/xrootd#999] opened 2019-06-12 23:32 UTC
We have found that after some config knobs are set in the config but then are reset later in the same config file on in another config file using continue they all use the original values. Knobs we have found so far are:

1. httpd port
1. pss.origin

@brianhlin

**Comment by abh3** [comment] 2019-06-14 19:27
I guess I need more context here. What is the actual problem? Is it XRootD specific or merely that the config files are not consistent.

**Comment by efajardo** [comment] 2019-06-14 19:34
This is what I mean
```
xrd.protocol http:8000 libXrdHttp.so
xrd.protocol http:9000 libXrdHttp.so
```

Then an xrootd server would retain 8000

**Comment by abh3** [comment] 2019-06-14 19:48
Ah, what I think you will find is that HTTP will then run on both ports. Looking at he code, the protocol directive is additive as you can run as many of those as you want.

**Comment by efajardo** [comment] 2019-06-17 15:08
Hi @abh3 this was definetly not the case with HTTP and it only used the first one

**Comment by abh3** [comment] 2020-03-31 06:54
OK, I just reran the test and the example work the way it was supposed to. The second protocol directive overrode the first and port 9000 was used. Could you show a more specific case of where this is not the case? I mean with the config file and the full output of the initialization part of the log.

**Comment by abh3** [comment] 2020-04-17 04:25
OK, no response on this. I am tempted to close it as it appears to not be reproducible and may be dure o a local configuration mistake.

**Comment by efajardo** [comment] 2020-04-17 17:17
@abh3 sorry for the late so here it is how to reproduce it. 

1. I start a process that listens on port (8000)
    ```console
         nc -l 8000 &
    ```
1. Then I create a file `/etc/xrootd/config.d/99-for-andy-test.cfg`
   ```file
        xrd.protocol http:9000 libXrdHttp.so
    ```
1. Start stashcache:
   ```console
    systemctl start xrootd@stash-cache.service
   ```
1. See that xrootd fails to start although the port has been redefined to use 9000 and not 8000:
   ```file
    ------ xrootd protocol initialization completed.
   200417 12:08:54 18523 XrdOpen: Unable to bind socket to port 8000; address already in use
    ------ xrootd stash-cache@fermicloud115.fnal.gov:1094 initialization failed.
    ```

The configuration is here:

```file
 cconfig -c /etc/xrootd/xrootd-stash-cache.cfg 
xrd.port 1094
continue /etc/xrootd/config.d
Config continuing with file /etc/xrootd/config.d/10-common-site-local.cfg ...
Config continuing with file /etc/xrootd/config.d/10-xrootd-lcmaps.cfg ...
Config continuing with file /etc/xrootd/config.d/40-stash-cache-plugin.cfg ...
ofs.osslib libXrdPss.so 
pss.cachelib libXrdFileCache.so 
pss.origin redirector.osgstorage.org:1094 
pss.setopt ParallelEvtLoop 10 
pss.setopt RequestTimeout 25 
pss.setopt ConnectTimeout 25 
pss.setopt ConnectionRetry 2 
pfc.blocksize 512k 
pfc.ram 1g 
pfc.prefetch 10 
pfc.diskusage 0.90 0.95 
Config continuing with file /etc/xrootd/config.d/40-xcache-auth.cfg ...
Config continuing with file /etc/xrootd/config.d/40-xrootd-lcmaps.cfg ...
Config continuing with file /etc/xrootd/config.d/50-osg-http.cfg ...
xrd.protocol http:8000 libXrdHttp.so 
http.cadir /etc/grid-security/certificates 
http.cert /etc/grid-security/xrd/xrdcert.pem 
http.key /etc/grid-security/xrd/xrdkey.pem 
http.secxtractor /usr/lib64/libXrdLcmaps.so 
http.exthandler xrdmacaroons libXrdMacaroons.so 
macaroons.secretkey /etc/xrootd/macaroon-secret 
ofs.authlib libXrdMacaroons.so 
http.header2cgi Authorization authz 
http.listingdeny yes 
http.staticpreload http://static/robots.txt /etc/xrootd/ban-robots.txt 
Config continuing with file /etc/xrootd/config.d/50-osg-monitoring.cfg ...
all.sitename Edgar_FERMICLOUD_VM115 
xrd.report xrd-report.osgstorage.org:9931 
xrootd.monitor all auth flush 30s window 5s fstat 60 lfn ops xfr 5 dest redir fstat info user xrd-report.osgstorage.org:9930 dest fstat info user xrd-mon.osgstorage.org:9930 
Config continuing with file /etc/xrootd/config.d/50-osg-paths.cfg ...
all.adminpath /var/spool/xrootd 
all.pidpath /run/xrootd 
oss.localroot /tmp 
Config continuing with file /etc/xrootd/config.d/50-stash-cache-authz.cfg ...
ofs.authorize 1 
acc.audit deny grant 
xrd.allow host * 
sec.protocol host 
xrootd.diglib * /etc/xrootd/digauth.cfg 
Config continuing with file /etc/xrootd/config.d/50-stash-cache-paths.cfg ...
all.export / 
Config continuing with file /etc/xrootd/config.d/90-stash-cache-disks.cfg ...
Config continuing with file /etc/xrootd/config.d/90-xcache-logging.cfg ...
xrootd.trace emsg login stall redirect 
pfc.trace info 
ofs.trace most 
xrd.trace all -sched 
cms.trace all 
pss.setopt DebugLevel 1 
Config continuing with file /etc/xrootd/config.d/99-for-andy-test.cfg ...
xrd.protocol http:9000 libXrdHttp.so 
```


And I am uploading the log right here:  [xrootd.log](https://github.com/xrootd/xrootd/files/4494321/xrootd.log)

**Comment by abh3** [comment] 2020-04-18 00:43
So, it was obviously the case that I was using another release to reproduce this. Indeed, the 4.x series has the problem. The 5.x series does not have the problem. I can go hunting on what changed and since we have a 4.x-RC we could include this in 4.x if you feel it's important enough.

**Comment by efajardo** [comment] 2020-04-20 15:42
Well I do not know if it is important to fix it. Since we can get around it. Same problem btw happens when redefining (xrd.port).

**Comment by brianhlin** [comment] 2020-04-20 17:19
Yeah, since we already have a 4.12.0 RC1, let's sneak this fix in.

**Comment by abh3** [comment] 2020-04-20 21:58
OK, I will check that out as well. It's likely caught up with the changes 
in R5 and may have fixed that as well.

**Comment by abh3** [comment] 2020-05-19 05:09
Obviously, we now have 4.12.1 and nothing changed. Should we just close this ticket?

**Comment by abh3** [comment] 2020-11-19 20:45
Given no response on this it would appear this issue has been resolved.

**Closed by abh3** 2020-11-19 20:45 UTC
Labels: bug (non-critical)
