### ISSUE TITLE
Directory listing with xrdcp -r against redirector fails

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#954] opened 2019-03-29 18:59 UTC
Following setup:
- Redirector without direct filesystem access, configured like:
```cms.dfs limit 0 lookup distrib mdhold 0 redirect immed retries 2```
- All data nodes have access to the files (i.e. shared filesystem behind them). 

Now, listing a directory with `xrdfs` works fine:
```
$ xrdfs redirector.example.com ls -ul /cephfs/grid/atlas/user/scratch/freyermu
/cephfs/grid/atlas/user/scratch/freyermu/bla.root
/cephfs/grid/atlas/user/scratch/freyermu/blub
```
and on the redirector, I see:
```
Decode xrootd sent XXX@YYY 'Swxrootd003.example.com Swxrootd001.example.com:1094 Swxrootd006.example.com:1094 Swxrootd007.example.com:1094 Swxrootd002.example.com Swxrootd004.example.com Swxrootd005.example.com:1094' */cephfs/grid/atlas/user/scratch/freyermu
```
Up to now, all is well. But `xrdcp -r` fails:

```
$ xrdcp --debug 1 -r xroot://redirector.example.com:1094//cephfs/grid/atlas/user/scratch/freyermu/ bla/
[2019-03-29 19:55:19.309750 +0100][Info   ][App               ] Failed to get directory listing for xroot://redirector.example.com:1094//cephfs/grid/atlas/user/scratch/freyermu/: Unable to open directory /cephfs/grid/atlas/user/scratch/freyermu/; no such file or directory
Error indexing remote directory.
```
In the logs of the redirector, I find:
```
Decode xrootd redirects XXX@YYY to xrootd001.example.com:1094 /cephfs/grid/atlas/user/scratch/freyermu/
ofs_opendir: XXX@YYY Unable to open directory /cephfs/grid/atlas/user/scratch/freyermu/; no such file or directory
```
So for some reason, it seems that the directory listing requested by `xrdcp -r` is not honuring `lookup distrib` but performed on the redirector - even worse, the redirector checks locally instead of performing a distributed lookup itself. 

Doing an `xrdcp` of single files works fine, of course. 

Is this a misconfiguration somewhere? Since `xrdfs ls` works, I doubt it, but let me know if something comes to mind.

**Comment by simonmichal** [comment] 2019-04-03 08:55
@olifre : thanks for reporting this problem, could provides us with an endpoint where I can reproduce the problem with xrootd client? Alternatively, could you run xrdcp/xrdfs with XRD_LOGLEVEL=Dump and provides us with respective logs? Also, could you try running xrdfs ls with -R option and see if this has any effect?

**Comment by olifre** [comment] 2019-04-03 21:24
@simonmichal : I could grant you access to the existing setup if you had an X509 cert registered with the ATLAS VO (I did not find you in VOMS; so I guess you don't have one). 

`-R` for `xrdfs ls` worked fine, no issues there. Only `xrdcp -r` has problems. 

So I followed up with the debug logs. The logs are only slightly obfuscated (IP addresses, hostnames). The redirector is `xrootd.example.com`, the nodes with access to the shared FS are all `xrootdXXX.example.com` with XXX being a three-digit number. There are nodes from 001 to 007. 

Here you go:
 - Log from `xrdfs ... ls -ul ...` 
   [xrdfs-lsul.log](https://github.com/xrootd/xrootd/files/3040780/xrdfs-lsul.log)
 - Log from `xrdfs ... ls -R ...`
   [xrdfs-lsR.log](https://github.com/xrootd/xrootd/files/3040784/xrdfs-lsR.log)
 - Log from `xrdcp -r ... ...`
   [xrdcp-r.log](https://github.com/xrootd/xrootd/files/3040789/xrdcp-r.log)

**Comment by simonmichal** [comment] 2019-04-05 14:20
@olifre : Thanks a lot for the logs, that's a big help! The conclusion based on what I see in the logs is that xrdcp is missing the `DirListFlags::Locate` flag when issuing `FileSystem::DirList`. I just pushed a patch: a3ad80d16cda5c63189e587735d1297b438924d0, could you please test?

**Comment by olifre** [comment] 2019-04-05 18:15
@simonmichal Very nice, indeed this helps! I'm still on 4.9.0 on the client, so I am affected by #910 , but the files arrive just fine!  :+1: 

There is one issue uncovered by this, however: In our case, there are 7 data servers behind the redirector, and they all see the same underlying FS. `xrdfs ... ls` merges those lists so the files are only shown once. With `xrdcp -r` though, each file is seen 7 times, so I get 7 copy jobs per file, and 6 failures of the kind:
```
Job #3: [ERROR] Server responded with an error: [3006] File exists
```
Do you want to treat this in a separate issue, and do you want debug logs?

**Comment by simonmichal** [comment] 2019-04-08 13:29
@olifre : let's keep it all within this ticket, I pushed another patch: e69790effc61f3fe35c6b9a961ef773116db2b27, could you please test?

If it works please don't close this issue because I'd like to clarify with @abh3 (once his back from holidays) why the `kXR_locate` request works with a _cmsd_ with `cms.dfs` directive and `kXR_dirlist` not.

**Comment by olifre** [comment] 2019-04-08 20:17
@simonmichal Perfect, after applying that patch in addition, now everything works fine! 

Of course, let's leave this open until that's clarified.

**Comment by simonmichal** [comment] 2019-04-09 06:49
@olifre : thanks for testing :-)

**Comment by abh3** [comment] 2019-04-20 00:44
The answer is simply that kXR_dirlist is not redirected. I suppose we could redirect it to some server that has the directory. There is no history for why it was not made redirect-able. I suppose the reason may be that you would never get a full result if we did that and you would get different listings on each try depending on where you got redirected. That made it somewhat useless to redirect a dirlist request.

**Comment by simonmichal** [comment] 2019-04-20 19:40
OK, I think we have now a good understanding of this issue and also a working solution using `dirlist` with `LOCATE` and `MERGE` flags.

**Closed by simonmichal** 2019-04-20 19:40 UTC
