### ISSUE TITLE
Checksum: HTTP 500 Unexpected server error

### ISSUE THREAD

**Issue by stlammel** [xrootd/xrootd#1816] opened 2022-11-02 19:56 UTC
Dear xrootd team,
   as part of the WLCG DOMA project we like to improve WebDAV error codes and messages.
We have identified an intermittent checksum failure at a site that returns an "HTTP 500 Unexpected server error". Could you please help us understand the cause and handle this failure with a more informative message?
   The error/error message occurs on an ADLER32 checksum (after a write of the file) in the CMS SAM tests. An example SAM output is at
https://monit-grafana.cern.ch/d/siYq3DxZz/wlcg-sitemon-test-details?orgId=20&var-dst_hostname=webdav.ifca.es&var-metric=org.cms.SE-WebDAV-6crt-write&var-timestamp=1666193572000
   There is an open GGUS ticket with the site where the error occurs,
https://ggus.eu/ws/ticket_info.php?ticket=159284
Feel free to comment in GGUS, ask the site admins for additional information, different logging being turned on, etc. (If you are not yet registered in GGUS, please use the registration link in the upper left and check the support access flag.)
   Thanks,
        cheers,  Stephan

**Comment by ccaffy** [comment] 2023-05-25 12:40
Hello @stlammel ,

I believe this issue is not relevant anymore if the XRootD server version is >= 5.5.4.
It contains some fixes related to checksums matching with HTTP: https://github.com/xrootd/xrootd/blob/master/docs/ReleaseNotes.txt

Do you confirm it works as you expect?

Thanks.

**Comment by stlammel** [comment] 2023-05-25 15:44
@ccaffy 
I can't say if this particular HTTP 500 relating to checksums provides a better error message now. I'll take your work for it.
(We do still see HTTP 500 errors regularly that don't provide more details on what went wrong/allows users or admins to find the issue quickly.)
Thanks,
 - Stephan

**Comment by ccaffy** [comment] 2023-05-25 15:57
This one should not give 500 error anymore. So I'll close this particular issue. 

If you find 500 errors, did you manage to identify the cause from the logs? If that's the case, please open a ticket that will allow me to identify and fix the error preventing the message to be clear ;)

Thanks a lot in advance.

**Closed by ccaffy** 2023-05-25 15:57 UTC
Labels: enhancement

**Comment by stlammel** [comment] 2023-05-25 16:11
@ccaffy 
I believe user reties and service restart by sysadmins is the common approach.
Ok, will open a ticket again when we find a persistent HTTP 500 again.
Thanks,
 - Stephan
