### ISSUE TITLE
[XrdSsi] GetMetadata loses first character

### ISSUE THREAD

**Issue by slithy** [xrootd/xrootd#537] opened 2017-07-04 12:43 UTC
When using Set/GetMetadata in SSI extensions, the first character of the metadata is lost:

**On server side:**
```
std::string response_str = "HELLO WORLD";
SetMetadata(response_str.c_str(), response_str.size());
```
This puts 11 bytes of metadata on the wire: HELLO WORLD
48 45 4C 4C 4F 20 57 4F 52 4C 44

**On client side:**
```
const char *metadata_buffer = GetMetadata(metadata_len);
```
We receive a payload of the correct size (11 bytes) but the first byte is zero:
0 45 4C 4C 4F 20 57 4F 52 4C 44 
metadata_len = 11, metadata_buffer = <0>ELLO WORLD

**Comment by abh3** [comment] 2017-07-06 03:55
I ran my verification test and it didn't reproduce the problem. After asking it to send '12345678' I got this on the client side:
theMD = GetMetadata(theML);
(gdb) p theMD
$1 = 0x7fffc0000950 "12345678"
(gdb) p theML
$2 = 9

The response structure also is completely correct.

(gdb) p rInfo
$3 = (const XrdSsiRespInfo &) @0x6193e8: {{buff = 0x7fffc0000959 "how now brown cow ",
    eMsg = 0x7fffc0000959 "how now brown cow ", fsize = 140736414615897,
    strmP = 0x7fffc0000959}, {blen = 19, eNum = 19, fdnum = 19}, mdlen = 9,
  mdata = 0x7fffc0000950 "12345678", rType = XrdSsiRespInfo::isData}

I suspect you may have fallen into the std::string c_str() trap. As the metadata must remain valid until the Responder's Finished() method is called. Using std:string is a rather precarious way of doing it since if the string goes out of scope or gets altered prior to Finished() being called, the behavior is undefined and you may be sending bad bytes. It would appear here that the string was reset to the null string before the metadata was actually sent.

**Closed by abh3** 2017-07-06 03:55 UTC

**Comment by slithy** [comment] 2017-07-06 08:29
OK, thanks, I understand now. I didn't realise it was zero-copy. The solution was to make the string a member of the XrdSsiResponder subclass so it stays in scope until after Finished() is called.

std::string is convenient as I am using Google Protocol Buffers to pack and unpack the messages and the API provides a SerializeToString() method.
