### ISSUE TITLE
Always send PerformanceMarker for HTTP transfers

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#1785] opened 2022-09-21 15:48 UTC
The PerformanceMarker is used to indicate to the requester what IP protocol (IPv4, IPv6, or both) is used for the actual data movement.  These are then utilized by FTS to populate information for various monitoring dashboards.

@mpatrascoiu has pointed out that these are only sent for transfers lasting >5 seconds meaning there's no IP protocol data available for short file transfers.  He's requested (and I agree!) that these also be generated for short transfers (<5 seconds) to avoid a hole in the monitoring.

**Comment by abh3** [comment] 2022-09-22 06:48
That should be relatively easy by simply moving the place where the perf timer is started. Am I to assume that you will provide the patch?

**Comment by ccaffy** [comment] 2022-09-23 13:10
If you want I can do it as I am supposed to be the maintainer of XrdHttpTPC.
Tell me :)

Cheers,
Cedric

**Comment by ccaffy** [comment] 2022-09-23 13:47
Thanks @bbockelm for your explanations :) I'll take a look at it after I'm done with the issue : https://github.com/xrootd/xrootd/pull/1778

**Comment by abh3** [comment] 2022-09-23 19:47
Hi Cedric,

Sure!

Andy

**Comment by abh3** [comment] 2022-09-23 19:49
Actually, we already capture that information for TPC g-stream monitoring 
which I always said was the preferable way of doing this instead of 
relying on perf markers. So, it's just a matter of propogating that IP 
address.

**Comment by abh3** [comment] 2022-09-23 19:57
So, for more info see the TPCHandler::opensocket_callback() as this may simplify everything. You can also trigger perf marking from there, though perhaps not the safest thing to do from a curl callback function as curl is pretty temperamental.

**Comment by ccaffy** [comment] 2023-02-13 10:39
Hi all,

I cannot reproduce this as it is working properly. @mpatrascoiu can confirm it works on his side as well...

In the case I do a TPC transfer of a 5MB file, I get the perf marker at the end of the transfer:
```
Perf Marker
Timestamp: 1676284187
Stripe Index: 0
Stripe Bytes Transferred: 0
Total Stripe Count: 1
RemoteConnections: tcp:137.138.123.14:1096
End
```

If I do a large file TPC transfer, I get the perf markers as well...

@mpatrascoiu can confirm it worked when he tried on his side...

Please tell me if I missed something here :) Otherwise this issue can be closed.

**Comment by bbockelm** [comment] 2023-02-21 02:42
Mihai was the one who reported this problem originally ... so if it's working now, let's go ahead and close out!

**Comment by ccaffy** [comment] 2023-05-25 12:42
Closing!

**Closed by ccaffy** 2023-05-25 12:42 UTC
Labels: enhancement
