### ISSUE TITLE
Creating new processes randomly fails with EPoll: Bad file descriptor polling for events

### ISSUE THREAD

**Issue by chrisburr** [xrootd/xrootd#1198] opened 2020-05-19 10:46 UTC
When `XRD_RUNFORKHANDLER` is set, launching new processes can be fail due to a race between the main thread and XRootD's polling thread.

This isn't Python specific (and I'm using GFAL2 instead of the XRootD python bindings) but I'll explain how it happens using it as an example. When `subprocess` creates a new process it works by:

1. Calling `clone` on the current process
2. If `close_fds=True` then call `close` on all open file descriptors (Python 2.7 does it by closing all possible file descriptors but it's not relevant)
3. Start the requested process using `execve`

If `XRD_RUNFORKHANDLER` is set, the `pthread_atfork` hook causes `XrdSys::IOEvents::Poller::newPoller` to call `epoll_create1` to create a new epoll file descriptor . The newly cloned process then proceeds to close all of the open file descriptors. If `XrdSys::IOEvents::PollE::Begin` runs before the main thread calls `execvp` it finds [the file descriptor is closed and aborts](https://github.com/xrootd/xrootd/blob/250eced4d3787c2ac5be2c8c922134153bbf7f08/src/XrdSys/XrdSysIOEventsPollE.icc#L214-L222) after printing `EPoll: Bad file descriptor polling for events`.

I've struggled to make it crash locally however I can see it ~20% of the time in real jobs submitted to some WLCG sites.

While I can come up with workarounds, I think the underlying issue needs to be fixed as quite a few libraries set `XRD_RUNFORKHANDLER` for good reasons and then perfectly correct user code will randomly fail.

**Comment by simonmichal** [comment] 2020-05-19 12:04
@chrisburr : thanks for reporting this problem, I'll see how we can fix this.

**Comment by chrisburr** [comment] 2020-06-08 09:03
Have you had any further thoughts about this?

**Comment by simonmichal** [comment] 2020-06-08 09:05
@chrisburr : sorry I haven't had time yet to look into it, but I try to find some time this weeks, thanks for the reminder!

**Comment by chrisburr** [comment] 2020-06-08 09:13
No worries! It's not urgent as unsetting the environment variable is a good enough workaround for now.

**Comment by marianne013** [comment] 2021-05-21 17:30
We recently had a user run into this, are there any updates ?

**Comment by simonmichal** [comment] 2021-06-08 09:36
@chrisburr : sorry for the delay, I finally had time to look at the problem. It seems to me that allowing the poller to fail more gracefully than just calling an `abort` should fix the problem:

https://github.com/xrootd/xrootd/blob/250eced4d3787c2ac5be2c8c922134153bbf7f08/src/XrdSys/XrdSysIOEventsPollE.icc#L214-L223

That said, it puzzles me that you observed the same problem with GFAL2. GFAL2 is not doing any kind of file descriptor handling behind the scene (AFAIK). Now the `epoll_create1` is called with `EPOLL_CLOEXEC` but I don't thing the close-on-exec is subject to race conditions. Any thoughts?

**Comment by chrisburr** [comment] 2021-06-08 10:12
> It seems to me that allowing the poller to fail more gracefully than just calling an abort should fix the problem

I agree that it's probably the best solution.

> That said, it puzzles me that you observed the same problem with GFAL2. GFAL2 is not doing any kind of file descriptor handling behind the scene (AFAIK). Now the epoll_create1 is called with EPOLL_CLOEXEC but I don't thing the close-on-exec is subject to race conditions. Any thoughts?

It's been a while since I thought about this but I think gfal2 was only involved because it happened to be the way XRootD was being loaded. I could probably have reproduced it with just `xrootd` and `fork` but I stopped once I understood the problem well enough to open this issue.

**Comment by simonmichal** [comment] 2021-06-08 10:22
Well, yes if it was reproducible with gfal2 it probably also was with plain xrootd client, but what is in this case closing the file descriptor in between the `fork` and `exec`? In case of `subprocess` + `close_fds=True` it is the Python runtime, isn't it?

**Comment by simonmichal** [comment] 2021-06-08 15:42
@chrisburr : I have a possible bug fix: 66f8de9b670e9fddfd95cc0080981532d13db339 in issue1198 in the https://github.com/xrootd/xrootd/tree/issue1198 branch. Could you give it a try? (I tried out the scenario you described but cannot reproduce the problem)

**Comment by abh3** [comment] 2021-06-08 18:04
Well, I looked at the patch and it seems like it really is not the right 
solution to this problem. As I understand it, the problem is due to the 
runforkhandler which is executed in the child. By design, it assumes 
continuation and is not aware that it's being prepared for an exec() call. 
Hence it does things that need not be done like create a new poller. This 
is a design flaw and the proposed update is putting in unnecessary checks 
to cover up that design flaw. There are three solutions to this problem:

1) When registering a fork handler, tell the fork handler what the 
intention is (i.e. continuation at fork or it's for an exec() call). If 
it's for an exec call then the child handler should not be reinitializing 
the newly created process. In fact, one could simply no-op the whole 
cheld part as it's useless work. That would avoid the problem, albiet it 
would requrie an application change to make use of this.

2) If you want to avoid the ABI change (which I think is the correct 
solution). Tell the newly created poller that it being created due to a 
fork(). This would allow the poller to simply ignore EBADF and simply 
exit the thread when it gets the error. Unfortuantely, this would 
potentially mask other problems that are legitmate errors but that's 
another issue.

3) The poller could initialize a static variable with the original process 
number. Should it get an EBADF error it could check if that is in the 
original process or in a new process and exit the thread assuming that 
it's due to the forkhandler design flaw. This is simply a variation of 
(2).

Any of these solutions would avoid having to litter the code with tests 
for "poller error" to cover up the fork handler's ignorance in this 
particular case.

So, I wouldn't apply this patch.

Andy

**Comment by abh3** [comment] 2021-06-08 19:24
One additional observation. To get around this fork handler problem in a compatible way one could introduce a new envar (you could potentially piggy back on the existing one) which tells the client why you want to run the fork handler. The two values would be "for_exec" or "for_client". When "for_rexec" is set the client side of the fork handler does not start any new threads which means it would not create a poller. The "for_client" setting would do what it does today. The default is controversial. Obviously, CMS and some ATLAS jobs do "for_client" as a way to run psudeo multi-threading for code that is not thread safe. Others, like Chris do "for_exec" and need the option to reliably do so. So, perhaps "for_client" would be least controversial but at least one would have a way to get around this problem.

**Comment by simonmichal** [comment] 2021-06-09 06:18
@abh3: few comments from my side:

1. First of all, thanks for pointing out that the poller thread needs to exit when the error condition is detected, this is fixed: cd7856cdf776c668bf51124952bbd3c0ea07f0e0
https://github.com/xrootd/xrootd/blob/cd7856cdf776c668bf51124952bbd3c0ea07f0e0/src/XrdSys/XrdSysIOEventsPollE.icc#L217-L222

2. **There is no way to know if the process is being forked to do an `exec` or no.** Also adding an envar defeats the purpose of the patch, if we want to force the user to play with envars we can simply ask him to disable the fork handler, but this is not the point.

3. What we are trying to fix here is really not a flaw in the fork handler but in the poller, a bottom component should simply not handle errors with an `abort`. Roughly speaking, in case of `forking` for `exec` it really doesn't matter what happens in the new process before the `exec` as long as it is not killing the process ;-)

4. What we need (IMHO) is a way to let the client know that the event loop is not working and that's what the patch does. The overhead of the check is negligible and I wouldn't worry about it.

5. I really would like to avoid handling errors other than `EBADF` with the `abort` as this will make the code incomprehensible.

6. All that said, if I would be 100% sure that the patch is correct I wouldn't ask you for a review ;-) so here's my main concern, let's say the client is running in the context of `XCache` and `epoll_wait` yields an error, the client will start failing all request with fatal error making the cache unusable and in this case, well it would be better to terminate ...

**Comment by simonmichal** [comment] 2021-06-09 14:39
@chrisburr : I think we reached a consensus about how the bug fix should look like: 5ece48c16de3c6c1508fc84eea65d10333020854

Could you give it a try (https://github.com/xrootd/xrootd/tree/issue1198)?

**Comment by simonmichal** [comment] 2021-06-10 08:37
@chrisburr  : so I manage to force the error scenario from gdb and it looks like the bug fix works so I merged 5ece48c16de3c6c1508fc84eea65d10333020854 to master, let me know if I can close this issue?

**Comment by chrisburr** [comment] 2021-06-10 08:51
@simonmichal, apologies for the delay in getting back to you.

I don't have a good way of testing as I've never managed to reproduce this locally, only in complex grid jobs running at a random selection of LHCb grid sites (isolating the issue involved running lots jobs with `strace` until I had enough logs to figure it out).

That said, I think 5ece48c looks like a very nice solution so I think this can be closed.

Thank you very much for figuring this out!

**Comment by simonmichal** [comment] 2021-06-10 08:56
@chrisburr : perfect, and sorry again for such a long delay!

**Closed by simonmichal** 2021-06-10 08:56 UTC
Labels: bug (non-critical)
