### ISSUE TITLE
Cannot copy a file with gfal using the 'xroot' protocol

### ISSUE THREAD

**Issue by ddavila0** [xrootd/xrootd#1366] opened 2020-12-18 05:27 UTC
When I try a gfal-copy to an endpoint using the 'xroot' protocol.

This is what I get from the client:
```
[root@4045db2a8cdd /]# gfal-copy -v file:///tpc_transfers/some_bytes  root://gftp-2.t2.ucsd.edu:1094/store/user/ddavila/some-bytes_997
Copying 3 bytes file:///tpc_transfers/some_bytes => root://gftp-2.t2.ucsd.edu:1094/store/user/ddavila/some-bytes_997
event: [1608268606088] BOTH   GFAL2:CORE:COPY	LIST:ENTER	
event: [1608268606090] BOTH   GFAL2:CORE:COPY	LIST:ITEM	file:///tpc_transfers/some_bytes => root://gftp-2.t2.ucsd.edu:1094/store/user/ddavila/some-bytes_997
event: [1608268606090] BOTH   GFAL2:CORE:COPY	LIST:EXIT	
event: [1608268606090] BOTH   xroot	TRANSFER:ENTER	file://localhost///tpc_transfers/some_bytes?xrd.gsiusrpxy=/tmp/x509up_u0 => root://gftp-2.t2.ucsd.edu:1094///store/user/ddavila/some-bytes_997?xrd.gsiusrpxy=/tmp/x509up_u0
event: [1608268606091] BOTH   xroot	TRANSFER:TYPE	streamed
event: [1608268606233] BOTH   xroot	TRANSFER:EXIT	Job finished, [ERROR] Server responded with an error: [3016] Unable to fchmod /store/user/ddavila/some-bytes_997; is a directory
gfal-copy error: 21 (Is a directory) - Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [3016] Unable to fchmod /store/user/ddavila/some-bytes_997; is a directory
```

On the server side I get this:
```
201217 21:16:45 13915 XrootdXeq: root.222:193@cpe-75-80-56-85.san.res.rr.com pub IPv4 login as ddavila
201217 21:16:46 13915 hdfs_stat: Unable to stat /cms/store/user/ddavila/some-bytes_997; No such file or directory
201217 21:16:46 13915 ofs_stat: root.222:193@cpe-75-80-56-85.san.res.rr.com Unable to locate /store/user/ddavila/some-bytes_997; no such file or directory
201217 21:16:46 13915 root.222:193@cpe-75-80-56-85.san.res.rr.com XrootdResponse: sending err 3011: Unable to locate /store/user/ddavila/some-bytes_997; no such file or directory
201217 21:16:46 13915 hdfs_stat: Unable to stat /cms/store/user/ddavila/some-bytes_997; No such file or directory
201217 21:16:46 13915 ofs_stat: root.222:193@cpe-75-80-56-85.san.res.rr.com Unable to locate /store/user/ddavila/some-bytes_997; no such file or directory
201217 21:16:46 13915 root.222:193@cpe-75-80-56-85.san.res.rr.com XrootdResponse: sending err 3011: Unable to locate /store/user/ddavila/some-bytes_997; no such file or directory
File we will access: /cms/store/user/ddavila/some-bytes_997
201217 21:16:46 13915 ofs_open: root.222:193@cpe-75-80-56-85.san.res.rr.com Unable to fchmod /store/user/ddavila/some-bytes_997; is a directory
hdfsDelete(path=/cms/store/user/ddavila/some-bytes_997, recursive=0): FileSystem#delete error:
RemoteException: Permission denied: user=nobody, access=WRITE, inode="/cms/store/user/ddavila":ddavila:ddavila:drwxr-xr-x
...
<all the haddop exception garbage>
...
201217 21:16:46 13915 hdfs_unlink: Unable to unlink /cms/store/user/ddavila/some-bytes_997; Permission denied
201217 21:16:46 13915 ofs_Del: Unable to remove /store/user/ddavila/some-bytes_997; permission denied
201217 21:16:46 13915 root.222:193@cpe-75-80-56-85.san.res.rr.com XrootdResponse: sending err 3016: Unable to fchmod /store/user/ddavila/some-bytes_997; is a directory
```

XrootD version is: 4.12.6-0.rc1
Gfal2 versions are:
gfal2-util-1.5.3-1.el7.noarch
gfal2-plugin-xrootd-2.18.1-1.1.osg35.el7.x86_64
gfal2-2.18.1-1.1.osg35.el7.x86_64

when I try the same copy with xrdcp it works fine:
```
[root@4045db2a8cdd /]# xrdcp -v  file:///tpc_transfers/some_bytes  root://gftp-2.t2.ucsd.edu:1094//store/user/ddavila/some-bytes_997
[3B/3B][100%][==================================================][3B/s]  
```

**Comment by simonmichal** [comment] 2020-12-19 20:53
@ddavila0 : thanks for reporting the problem. I had a quick look and I was not able to reproduce the problem. I tried with `gfal2-2.18.1`, `gfal2-util-1.5.3` and both xrootd `4.12.6` and master HEAD (both for server and client). Since it works for you with `xrdcp` it seems to me it might be some corner case problem in gfal2.

**Comment by mpatrascoiu** [comment] 2020-12-22 16:00
Hello @ddavila0,

I agree with Michal. Perhaps this is something I can investigate in Gfal2.
However, I'm confused on this part of the server error:
`Permission denied: user=nobody, access=WRITE, inode="/cms/store/user/ddavila":ddavila:ddavila:drwxr-xr-x`

The next actions seem to fail due to the same reason. In this case, I don't trust so much the error message reported to the user. It seems to be just the first one of many.

**Comment by ddavila0** [comment] 2021-01-06 01:30
Thanks @simonmichal and @mpatrascoiu  for looking at this.
I'm starting to think this is related to hdfs and that's why @simonmichal  couldn't reproduce it.

On the other hand, I've noticed another more annoying issue related to this one.
If I try a `gfal-copy` with the `xroot` protocol, as before, followed by a copy of the same file, this time using `xrdcp` and  later on I restart the XRootD server, it won't start again.

The following is shown in the server logs:
```
Init 1 pending create recovered from /var/spool/xrootd/standalone/.ofs/posc.log
hdfsDelete(path=/cms/store/user/ddavila/some-bytes-997, recursive=0): FileSystem#delete error:
RemoteException: Permission denied: user=nobody, access=WRITE, inode="/cms/store/user/ddavila":ddavila:ddavila:drwxr-xr-x

<a lot of hadoop garbage>

210105 17:21:07 6580 hdfs_unlink: Unable to unlink /cms/store/user/ddavila/some-bytes-997; Permission denied
210105 17:21:07 6580 ofs_Config: Unable to unpersist /store/user/ddavila/some-bytes-997; permission denied
------ File system server initialization failed.
210105 17:21:07 6580 XrootdConfig: Unable to load base file system using default
------ xrootd protocol initialization failed.
210105 17:21:07 6580 XrdProtocol: Protocol xroot could not be loaded
------ xrootd standalone@gftp-1.t2.ucsd.edu:1094 initialization failed.
```

**Comment by abh3** [comment] 2021-01-06 01:48
The problem here is that either the ownership of the file changed or some other weird error in HDFS prevents deletion. Since the file was created with the POSC attribute and was not successfully closed it needs to be deleted. If the server ignores this error then there will be a visible file that is likely incomplete. This runs counter to what POSC guarantees to do. So, the server is caught in a no-win situation. The solution here is to find out what it is about that file system that creates this conundrum.

**Comment by abh3** [comment] 2021-01-22 08:11
Where are we on this issue? Can we close this?

**Closed** 2021-02-05 13:15 UTC
