### ISSUE TITLE
XrdClUtils :: RHEL7 build fails "attribute warn_unused_result [-Werror=unused-result]"

### ISSUE THREAD

**Issue by zvada** [xrootd/xrootd#606] opened 2017-10-20 19:56 UTC
Build of `xrootd-4.7.1-rc2` for `RHEL7` platform in koji fails on `declared with attribute warn_unused_result [-Werror=unused-result]` -- a warning that gets turned into an error:

```
/builddir/build/BUILD/xrootd-4.7.1-rc2/src/./XrdCl/XrdClUtils.hh:282:31: error: ignoring return value of 'int setfsuid(__uid_t)', declared with attribute warn_unused_result [-Werror=unused-result]
           setfsuid(pPrevFsUid);
                               ^
[ 53%] /builddir/build/BUILD/xrootd-4.7.1-rc2/src/./XrdCl/XrdClUtils.hh:286:31: error: ignoring return value of 'int setfsgid(__gid_t)', declared with attribute warn_unused_result [-Werror=unused-result]
           setfsgid(pPrevFsGid);
                               ^
```
Bit of googling suggested workaround using cast to `(void)` to ignore it but including such patch doesn't help either and I see same build error:
```
/builddir/build/BUILD/xrootd-4.7.1-rc2/src/./XrdCl/XrdClUtils.hh:282:38: error: ignoring return value of 'int setfsuid(__uid_t)', declared with attribute warn_unused_result [-Werror=unused-result]
           (void) setfsuid(pPrevFsUid);
                                      ^
/builddir/build/BUILD/xrootd-4.7.1-rc2/src/./XrdCl/XrdClUtils.hh:286:38: error: ignoring return value of 'int setfsgid(__gid_t)', declared with attribute warn_unused_result [-Werror=unused-result]
           (void) setfsgid(pPrevFsGid);
                                      ^
```

Full build.log you can find [here](http://koji.chtc.wisc.edu/kojifiles/work/tasks/4179/254179/build.log).

Build for `RHEL6` works just fine.

Thanks,
Marian

**Comment by ljanyst** [comment] 2017-10-20 20:46
Certain distributions of glibc seem to use `__attribute__((warn_unused_result))` more aggressively than others. Function calls declared this way are not voidable. The rationale is here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25509

**Comment by simonmichal** [comment] 2017-10-23 13:08
I cannot reproduce it either (and we build with mock for all slc and fedora platforms, and with koji for slc 6 and 7). Is there anything specific about your koji build?

I wouldn't dwell on it too much, @gbitzes : could you simply add a log message (dump) in the destructor saying that the uid has been changed from x to y?

**Comment by gbitzes** [comment] 2017-10-23 13:59
@simonmichal : Done, I added a commit to the existing pull request.

**Comment by simonmichal** [comment] 2017-10-23 14:02
@zvada : could you try #605 ?

**Comment by zvada** [comment] 2017-10-23 18:47
@simonmichal: which commit try out then? [08d4646](https://github.com/xrootd/xrootd/pull/605/commits/08d4646697e5bde817f0ba0abdff4ae6152fee67) or [cd33790](https://github.com/xrootd/xrootd/pull/605/commits/cd3379096e346f2bc2694f78328d94bee36d88dc)?

**Comment by zvada** [comment] 2017-10-23 18:51
Oh, per your comment about "log message (dump)" to @gbitzes I think this one should be tested [cd33790](https://github.com/xrootd/xrootd/pull/605/commits/cd3379096e346f2bc2694f78328d94bee36d88dc). Or all files updated [here](https://github.com/xrootd/xrootd/pull/605/files) need a test? Going to try out.

**Comment by simonmichal** [comment] 2017-10-23 18:58
@zvada : actually cd3379096e346f2bc2694f78328d94bee36d88dc should fix your build problem, but you will also need 08d4646697e5bde817f0ba0abdff4ae6152fee67 to avoid ugly merge ;-)

**Comment by zvada** [comment] 2017-10-23 19:35
I've put both commits into one patch - see this [gist](https://gist.github.com/zvada/be05d099d250a89fd28e9e58d188a0fc). And, [scratch build](https://koji.chtc.wisc.edu/koji/taskinfo?taskID=254226) for el7 passed now without an error!!!

Thanks,
Marian

**Comment by simonmichal** [comment] 2017-10-24 08:38
Looks good :-)

Can we close this one, as the build failure has been addressed? 

Michal

**Comment by zvada** [comment] 2017-10-24 15:05
Yep, we can close. Do we get rc3 soon or all will go to official release cut soon? We have OSG development freeze on Monday, Oct 30. Would be great we can make non-RC release into the OSG schedule. Is it possible?

**Comment by simonmichal** [comment] 2017-10-24 15:29
If this is the only issue with RC2 (and so far it is) then there's no need for RC3, I already ported those 2 commits to stable-4.7.x, by the end of the week, I'll cut the release.

**Closed by simonmichal** 2017-10-24 15:29 UTC

**Comment by zvada** [comment] 2017-10-24 15:41
We haven't had chance test it fully yet due block by build error but we are installing it now and should confirm whether all is good or not within a couple of days. Thanks!

**Comment by simonmichal** [comment] 2017-10-25 10:23
OK, I'm waiting for a green light from you to do the release ;-)
I suppose we have time until Monday morning, if I do the release on Monday morning this would be enough for you due to the time difference, right?

**Comment by zvada** [comment] 2017-10-27 17:45
Hi @simonmichal,

I believe I can confirm that issues addressed are gone after deploying rc2 in question. We've tested this on our StashCache instances at Nebraska and UChicago and also https+segfault issues for CMS@Florida didn't reappear (yet). :)

Please, do the release!

Thanks,
Marian

**Comment by xrootd-dev** [comment] 2017-10-27 18:19
Hi Marian,

Good to know. We will do a release as soon as possible. Right now we are 
trying to resolve some issues other testors have reported. So, the release 
may be delayed a bit.


Andy

**Comment by zvada** [comment] 2017-10-30 05:17
Hi Andy,

you mentioned in the other email thread you already have bug fix for it. Could this get into testing of yet another RC or are you guys considering make it available in official cut and when if so?

I'd like to see whether we can still push this into OSG release or not within few days. Even there is freeze scheduled for Oct 30th at OSG we could push this back a bit if we know what's your plan -- OSG definitely won't accept RC in the production release, however.

Thanks,
Marian

**Comment by xrootd-dev** [comment] 2017-10-30 06:00
Hi Marian,

Funny, we were just discussing this today. We definitely want to get this 
into 4.7.1 ASAP mostly to allow OSG to package the fixed release. We don't 
know the exact deadline OSG has but are wishfully thinking it won't be 
until midweek (will it -- can it get delayed until then?). We really would 
like to deploy the patch on one of our large scale testbeds (dozens of 
servers doing thousands of transactions) to make sure the fix really fixes 
this (I have high confidence it will). That won't happen until Monday and 
we would need to run at least 8 hours (the problem will actually show up 
within an hour if it's still there). So, that's the story.

Andy

**Comment by simonmichal** [comment] 2017-10-30 10:16
Hi Marian,

I just created RC3, it's under testing now, We'll approximately need 1-2 days to test it. 
So if everything is fine, I could do the release on Wednesday morning (Andy is confident 
about his patch).

Is this OK for you?

Cheers,
Michal

**Comment by zvada** [comment] 2017-10-30 15:48
Yes, that sounds good! I'll ask to make special on-hold in the OSG release process and wait till Wednesday for latest non-RC of xrootd. Crossing fingers that all tests go well. We may also try put RC3 in some of our tests in US, let's see.

Thanks,
Marian

**Comment by zvada** [comment] 2017-11-02 10:56
@abh3, @simonmichal: assuming "XRootD 4.7.1 bugfix release" announced yesterday includes latest patches not previously tested in RC3 we did build from the final tag v4.7.1 for the coming OSG release as well. Just wanted to make sure this was the right course of action and things should be aligned with all recent code changes. Thanks.

**Comment by simonmichal** [comment] 2017-11-02 11:05
@zvada : yes that's the right thing to do :-)
Just for the record, 4.7.1 includes just one patch that was not tested in RC3: 3c78db546b530e4989cc5bab3e8afb10298d0991
(which I tested in my testbed)

**Comment by zvada** [comment] 2017-11-02 11:10
Perfect, that's what I thought. So we have built in OSG as well.
