### ISSUE TITLE
xrootd 4.6.0 xrdcp treats missing CRL as an error

### ISSUE THREAD

**Issue by ellert** [xrootd/xrootd#465] opened 2017-02-14 10:29 UTC
This issue was reported as a comment in the bodhi update system in Fedora:

https://bodhi.fedoraproject.org/updates/FEDORA-2017-0eca8dbb12

When I first investigated this I found the problem with the incompatibility with older servers that I reported in #461 which showed a similar problem, but the original reporter came back and reported that his problem still was there after updating to the version fixing the older server incompatibility.

I tried to issue the exact same command that was used by the reporter, and it succeeded without problems for me. So I asked for more information.

The detailed logs that were provided showed that on the users system the CRL files for the CA signing the server's certificate ware not present. And if I move these CRL files away on my system I can reproduce the problem.

An absent CRL file should not cause an error. The CRL file being absent means "do not check". If the CRL file is there it must be valid (i.e. not expired) and those certificates that are revoked in it must not be validated.

The CRL checking code in 4.6.0 treats a missing CRL as an expired CRL, which is not correct. This is a regression form the 4.5.0 version.

The logs from the original reporter attempting the same xrdcp command with 4.5.0 and 4.6.0 installed on the same system are attached.

[xrdcp-4.5.0.txt](https://github.com/xrootd/xrootd/files/773755/xrdcp-4.5.0.txt)
[xrdcp-4.6.0.txt](https://github.com/xrootd/xrootd/files/773754/xrdcp-4.6.0.txt)

**Comment by gganis** [comment] 2017-02-21 09:47
This should be now fixed in the HEAD of master and stable-4.6.x .
Thanks for reporting.

**Closed by gganis** 2017-02-21 09:47 UTC

**Comment by ellert** [comment] 2017-03-04 08:03
This issue has reappeared.

**Comment by gganis** [comment] 2017-03-06 17:54
Should be fixed now. Please confirm. Sorry for the inconvenience.

**Comment by ellert** [comment] 2017-03-06 20:24
The case when the CRL is absent works now. However, a warning appears in the terminal which I think should not be there:
170306 21:21:08 2183 secgsi_GetCA: CRL entry for '70d35895.0:1' needs refreshing: clean the related entry cache first (0x7fd3b002d700)

**Comment by ellert** [comment] 2017-03-09 14:18
Is anyone looking into removing the confusing warning?

**Comment by gganis** [comment] 2017-03-09 16:27
Sorry, I am not able to reproduce it.
What configuration produces this (valid/invalid/missing/expired CRL)?

**Comment by ellert** [comment] 2017-03-09 18:20
With the CRLs (70d35895.r0 and d690e530.r0) present in /etc/grid-security/certificates:

    $ xrdcp -f root://se1.accre.vanderbilt.edu//store/test/xrootd/T2_US_Vanderbilt//store/mc/SAM/GenericTTbar/GEN-SIM-RECO/CMSSW_5_3_1_START53_V5-v1/0013/CE4D66EB-5AAE-E111-96D6-003048D37524.root /dev/null
    [492.2MB/492.2MB][100%][==================================================][12.95MB/s]  

With the CRLs (70d35895.r0 and d690e530.r0) NOT present in /etc/grid-security/certificates:

    $ xrdcp -f root://se1.accre.vanderbilt.edu//store/test/xrootd/T2_US_Vanderbilt//store/mc/SAM/GenericTTbar/GEN-SIM-RECO/CMSSW_5_3_1_START53_V5-v1/0013/CE4D66EB-5AAE-E111-96D6-003048D37524.root /dev/null
    170309 19:16:37 17769 secgsi_GetCA: CRL entry for '70d35895.0:1' needs refreshing: clean the related entry cache first (0x7f128002d570)
    [492.2MB/492.2MB][100%][==================================================][12.62MB/s]
