### ISSUE TITLE
XCache can start with out an Authfile

### ISSUE THREAD

**Issue by efajardo** [xrootd/xrootd#1166] opened 2020-03-26 18:41 UTC
XCache can start without an auth file:
```
Config continuing with file /etc/xrootd/config.d/50-stash-cache-authz.cfg ...
=====> acc.audit deny grant
=====> acc.authdb /run/stash-cache-auth/Authfile
Config continuing with file /etc/xrootd/config.d/50-stash-cache-paths.cfg ...
Config continuing with file /etc/xrootd/config.d/90-stash-cache-disks.cfg ...
Config continuing with file /etc/xrootd/config.d/90-xcache-logging.cfg ...
Config continuing with file /etc/xrootd/config.d/92-disks.cfg ...
Config 2 authorization directives processed in /etc/xrootd/xrootd-stash-cache-auth.cfg
200304 00:04:01 537 acc_AuthFile: Unable to find /run/stash-cache-auth/Authfile; no such file or directory
------ Authorization system initialization failed.
```

However the actual cache starts correctly:

```Config continuing with file /etc/xrootd/config.d/92-disks.cfg ...
=====> http.trace all
 Using TLS 1.2
200304 00:04:01 537 sysConfig: XRDROLE:  server
200304 00:04:01 537 sysConfig: Configured as HTTP(s) data server.
200304 00:04:01 537 sysXrdHttp:  Reset
200304 00:04:01 537 sysXrdHttp:  XrdHttpReq request ended.
------ HTTP protocol initialization completed.
------ xrootd stash-cache-auth@stashcache-ucsd-5fb6d5c964-9xhgv:8443 initialization completed.
```

I am attaching the log
[xrootd_onstart.log](https://github.com/xrootd/xrootd/files/4389201/xrootd_onstart.log)

**Comment by abh3** [comment] 2020-03-31 05:47
Could you post the complete log of all the initialization from start to end. This really shouldn't happen.

**Comment by efajardo** [comment] 2020-03-31 18:41
@abh3 what do you mean I attached the complete log

**Comment by abh3** [comment] 2020-03-31 19:08
The snippet posted only include the logfile from the point of processing 
/etc/xrootd/config.d/50-stash-cache-authz.cfg and I need the log file from 
the moment of startup to he moment *all* of the configuration completes 
and teh message whether the "xrd" component succeeds or fails. So, start 
up the server after a minute send me the complete log.

Andy

**Comment by efajardo** [comment] 2020-03-31 19:17
I posted the snippet and attached the whole log: `xrootd_onstart.log`

**Comment by abh3** [comment] 2020-03-31 19:37
Thanks, it seems there is some strange interaction with continuations but now I have something to go on as I couldn't reproduce it in my simple setup.

**Comment by abh3** [comment] 2020-04-09 18:39
I am closing this as plug-in developer error.

**Closed by abh3** 2020-04-09 18:39 UTC
