### ISSUE TITLE
DNS/IP caching not refreshed in 'XrdSsiService'

### ISSUE THREAD

**Issue by jafonso** [xrootd/xrootd#2289] opened 2024-06-28 13:52 UTC
I'm creating this issue following an in-person discussion with @amadio .

----

### Problem

We have a large number of EOS MGM and FST servers connecting to a CTA Frontend service. \
The service provider is obtained by passing the URL of the CTA Frontend to the `XrdSsiProvider::GetService` function which, according to the XRootD documentation, employs some sort of built-in DNS/IP resolution:
- https://xrootd.slac.stanford.edu/doc/dev50/ssi_reference-V3.htm#_Toc53698230

Unfortunately, it seems that the DNS/IP resolution is never refreshed or timed-out once the service is created... \
This forces us to manually restart the MGM/FST servers every time the IP of the CTA Frontend service changes, despite the URL remaining the same.

----

### Desired behaviour

Ideally, we would like to be able to set a timeout for the built-in DNS cache or, at least, have it refreshed automatically every X seconds.

I have discussed this with @amadio and he mentioned that the fix should probably go here:
- https://github.com/xrootd/xrootd/blob/master/src/XrdSsi/XrdSsiClient.cc#L145

Thanks!

**Comment by amadio** [comment] 2024-06-28 15:31
@abh3 One question that came up was if setting the timeout to the same 300s used elsewhere in the code would work or if due to the special nature of these entries it wouldn't work. If changing the timeout works, I could include a patch for this into 5.7.

**Comment by abh3** [comment] 2024-06-29 00:52
First off, changing maxTMO value in XrdSsiClient.cc will stop SSI from working. That value is used to disable XRootD client timeouts so that connections never timeout which is needed for SSI.

So, recall we discussed this problem and now I have looked at the code again and nothing caches IP addresses. Only names of hosts are cached. Now, we do cache sessions and sessions have an open XRootD client object. However, since we disable connection timeouts, presumably the connection is active when we reuse the XRootD client object and so it all should stull work. If the connection is somehow closed, presumably the XRootD client reresolves the address when re-establishing the connection. Recall, you looked at this and said thathappens in all cases and I said well, LSST is complaining as much as the person here. So, it would appear that there is a case where the address is not re-resolved. Otherwise, I don't see how that would happen in SSI unless someone is passing in an IP address when calling GetService() but that would be the application's failt not SSI's fault. Unless...

There is one possibility that we wind up using an IP address even with the application passed a hostname. In the process of making sure a valid hostname was passed we resolve it and then convert the IP address back to the hostname. This is done to allow non-FQN's to be passed and we want to generate URL's with FQN's. However, if the DSN entry does not have a pointer record (i.e. does not support reverse lookups) then the IP address will be used and surely this will generate the issue described here. So, the first step is to check if CTA can be found via it's IP address. Now, the person here mentioned that CTA's address may change which would imply it's running via Kubernetes, right? If so,  the way they run K8s may disable reverse lookups. There is more about this at https://www.linkedin.com/pulse/reverse-ip-lookup-solution-k8s-services-deepak-kumar/

So, let's find out and then we can come up with a solution is this is the case.

**Comment by amadio** [comment] 2024-06-30 08:31
Hi @abh3, my question was specifically about this timeout:

https://github.com/xrootd/xrootd/blob/619e93fe896f23ac04fd424ac5223c2443fec296/src/XrdSsi/XrdSsiClient.cc#L158

My initial guess (and therefore my question above) was that indeed it was set to not expire for a reason, but there is code to handle it being set. If the IP address is resolved when connecting, and the connection stays alive forever, then the address would never be re-resolved indeed. However, as you describe above, if the `DataServerTTL` timeout could be set to a value of, say 5min, it would allow the connection to be closed and upon reconnection the address would be re-resolved. I think no change in the software is required for this, the user just needs to call `SetTimeout` below in case the default is not suitable for them. However, we may want to consider making the default of this specific timeout shorter than the rest in a future release.

https://github.com/xrootd/xrootd/blob/619e93fe896f23ac04fd424ac5223c2443fec296/src/XrdSsi/XrdSsiClient.cc#L354-L388

**Comment by abh3** [comment] 2024-07-01 01:26
Yoiu really cannot do that. SSI requests in progress will be killed upon the timeout. They are set this way to allow requests to take as long as they want. Please consider what I said. If the conection is alive the IP addrtess cannot change. If the connectopn drops, the address will be re-resolved upon reconnecting. So , thsi is *not* the problem involving timeouts or caching IP addresses as that does not happen. Again, I suspect reverse DNS lookups are not working. One needst o first figure whether that is the case first.

**Comment by amadio** [comment] 2024-07-01 06:03
Ok, I will follow this up with the CTA service managers to check that reverse DNS is working correctly in their setup.

**Comment by abh3** [comment] 2024-07-01 07:17
I think you may need to directly talk to someone who can try a reverse lookup inside the container that SSI is running. That may require developer help. Alternatively, the link that I gave you explains the terminology where reverse lookups work and where reverse lookups are disabled. That may assist you when talking to the service manager.

**Comment by amadio** [comment] 2024-07-01 09:23
CTA doesn't run with containers, they just use a DNS alias to point to their frontend, and they moved this alias to point to a different machine. But I will look at the link to understand how things should work in Kubernetes as well.

**Comment by abh3** [comment] 2024-07-01 10:27
It still could be that the network team did not setup PTR records in the DNS o allow reverse translation. That happens to be the case far more than it used to be. It seems to be an ever increasing problem with network people just ignoring this step. Maybe due to just newbies now.

**Comment by abh3** [comment] 2024-08-01 03:41
I know this is not a critical issue but could you see if reverse IP lookup iworks for the CTA server in question?

**Comment by amadio** [comment] 2024-08-23 15:35
I checked the reverse DNS entries for CTA, and everything should be fine there. Here is an example for `eosctapublic.cern.ch`:

```sh
$ host eosctapublic.cern.ch
eosctapublic.cern.ch has address 128.142.193.99
eosctapublic.cern.ch has IPv6 address 2001:1458:301:27::100:61

$ dig -x 128.142.193.99 | grep PTR
;99.193.142.128.in-addr.arpa.	IN	PTR
99.193.142.128.in-addr.arpa. 900 IN	PTR	eosctafst0203.cern.ch.

$ dig -x 2001:1458:301:27::100:61 | grep PTR
;1.6.0.0.0.0.1.0.0.0.0.0.0.0.0.0.7.2.0.0.1.0.3.0.8.5.4.1.1.0.0.2.ip6.arpa. IN PTR
1.6.0.0.0.0.1.0.0.0.0.0.0.0.0.0.7.2.0.0.1.0.3.0.8.5.4.1.1.0.0.2.ip6.arpa. 900 IN PTR eosctafst0203.cern.ch.
```

In trying to understand the issue, however, I looked into the XrdSsi documentation, and on EOS to see how things are implemented. Here are my findings:

The [XrdSsi documentation](https://xrootd.slac.stanford.edu/doc/dev50/ssi_reference-V3.htm#_Toc53698231) says that one should get a service by calling `GetService()` using an `XrdSsiProvider` object, passing in the contact for that service. However, looking on EOS, this is not what is happening. A service is statically initialized, then never changed, like the links below show:

https://github.com/cern-eos/eos/blob/5.2.24/mgm/WFE.cc#L2797-L2799
https://github.com/cern-eos/eos/blob/5.2.24/fst/XrdFstOfsFile.cc#L3898

Calling `GetService()` will give you an object of the type `XrdSsiServReal` which is very important because that's the object that has the logic to refresh things later on.

https://github.com/xrootd/xrootd/blob/7c51f3a38c5d5e5bde744ca52abf20c51f6856cf/src/XrdSsi/XrdSsiClient.cc#L199-L201

Also, the [documentation](https://xrootd.slac.stanford.edu/doc/dev50/ssi_reference-V3.htm#_Toc53698299) says that, should a request fail, any retry should be marked as such by calling `request->SetRetry(true)` before calling `service->ProcessRequest()` on it again. This is not something that is being done when processing requests on EOS either. I do not see anywhere a call to `request->SetRetry(true)` in either EOS or xrootd-ssi-protobuf-interface. Marking a request as a retry is what will trigger an open with refresh:

https://github.com/xrootd/xrootd/blob/7c51f3a38c5d5e5bde744ca52abf20c51f6856cf/src/XrdSsi/XrdSsiSessReal.cc#L225-L234

Note that `XrdSsiServReal::ProcessRequest` is what calls `XrdSsiSessReal::Provision`:

https://github.com/xrootd/xrootd/blob/7c51f3a38c5d5e5bde744ca52abf20c51f6856cf/src/XrdSsi/XrdSsiServReal.cc#L225-L229

So in the end it seems that there is nothing to be fixed on the XRootD side, the problem is elsewhere. Please use `XrdSsiProvider` to get an `XrdSsiServReal` object, then mark retry requests as such. If after that things still don't work when you switch the alias to a new CTA frontend, then we will investigate further why things don't work.

**Comment by abh3** [comment] 2024-08-23 19:38
Hi Guilherme,

Does it have an ipv4 address and if so does that resolve as well? Just want to cover all the possibilities.

Andy
________________________________

**Comment by amadio** [comment] 2024-08-23 21:52
Hi @abh3, yes, the reverse DNS works. Actually, this is the real one that was changed after an upgrade to Alma9:

```sh
lxplus ~ $ host  ctaproductionfrontend.cern.ch
ctaproductionfrontend.cern.ch has address 188.185.127.193
ctaproductionfrontend.cern.ch has IPv6 address 2001:1458:d00:4a::100:1b2

lxplus ~ $ dig -x 188.185.127.193 | grep PTR
;193.127.185.188.in-addr.arpa.  IN      PTR
193.127.185.188.in-addr.arpa. 632 IN    PTR     ctaproductionfrontend12.cern.ch.
```

**Comment by amadio** [comment] 2024-11-21 16:14
Closing this, as the problem is not actually in XRootD. Please see issue https://its.cern.ch/jira/browse/EOS-6256 and merge requests to [EOS](https://gitlab.cern.ch/dss/eos/-/merge_requests/240) and [xrootd-ss-protobuf-interface](https://gitlab.cern.ch/eos/xrootd-ssi-protobuf-interface/-/merge_requests/9) for the actual fixes to this.

**Closed** 2024-11-21 16:14 UTC
Labels: bug (non-critical)
