### ISSUE TITLE
XRootD 4.12.0 with xrootd-voms fails to load vomslib

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1191] opened 2020-05-08 15:32 UTC
Dear all,

sadly, I only came around trying out 4.12.0 now with the release. 

I encounter failure trying to use the new `xrootd-voms`. Here's what I observe:
```
200508 17:22:50 17233 secgsi_InitOpts: *** ------------------------------------------------------------ ***
200508 17:22:50 17233 secgsi_LoadVOMSFun: Unable to load vomslib plugin /usr/lib64/libXrdSecgsiVOMS-4.so
200508 17:22:50 17233 secgsi_LoadVOMSFun: could not find 'XrdSecgsiVOMSFun()' in /usr/lib64/libXrdSecgsiVOMS-4.so
200508 17:22:50 17233 secgsi_Init: Secgsi: ErrError: VOMS plug-in could not be loaded: /usr/lib64/libXrdSecgsiVOMS-4.so
Secgsi: ErrError: VOMS plug-in could not be loaded: /usr/lib64/libXrdSecgsiVOMS-4.so
=====> sec.protocol /usr/lib64 gsi -dlgpxy:1 -exppxy:=creds -ca:1 -crl:3 -gridmap:/dev/null -cert:/etc/grid-security/hostcert.pem -key:/etc/grid-security/hostkey.pem -certdir:/etc/grid-security/certificates -vomsfun:/usr/lib64/libXrdSecgsiVOMS-4.so -vomsfunparms:certfmt=raw|vos=atlas,ops,dteam,wlcg|grps=/atlas,/ops,/dteam,/wlcg
Config 1 authentication directives processed in /etc/xrootd/xrootd-grid.cfg
------ Authentication system initialization failed.
Config Unable to create security framework via /usr/lib64/libXrdSec.so
200508 17:22:50 17233 XrootdConfig: Unable to load security system.
------ xrootd protocol initialization failed.
200508 17:22:50 17233 XrdProtocol: Protocol xrootd could not be loaded
```

For the migration from the pre-`4.12.0` world, I did:
```
yum remove vomsxrd
yum install xrootd-voms
yum update
```
It seems all is installed as expected, since:
```
# rpm -qa | grep -i xrootd
xrootd-server-libs-4.12.0-1.el7.x86_64
xrootd-client-4.12.0-1.el7.x86_64
xrootd-client-libs-4.12.0-1.el7.x86_64
xrootd-server-4.12.0-1.el7.x86_64
xrootd-4.12.0-1.el7.x86_64
xrootd-voms-4.12.0-1.el7.x86_64
xrootd-libs-4.12.0-1.el7.x86_64
xrootd-selinux-4.12.0-1.el7.noarch
```
Also, the library itself seems fine:
```
# nm -D /usr/lib64/libXrdSecgsiVOMS-4.so  | grep -i VOMS
00000000002092e0 B gsiVOMSTrace
00000000000047a0 T XrdSecgsiVOMSFun
0000000000002bc0 T XrdSecgsiVOMSInit
                 U _ZN8vomsdata12ErrorMessageEv
                 U _ZN8vomsdata8RetrieveEP7x509_stP13stack_st_X50912recurse_type
                 U _ZN8vomsdataC1ESsSs
                 U _ZN8vomsdataD1Ev
```
and furthermore:
```
# ldd /usr/lib64/libXrdSecgsiVOMS-4.so 
        linux-vdso.so.1 =>  (0x00007ffc677a4000)
        libvomsapi.so.1 => /lib64/libvomsapi.so.1 (0x00007f42d9f45000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f42d9c3e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f42d993c000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f42d9726000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f42d9358000)
        libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f42d912e000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f42d8ebc000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f42d8a59000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f42da3b9000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f42d880c000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f42d8523000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f42d831f000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f42d80ec000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f42d7ee8000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f42d7cd2000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f42d7ac2000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f42d78be000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f42d76a4000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f42d7488000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f42d7261000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f42d6fff000)
```

Additionally, I use `voms-2.0.14-1.el7.x86_64` from EPEL, it's a fully updated CentOS 7.8 system. 

Any ideas? Anything obviously wrong in my configuration?

**Comment by olifre** [comment] 2020-05-08 18:55
I've now reduced the config file to a mostly minimum one, and tested on a vanilla CentOS 7.8 node (only installing `xrootd` and `xrootd-voms` and naturally the stuff they pull in):
```
sec.protocol /usr/lib64 gsi -vomsfun:/usr/lib64/libXrdSecgsiVOMS.so -gridmap:/dev/null
xrootd.seclib /usr/lib64/libXrdSec.so
```
It does not matter whether I specify `/usr/lib64/libXrdSecgsiVOMS.so` or `/usr/lib64/libXrdSecgsiVOMS-4.so`, the load error remains.

**Comment by olifre** [comment] 2020-05-08 19:07
Ah, here we go. Running `xrootd` manually with `LD_DEBUG=all` reveals:
```
/usr/lib64/libXrdSecgsiVOMS-4.so: error: symbol lookup error: undefined symbol: _ZN18XrdCryptoX509Chain5BeginEv (fatal)
```
So we miss `XrdCryptoX509Chain::Begin()` somehow.

**Comment by olifre** [comment] 2020-05-08 19:15
Ok, so:
```
LD_PRELOAD=/lib64/libXrdCrypto.so.1
```
"fixes" it. Should this library be loaded via configuration (somehow), or should it be linked against by `/usr/lib64/libXrdSecgsiVOMS-4.so` which requires that symbol?

**Comment by simonmichal** [comment] 2020-05-08 20:27
@olifre : thanks for reporting this problem and for all the input. I'll investigate!

**Comment by xrootd-dev** [comment] 2020-05-08 22:00
Hi Oliver,

It should have been part of the link specifcation and clearly that got 
missed. Also, please do not specify the '-4' it just messes everything up 
going forward. Unless, of course you don't mind continually updating your 
configuration which you will be forced to do as that number changes from 
major release to major release.

**Comment by olifre** [comment] 2020-05-09 00:42
@xrootd-dev Many thanks for confirming! 

> Also, please do not specify the '-4' it just messes everything up going forward.

Many thanks for this information! Actually, our existing configuration does not have the `-4`. It was a futile attempt to see if this was the problem (just from wondering if the error loading the library comes from the log message and the real filename not matching). 
But an `strace` then later on confirmed to me exactly what you said (that specifying the suffix in the configuration is nonsense). 

Cheers and thanks,
Oliver

**Comment by simonmichal** [comment] 2020-05-09 14:46
The problem is in the following line:
https://github.com/xrootd/vomsxrd/blob/1928ee9102b9b2aef76a2629aec8bfcf353eb7dd/src/vomsxrd.cmake#L30
`XROOTD_LIBRARIES` is not set when vomsxrd is being built as part of XRootD framework.

To give you bit of context when vomsxrd is being built as a standalone project it is using the xrootd config module (https://github.com/xrootd/xrootd/blob/master/cmake/XRootDConfig.cmake.in) that sets the variable correctly.

It shall be fixed!

**Comment by simonmichal** [comment] 2020-05-11 11:28
@olifre it should be fixed by: 841d85f96693c0de50f4f7a62ad474deb974d000

could you give it a try? 

(once confirmed, we will cut a small 4.12.1)

**Comment by olifre** [comment] 2020-05-11 14:29
@simonmichal Many thanks! Sorry, took me a while to configure XRootD on a CentOS 8 devel node, but indeed I can confirm the library now links against `libXrdCrypto` and `xrootd` starts up with my minimal config :-).

**Comment by simonmichal** [comment] 2020-05-11 14:30
Thanks for checking :-) I suppose we can close this issue?

**Comment by olifre** [comment] 2020-05-11 14:33
Yes, indeed we can (unless you want to keep it open until the release is done? ). :-)

**Comment by simonmichal** [comment] 2020-05-11 15:02
Thanks (we usually close ticket as soon as they are resolved ;-)

**Closed by simonmichal** 2020-05-11 15:02 UTC
