### ISSUE TITLE
cmake croaks when libcurl has no version

### ISSUE THREAD

**Issue by abh3** [xrootd/xrootd#797] opened 2018-08-09 21:40 UTC
It seems that installing an un-versioned libcurl is far more common that anyone expected. This causes our cmake build to become unusable in the presence of an un-versioned libcurl because it wants to check if a compatible version is installed. This needs to be corrected and it should assume no compatible libcurl exists if the current library does not contain version information (that's the safest bet). The messages are:

***** error: from /home/jgates/stack/stack/miniconda3-4.5.4-10a4fa6/EupsBuildDir/Linux64/xrootd-master-g344ca073bb/build.log:
/usr/bin/cmake: /home/jgates/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/libcurl/7.53.1/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 67%] Building CXX object src/XrdCl/CMakeFiles/XrdCl.dir/XrdClZipArchiveReader.cc.o
/usr/bin/cmake: /home/jgates/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/libcurl/7.53.1/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 67%] Building CXX object src/XrdCl/CMakeFiles/XrdCl.dir/XrdClXCpCtx.cc.o
/usr/bin/cmake: /home/jgates/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/libcurl/7.53.1/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 67%] Building CXX object src/XrdCl/CMakeFiles/XrdCl.dir/XrdClXCpSrc.cc.o
/usr/bin/cmake: /home/jgates/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/libcurl/7.53.1/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 67%] Building CXX object src/XrdCl/CMakeFiles/XrdCl.dir/XrdClLocalFileHandler.cc.o
/usr/bin/cmake: /home/jgates/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/libcurl/7.53.1/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 67%] Building CXX object src/XrdCl/CMakeFiles/XrdCl.dir/XrdClLocalFileTask.cc.o
/usr/bin/cmake: /home/jgates/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/libcurl/7.53.1/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 68%] Linking CXX shared library libXrdCl.so
/usr/bin/cmake: /home/jgates/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/libcurl/7.53.1/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/jgates/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/libcurl/7.53.1/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/jgates/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/libcurl/7.53.1/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/jgates/stack/stack/miniconda3-4.5.4-10a4fa6/Linux64/libcurl/7.53.1/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 68%] Built target XrdCl
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
+ exit -4

**Comment by simonmichal** [comment] 2018-10-31 09:02
Just to truck our email conversation I'll copy paste my findings so far:

I've actually checked and neither:

  - the libcurl.so I have on cc7, 
  - nor the libcurl.so I have on fedora 28 
  - nor the libcurl.so I have on ubuntu xenial

have .gnu.version_d.

I also tried building curl from sources (7.53.1, as advised) and then build xrootd
against it, and it works just fine for me. Cannot reproduce the problem.

Looking a:
https://serverfault.com/questions/696631/libcurl-so-4-no-version-information-available
https://stackoverflow.com/questions/30017397/error-curl-usr-local-lib-libcurl-so-4-no-version-information-available-requ

makes me think you might have installed more than one version of libcurl,
which might cause the problem.

Let me know your thoughts.

Cheers,
Michal

**Comment by abh3** [comment] 2018-10-31 20:37
Frankly, I wouldn't spend more time on this. Obviously, it's a very 
esoteric problem. I'd suggest that should you get a non-versioned libcyrl 
you likely installed the wrong thing or just mmade a plain mistake.

Andy

**Comment by fritzm** [comment] 2019-02-21 05:58
@abh3, @simonmichal:

It seems we finally got to the bottom of this today.  There is an extra `configure` flag that needs to be explicitly passed when building `libcurl` under Ubuntu in order to end up with an appropriate version resource in the library ("`--enable-versioned-symbols`").

Apparently, this option defaults correctly e.g. on Centos, but not on Ubuntu.  We found this by finally reading the official Debian package script for `libcurl` (after noticing that the officially distributed libcurl library _did_ have the correct resource), and noticing the explicit passing of this flag there.

Noted here for future reference, in case anybody else runs into this issue (there seems to be a lot of confusion and poor advice about this out on the web).  Please feel free to close this issue!

thanks much,
--FritzM.

**Comment by simonmichal** [comment] 2019-02-25 15:44
@fritzm : thanks for reporting your findings!

**Closed by simonmichal** 2019-02-25 15:44 UTC
Labels: bug
