### ISSUE TITLE
xrdcp -r with authz token on dest URL fails

### ISSUE THREAD

**Issue by cantrip** [xrootd/xrootd#1755] opened 2022-08-05 17:38 UTC
Hi,

If I use xrdcp -r and the destination URL includes a SciToken on the command line by adding ?authz=TOKENHERE to the URL, I get the error "Multiple sources were given but target is not a directory." If I remove the token and passthrough to another auth, it works. I am guessing that something parsing the URL is expecting a trailing "/" which isn't there with extra attributes on the URL. 

single file copies work just fine with the token appended to the URL. 

This form of copy works (with passthrough to another auth)
`xrdcp -r /srcdir/  xroots://server//destdir/`

this fails:
`xrdcp -r /srcdir/  xroots://server//destdir/?authz=Bearer%20TOKENHERE`

Maybe there’s a better way to get the SciToken into the client environment that I do not know, e.g. $BEARER_TOKEN or something so that it’s not in the URL?

Thanks for any pointers. 

--Bryan

**Comment by cantrip** [comment] 2022-08-16 17:02
I have worked around this by enabling ztn, so this is probably unimportant.

**Comment by dcervenkov** [comment] 2022-09-30 14:56
I've also run into this issue. I did a little digging, and I think what is happening is the following:
- If there are multiple files to be copied, `xrdcp` checks if the destination is a directory
- The token is not used during this check, leading to the following debug message:
```
[3010] Unable to give access - user access restricted - unauthorized identity used ; Permission denied
```
- Failing to do the check, the destination is not marked as `isDir`
- `xrdcp` return the following error message:
```
Multiple sources were given but target is not a directory.
```

**Comment by simonmichal** [comment] 2022-10-07 09:21
@cantrip : thank you for reporting this problem! do you maybe have an endpoint that I could use to reproduce this problem?

**Comment by simonmichal** [comment] 2022-10-10 11:58
@cantrip & @dcervenkov : the problem should be fixed in fdfe7ef58874cbe32e4357ffe05a7d2d002c7bda, could you please give it a try?

**Comment by dcervenkov** [comment] 2022-10-11 08:36
@simonmichal, I can confirm that explicitly copying multiple files works with https://github.com/xrootd/xrootd/commit/fdfe7ef58874cbe32e4357ffe05a7d2d002c7bda.

However, I'm observing strange behavior when using recursive copy `xrdcp -r`. The files are created at the destination, but their contents are not copied (they have size 0). First, the following messages are printed for each file
```
Job: 1/193
Source: file://localhost/home/cervenkov/bin/xrootd/include/xrootd/XrdVersion.hh
Target: root://eoslhcb.cern.ch:1094//eos/lhcb/user/d/dcervenk/PID_sweight_test/testdir/XrdVersion.hh?authz=[redacted]&xrd.wantprot=unix/include/xrootd
[0B/0B][100%][==================================================][0B/s]
```
Then again for each file
```
Job #1: [ERROR] Server responded with an error: [3018] Unable to create file (O_EXCL) /eos/lhcb/user/d/dcervenk/PID_sweight_test/testdir/XrdVersion.hh; File exists (destination)
```

**Comment by simonmichal** [comment] 2022-10-11 09:12
@dcervenkov : could you try copying with '-f' option?

**Comment by simonmichal** [comment] 2022-10-11 12:18
@dcervenkov : thanks for trying? Could you run with `-d 3` this will enable verbose logging, and post the logs here?

**Comment by dcervenkov** [comment] 2022-10-11 12:47
The log is [here](https://cernbox.cern.ch/index.php/s/rzE4XVMKL7Qs9Se). I hope I sanitized it sufficiently; let me know if there are still some secrets left.

**Comment by simonmichal** [comment] 2022-10-11 13:42
@dcervenkov : thanks for the logs. The copy fails because the client cannot authenticate against the data server:

```
[2022-10-11 13:28:56.222309 +0100][Debug  ][XRootDTransport   ] [st-096-hh151b28.cern.ch:1095.0] Authentication is required: &P=unix&P=sss,0.+13:/etc/eos.keytab
[2022-10-11 13:28:56.222316 +0100][Debug  ][XRootDTransport   ] [st-096-hh151b28.cern.ch:1095.0] Sending authentication data
[2022-10-11 13:28:56.222341 +0100][Error  ][XRootDTransport   ] [st-096-hh151b28.cern.ch:1095.0] No protocols left to try
[2022-10-11 13:28:56.222368 +0100][Error  ][AsyncSock         ] [st-096-hh151b28.cern.ch:1095.0] Socket error while handshaking: [FATAL] Auth failed
[2022-10-11 13:28:56.222378 +0100][Debug  ][AsyncSock         ] [st-096-hh151b28.cern.ch:1095.0] Closing the socket
[2022-10-11 13:28:56.222389 +0100][Debug  ][Poller            ] <[::ffff:163.1.136.219]:43140><--><[::ffff:128.142.128.193]:1095> Removing socket from the poller
[2022-10-11 13:28:56.222427 +0100][Error  ][PostMaster        ] [st-096-hh151b28.cern.ch:1095] elapsed = 0, pConnectionWindow = 120 seconds.
[2022-10-11 13:28:56.222439 +0100][Error  ][PostMaster        ] [st-096-hh151b28.cern.ch:1095] Unable to recover: [FATAL] Auth failed.
```

The client tries different locations hence the redirection limit error. I have to investigate bit more to figure out what is the root-cause of the authentication failure.

**Comment by dcervenkov** [comment] 2022-10-11 13:47
Sure, thanks for looking into this.

**Comment by simonmichal** [comment] 2022-10-12 09:48
@cantrip : are you enforcing specific authentication method on the client side by setting either the `XrdSecPROTOCOL` envar or specifying the `xrd.wantprot` cgi element in the URL?

The problem is the server asks for authentication either with `sss` or `unix`
```
[2022-10-11 13:28:56.222309 +0100][Debug  ][XRootDTransport   ] [st-096-hh151b28.cern.ch:1095.0] Authentication is required: &P=unix&P=sss,0.+13:/etc/eos.keytab
```

and the client is not trying any of those because we don't see`Trying to authenticate using unix` in the logs. The `unix` authentication is always possible (without any special credential), which makes me think there's a client side setting that prevents the client to go ahead with the `unix` authentication.

**Comment by simonmichal** [comment] 2022-10-20 14:25
@cantrip : is this still an issue? do you have any feedback regarding your client side settings?

**Comment by cantrip** [comment] 2022-11-10 13:55
I can confirm that `xrdcp -r`  for correctly for us with 5.5.0 and 5.5.1 clients.  We have no specific authentication method enforcement on the client. We tested from OSG jobs at a variety of sites writing back to JLab.

Sorry for the late response. I had a lot of configuration changes since I originally opened this issue to sort out. Thank you for for the fix!

**Comment by dcervenkov** [comment] 2022-11-10 15:14
@cantrip, I've just tried `xrdcp -r` with the newest master (`399392cea`) and it still fails with the `[FATAL] Redirect limit has been reached`. Should I open a new issue or can we try to solve it here?

**Comment by cantrip** [comment] 2022-11-10 17:26
We can work on it here; sorry, didn't mean to close it out!

**Comment by dcervenkov** [comment] 2022-11-11 12:29
OK, thanks. Let me know if you need any more info.

**Comment by simonmichal** [comment] 2023-01-18 16:29
> I can confirm that xrdcp -r for correctly for us with 5.5.0 and 5.5.1 clients. We have no specific authentication method enforcement on the client. We tested from OSG jobs at a variety of sites writing back to JLab.
> 
> Sorry for the late response. I had a lot of configuration changes since I originally opened this issue to sort out. Thank you for for the fix!

@cantrip : could you please try it also with `master`?

**Comment by abh3** [comment] 2023-01-30 10:42
Has this been fixed at this poit?

**Comment by simonmichal** [comment] 2023-02-13 10:16
As there's no feedback, I'll close this one for now (if it turns out the problem is still there please reopen).

**Closed by simonmichal** 2023-02-13 10:16 UTC
Labels: bug (critical)
