### ISSUE TITLE
Should xrdcp try IPv4 connection if IPv6 connection failed?

### ISSUE THREAD

**Issue by akurov** [xrootd/xrootd#625] opened 2017-11-15 10:50 UTC
Hi,

xrdcp don't try to connect via IPv4 if IPv6 connection fails:

$ xrdcp -f -d2 root://xrootd-cms-redir-01.cr.cnaf.infn.it//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root /dev/null
[2017-11-15 12:37:49.181283 +0200][Debug  ][Utility           ] CopyProcess: 2 jobs to prepare
[2017-11-15 12:37:49.181433 +0200][Debug  ][Utility           ] Creating a classic copy job, from root://xrootd-cms-redir-01.cr.cnaf.infn.it:1094//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root to file:///dev/null
[2017-11-15 12:37:49.181473 +0200][Debug  ][Utility           ] Monitor library name not set. No monitoring
[2017-11-15 12:37:49.181534 +0200][Debug  ][Utility           ] Opening root://xrootd-cms-redir-01.cr.cnaf.infn.it:1094//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root for reading
[2017-11-15 12:37:49.181607 +0200][Debug  ][File              ] [0x27c18ff0@root://xrootd-cms-redir-01.cr.cnaf.infn.it:1094//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root] Sending an open command
[2017-11-15 12:37:49.181648 +0200][Debug  ][Poller            ] Available pollers: built-in
[2017-11-15 12:37:49.181667 +0200][Debug  ][Poller            ] Attempting to create a poller according to preference: built-in
[2017-11-15 12:37:49.181684 +0200][Debug  ][Poller            ] Creating poller: built-in
[2017-11-15 12:37:49.181701 +0200][Debug  ][Poller            ] Creating and starting the built-in poller...
[2017-11-15 12:37:49.181846 +0200][Debug  ][Poller            ] Using 1 poller threads
[2017-11-15 12:37:49.181867 +0200][Debug  ][TaskMgr           ] Starting the task manager...
[2017-11-15 12:37:49.181917 +0200][Debug  ][TaskMgr           ] Task manager started
[2017-11-15 12:37:49.181936 +0200][Debug  ][JobMgr            ] Starting the job manager...
[2017-11-15 12:37:49.182048 +0200][Debug  ][JobMgr            ] Job manager started, 3 workers
[2017-11-15 12:37:49.182069 +0200][Debug  ][TaskMgr           ] Registering task: "FileTimer task" to be run at: [2017-11-15 12:37:49 +0200]
[2017-11-15 12:37:49.182105 +0200][Debug  ][PostMaster        ] Creating new channel to: xrootd-cms-redir-01.cr.cnaf.infn.it:1094 1 stream(s)
[2017-11-15 12:37:49.182134 +0200][Debug  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0] Stream parameters: Network Stack: IPAuto, Connection Window: 120, ConnectionRetry: 5, Stream Error Widnow: 1800
[2017-11-15 12:37:49.182258 +0200][Debug  ][TaskMgr           ] Registering task: "TickGeneratorTask for: xrootd-cms-redir-01.cr.cnaf.infn.it:1094" to be run at: [2017-11-15 12:38:04 +0200]
[2017-11-15 12:37:49.183239 +0200][Debug  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094] Found 2 address(es): [2001:760:4205:216::11]:1094, [::ffff:131.154.216.11]:1094
[2017-11-15 12:37:49.183299 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Attempting connection to [2001:760:4205:216::11]:1094
[2017-11-15 12:37:49.183353 +0200][Debug  ][Poller            ] Adding socket 0x27c18d90 to the poller
[2017-11-15 12:39:59.382636 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Async connection call returned
[2017-11-15 12:39:59.382713 +0200][Error  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Unable to connect: Connection timed out
[2017-11-15 12:39:59.382727 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Closing the socket
[2017-11-15 12:39:59.382741 +0200][Debug  ][Poller            ] <x><--><x> Removing socket from the poller
[2017-11-15 12:39:59.383409 +0200][Debug  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094] Found 2 address(es): [2001:760:4205:216::11]:1094, [::ffff:131.154.216.11]:1094
[2017-11-15 12:39:59.383450 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Attempting connection to [2001:760:4205:216::11]:1094
[2017-11-15 12:39:59.383500 +0200][Debug  ][Poller            ] Adding socket 0x27c18d90 to the poller
[2017-11-15 12:42:10.454612 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Async connection call returned
[2017-11-15 12:42:10.454686 +0200][Error  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Unable to connect: Connection timed out
[2017-11-15 12:42:10.454698 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Closing the socket
[2017-11-15 12:42:10.454713 +0200][Debug  ][Poller            ] <x><--><x> Removing socket from the poller
[2017-11-15 12:42:10.455409 +0200][Debug  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094] Found 2 address(es): [2001:760:4205:216::11]:1094, [::ffff:131.154.216.11]:1094
[2017-11-15 12:42:10.455450 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Attempting connection to [2001:760:4205:216::11]:1094
[2017-11-15 12:42:10.455501 +0200][Debug  ][Poller            ] Adding socket 0x27c18d90 to the poller
[2017-11-15 12:44:21.526595 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Async connection call returned
[2017-11-15 12:44:21.526669 +0200][Error  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Unable to connect: Connection timed out
[2017-11-15 12:44:21.526682 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Closing the socket
[2017-11-15 12:44:21.526697 +0200][Debug  ][Poller            ] <x><--><x> Removing socket from the poller
[2017-11-15 12:44:21.527422 +0200][Debug  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094] Found 2 address(es): [2001:760:4205:216::11]:1094, [::ffff:131.154.216.11]:1094
[2017-11-15 12:44:21.527464 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Attempting connection to [2001:760:4205:216::11]:1094
[2017-11-15 12:44:21.527517 +0200][Debug  ][Poller            ] Adding socket 0x27c18d90 to the poller
[2017-11-15 12:46:32.598585 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Async connection call returned
[2017-11-15 12:46:32.598652 +0200][Error  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Unable to connect: Connection timed out
[2017-11-15 12:46:32.598665 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Closing the socket
[2017-11-15 12:46:32.598680 +0200][Debug  ][Poller            ] <x><--><x> Removing socket from the poller
[2017-11-15 12:46:32.599344 +0200][Debug  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094] Found 2 address(es): [2001:760:4205:216::11]:1094, [::ffff:131.154.216.11]:1094
[2017-11-15 12:46:32.599384 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Attempting connection to [2001:760:4205:216::11]:1094
[2017-11-15 12:46:32.599435 +0200][Debug  ][Poller            ] Adding socket 0x27c18d90 to the poller
[2017-11-15 12:48:43.670588 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Async connection call returned
[2017-11-15 12:48:43.670657 +0200][Error  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Unable to connect: Connection timed out
[2017-11-15 12:48:43.670669 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Closing the socket
[2017-11-15 12:48:43.670684 +0200][Debug  ][Poller            ] <x><--><x> Removing socket from the poller
[2017-11-15 12:48:43.670741 +0200][Error  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0] Unable to recover: [ERROR] Connection error.
[2017-11-15 12:48:43.670756 +0200][Error  ][XRootD            ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094] Impossible to send message kXR_open (file: /store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root, mode: 00, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
[2017-11-15 12:48:43.670773 +0200][Debug  ][XRootD            ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094] Handling error while processing kXR_open (file: /store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root, mode: 00, flags: kXR_open_read kXR_async kXR_retstat ): [FATAL] Connection error.
[2017-11-15 12:48:43.670892 +0200][Debug  ][File              ] [0x27c18ff0@root://xrootd-cms-redir-01.cr.cnaf.infn.it:1094//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root] Open has returned with status [FATAL] Connection error
[2017-11-15 12:48:43.670913 +0200][Debug  ][File              ] [0x27c18ff0@root://xrootd-cms-redir-01.cr.cnaf.infn.it:1094//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root] Error while opening at xrootd-cms-redir-01.cr.cnaf.infn.it:1094: [FATAL] Connection error
[0B/0B][100%][==================================================][0B/s]  
Run: [FATAL] Connection error
[2017-11-15 12:48:43.671128 +0200][Debug  ][JobMgr            ] Stopping the job manager...
[2017-11-15 12:48:43.671530 +0200][Debug  ][JobMgr            ] Job manager stopped
[2017-11-15 12:48:43.671567 +0200][Debug  ][TaskMgr           ] Stopping the task manager...
[2017-11-15 12:48:43.671674 +0200][Debug  ][TaskMgr           ] Task manager stopped
[2017-11-15 12:48:43.671692 +0200][Debug  ][Poller            ] Stopping the poller...
[2017-11-15 12:48:43.671766 +0200][Debug  ][TaskMgr           ] Requesting unregistration of: "TickGeneratorTask for: xrootd-cms-redir-01.cr.cnaf.infn.it:1094"
[2017-11-15 12:48:43.671789 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Closing the socket
[2017-11-15 12:48:43.671810 +0200][Debug  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0] Destroying stream
[2017-11-15 12:48:43.671827 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Closing the socket

In IPv4-only mode connection is possible:

$ XRD_NETWORKSTACK=IPv4 xrdcp -f -d2 root://xrootd-cms-redir-01.cr.cnaf.infn.it//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root /dev/null
[2017-11-15 12:38:23.513276 +0200][Debug  ][Utility           ] CopyProcess: 2 jobs to prepare
[2017-11-15 12:38:23.513425 +0200][Debug  ][Utility           ] Creating a classic copy job, from root://xrootd-cms-redir-01.cr.cnaf.infn.it:1094//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root to file:///dev/null
[2017-11-15 12:38:23.513456 +0200][Debug  ][Utility           ] Monitor library name not set. No monitoring
[2017-11-15 12:38:23.513520 +0200][Debug  ][Utility           ] Opening root://xrootd-cms-redir-01.cr.cnaf.infn.it:1094//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root for reading
[2017-11-15 12:38:23.513588 +0200][Debug  ][File              ] [0x17e21ff0@root://xrootd-cms-redir-01.cr.cnaf.infn.it:1094//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root] Sending an open command
[2017-11-15 12:38:23.513630 +0200][Debug  ][Poller            ] Available pollers: built-in
[2017-11-15 12:38:23.513649 +0200][Debug  ][Poller            ] Attempting to create a poller according to preference: built-in
[2017-11-15 12:38:23.513665 +0200][Debug  ][Poller            ] Creating poller: built-in
[2017-11-15 12:38:23.513683 +0200][Debug  ][Poller            ] Creating and starting the built-in poller...
[2017-11-15 12:38:23.513825 +0200][Debug  ][Poller            ] Using 1 poller threads
[2017-11-15 12:38:23.513846 +0200][Debug  ][TaskMgr           ] Starting the task manager...
[2017-11-15 12:38:23.513897 +0200][Debug  ][TaskMgr           ] Task manager started
[2017-11-15 12:38:23.513915 +0200][Debug  ][JobMgr            ] Starting the job manager...
[2017-11-15 12:38:23.514024 +0200][Debug  ][JobMgr            ] Job manager started, 3 workers
[2017-11-15 12:38:23.514045 +0200][Debug  ][TaskMgr           ] Registering task: "FileTimer task" to be run at: [2017-11-15 12:38:23 +0200]
[2017-11-15 12:38:23.514080 +0200][Debug  ][PostMaster        ] Creating new channel to: xrootd-cms-redir-01.cr.cnaf.infn.it:1094 1 stream(s)
[2017-11-15 12:38:23.514110 +0200][Debug  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0] Stream parameters: Network Stack: IPv4, Connection Window: 120, ConnectionRetry: 5, Stream Error Widnow: 1800
[2017-11-15 12:38:23.514236 +0200][Debug  ][TaskMgr           ] Registering task: "TickGeneratorTask for: xrootd-cms-redir-01.cr.cnaf.infn.it:1094" to be run at: [2017-11-15 12:38:38 +0200]
[2017-11-15 12:38:23.515000 +0200][Debug  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094] Found 1 address(es): [::ffff:131.154.216.11]:1094
[2017-11-15 12:38:23.515053 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Attempting connection to [::ffff:131.154.216.11]:1094
[2017-11-15 12:38:23.515113 +0200][Debug  ][Poller            ] Adding socket 0x17e21d90 to the poller
[2017-11-15 12:38:23.587247 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Async connection call returned
[2017-11-15 12:38:23.587336 +0200][Debug  ][XRootDTransport   ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Sending out the initial hand shake + kXR_protocol
[2017-11-15 12:38:23.659449 +0200][Debug  ][XRootDTransport   ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Got the server hand shake response (type: manager [], protocol version 310)
[2017-11-15 12:38:23.659520 +0200][Debug  ][XRootDTransport   ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] kXR_protocol successful (type: manager [], protocol version 310)

Should xrdcp try IPv4 connection if IPv6 connection failed?

Client version: xrootd-client-4.7.1-1.fc27.x86_64

**Comment by simonmichal** [comment] 2017-11-17 15:45
@akurov : yes xrdcp should try ipv4 if a connection with ipv6 failed, however if the time elapsed while trying to connect with ipv6 exceeds the connection window then xrdcp gives up and the retry mechanism kicks in.

Could you try to use a bigger connection window? For testing you could try something like: 
export XRD_CONNECTIONWINDOW=600

Thanks,
Michal

**Comment by akurov** [comment] 2017-11-17 16:08
With XRD_CONNECTIONWINDOW=600 xrdcp tries IPv4 connection, but without this option fails on IPv6 attempts.

$ XRD_CONNECTIONWINDOW=600 xrdcp -f -d2 root://xrootd-cms-redir-01.cr.cnaf.infn.it//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root /dev/null
[2017-11-17 18:00:51.033805 +0200][Debug  ][Utility           ] CopyProcess: 2 jobs to prepare
[2017-11-17 18:00:51.034279 +0200][Debug  ][Utility           ] Creating a classic copy job, from root://xrootd-cms-redir-01.cr.cnaf.infn.it:1094//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root to file:///dev/null
[2017-11-17 18:00:51.034523 +0200][Debug  ][Utility           ] Monitor library name not set. No monitoring
[2017-11-17 18:00:51.034771 +0200][Debug  ][Utility           ] Opening root://xrootd-cms-redir-01.cr.cnaf.infn.it:1094//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root for reading
[2017-11-17 18:00:51.035023 +0200][Debug  ][File              ] [0xa2e0bff0@root://xrootd-cms-redir-01.cr.cnaf.infn.it:1094//store/test/xrootd/CMSSAM/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_0_0_90X_mcRun1_realistic_v4-v1/10000/28B9D1FB-8B31-E711-AA4E-0025905B85B2.root] Sending an open command
[2017-11-17 18:00:51.035526 +0200][Debug  ][Poller            ] Available pollers: built-in
[2017-11-17 18:00:51.035691 +0200][Debug  ][Poller            ] Attempting to create a poller according to preference: built-in
[2017-11-17 18:00:51.035840 +0200][Debug  ][Poller            ] Creating poller: built-in
[2017-11-17 18:00:51.035918 +0200][Debug  ][Poller            ] Creating and starting the built-in poller...
[2017-11-17 18:00:51.036192 +0200][Debug  ][Poller            ] Using 1 poller threads
[2017-11-17 18:00:51.036382 +0200][Debug  ][TaskMgr           ] Starting the task manager...
[2017-11-17 18:00:51.036449 +0200][Debug  ][TaskMgr           ] Task manager started
[2017-11-17 18:00:51.036625 +0200][Debug  ][JobMgr            ] Starting the job manager...
[2017-11-17 18:00:51.036741 +0200][Debug  ][JobMgr            ] Job manager started, 3 workers
[2017-11-17 18:00:51.036889 +0200][Debug  ][TaskMgr           ] Registering task: "FileTimer task" to be run at: [2017-11-17 18:00:51 +0200]
[2017-11-17 18:00:51.036944 +0200][Debug  ][PostMaster        ] Creating new channel to: xrootd-cms-redir-01.cr.cnaf.infn.it:1094 1 stream(s)
[2017-11-17 18:00:51.036979 +0200][Debug  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0] Stream parameters: Network Stack: IPAuto, Connection Window: 600, ConnectionRetry: 5, Stream Error Widnow: 1800
[2017-11-17 18:00:51.037342 +0200][Debug  ][TaskMgr           ] Registering task: "TickGeneratorTask for: xrootd-cms-redir-01.cr.cnaf.infn.it:1094" to be run at: [2017-11-17 18:01:06 +0200]
[2017-11-17 18:00:51.043067 +0200][Debug  ][PostMaster        ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094] Found 2 address(es): [2001:760:4205:216::11]:1094, [::ffff:131.154.216.11]:1094
[2017-11-17 18:00:51.043160 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Attempting connection to [2001:760:4205:216::11]:1094
[2017-11-17 18:00:51.043227 +0200][Debug  ][Poller            ] Adding socket 0xa2e0bd90 to the poller
[2017-11-17 18:02:59.606669 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Async connection call returned
[2017-11-17 18:02:59.606763 +0200][Error  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Unable to connect: Connection timed out
[2017-11-17 18:02:59.606784 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Closing the socket
[2017-11-17 18:02:59.606806 +0200][Debug  ][Poller            ] <x><--><x> Removing socket from the poller
[2017-11-17 18:02:59.606902 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Attempting connection to [::ffff:131.154.216.11]:1094
[2017-11-17 18:02:59.607000 +0200][Debug  ][Poller            ] Adding socket 0xa2e0bd90 to the poller
[2017-11-17 18:02:59.678993 +0200][Debug  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Async connection call returned
[2017-11-17 18:02:59.679093 +0200][Debug  ][XRootDTransport   ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Sending out the initial hand shake + kXR_protocol
[2017-11-17 18:02:59.750959 +0200][Debug  ][XRootDTransport   ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Got the server hand shake response (type: manager [], protocol version 310)
[2017-11-17 18:02:59.751049 +0200][Debug  ][XRootDTransport   ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] kXR_protocol successful (type: manager [], protocol version 310)

Should this option be added every time?

**Comment by simonmichal** [comment] 2017-11-20 16:46
@akurov : for now you will have to set the envar, a fix will be included in the next release.

**Closed** 2017-11-20 16:52 UTC

**Comment by ljanyst** [comment] 2017-11-21 07:36
I would be extremely weary of changing this. What you see here is not a legitimate usecase but rather a server misconfiguration. If a server has both IPv4 and IPv6 addresses and serves only on IPv4, the admin should configure the firewall to send a proper ICMP response instead of swallowing TCP packets.

**Comment by akurov** [comment] 2017-11-21 09:06
Always possible IPv6 network connectivity problems which can't be handled on server side, in such cases IPv4 should be used.

**Comment by ljanyst** [comment] 2017-11-21 09:23
From my experience, the routers would typically handle this by sending ICMP "Destination unreachable" response or something similar. It's very likely, that, with this patch, Michal is breaking more things than he is fixing. I would not make this change lightly. That's all I am saying.

**Comment by ljanyst** [comment] 2017-11-21 09:24
If you get an ICMP response, the failure is almost immediate and the client has enough time to retry another address.

**Comment by abh3** [comment] 2017-11-21 21:59
While I do appreciate your concern, the idea is to have as a robust system as possible regardless of what the problem is. That means (among other things), we want to bypass problems to the extent we can. As it sits, we can’t. I agree, it’s totally a configuration problem in DNS, server, or both. I have seen this before. That doesn’t mean we should tolerate getting the client stuck when a working  alternative exists. Sure, that likely means the admin won’t be aware of the problem until they actually look and wonder why no one is using IPv6 (I’ve seen that one before as well). I don’t believe we should put users through agony to force them to complain to the site admin when we can get around the problem. Hence, the patch.

Andy

**Comment by ljanyst** [comment] 2017-11-21 22:02
I agree with that. I just wanted to say that people likely depend on it being this way.
