### ISSUE TITLE
Issue compiling XRootD using aliBuild

### ISSUE THREAD

**Issue by bhofman** [xrootd/xrootd#1451] opened 2021-05-03 11:28 UTC
Hi erveyone, 

I am not sure this is the right place to ask but I am having issues compiling XRootD. I am trying to build XRootD using aliBuild.

The issue seems to be python related. I have both python and python3 installed (versions 2.7.18 and 3.9.4) I am running Ubuntu 21.04 (hirsute).

The resulting log I attached: 

[log.txt](https://github.com/xrootd/xrootd/files/6414511/log.txt)

Does anyone have a idea about what might cause the issue?

Thanks,
Bas

**Comment by simonmichal** [comment] 2021-05-03 12:35
@bhofman : thanks for reporting the problem, could you give us a recipe for reproducing the problem with a docker container?

**Comment by adriansev** [comment] 2021-05-03 17:54
@simonmichal Hi!
I suspect that the reason is the new gcc of ubuntu2104 .. for fedora there was a patch named:
[XrdPosix] Fix _STAT_VER problem on Fedora rawhide.
5298c732c
Mon Nov 2 09:47:25 2020 +0100 

but that was done long after v4.11.1 was released ... first tag it that has it seem to be 4.12.8
did i get it right?

**Comment by abh3** [comment] 2021-05-03 21:37
Well, the use of _STAT_VER which triggers the error
"error: '_STAT_VER' was not declared in this scope"
is gaurded by

#if defined(__linux__) and defined(_STAT_VER)

So, either your version of xrootd does not have that line (it was 
introduced some time ago when Linux stopped using this convention). I 
can't see any other explanation because if the symbol is defined and your 
compiling for Linux, the error should not appear. Weird.

The Python warnings indicate that the version of Python is far newer than 
what we normally compile with. Could you cut a ticket on that and include 
the log with the "deprecated" warnings in the ticket?

Andy

**Comment by abh3** [comment] 2021-07-29 04:16
So, have we resolved this?

**Comment by simonmichal** [comment] 2021-09-02 08:09
My understanding is that the problem with `_STAT_VER` has been fixed here 5298c732c394d7ac3c24abc7d01a4631f573e692 and as the XRootD4 reached its EOL I'm closing this one (feel free to reopen if the problem reappears).

**Closed by simonmichal** 2021-09-02 08:09 UTC
