### ISSUE TITLE
Client is unable to recover after socket error

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#529] opened 2017-06-11 17:03 UTC
New to 4.6.1, the client is no longer able recover after a socket error occurs.  For an example of this, see the GGUS ticket referenced in #528.

It seems that this one is a bit more urgent, however: a variety of relatively-normal things can trigger a socket error (not necessarily a client problem as in #528 but day-to-day server failures and network hiccups).

The symptoms are as follows:
1.  Socket error occurs when talking to a data server.
2.  CMSSW performs a retry at the redirector.
3.  A timeout occurs on the file open.
4.  Callback is cleanly invoked, CMSSW returns a permanent error.

Prior to the 4.6.x upgrade, (3) never occurred.  The xrootd client would be able to cleanly reopen the file and continue on.

*Note*: it occurred to me that around the time of the 4.6.x upgrade, read recovery was disabled in the client (as read recovery is also done in CMSSW).  Is it possible that this is related to code paths that are only used if read recovery is _disabled_?

**Comment by simonmichal** [comment] 2017-06-19 11:07
AFAIK the read recovery has no impact on an open, it only affects stateful operations.

Regarding 3) is this the open sent to the redirector that times out, or the client has been  redirected to a data server and the open request to a new data server timed out? If the timeout happens for an open sent to the redirector, this cannot be recovered. (this logic has been untouched in 4.6.x)

Michal

**Comment by bbockelm** [comment] 2017-06-19 13:20
The timeout happens for an open sent to the redirector.

This most definitely has something to do with the read recovery code paths though -- launching 10 sample jobs with read recovery disabled and 10 with it enabled:
* All jobs with read recovery disabled failed due to timeouts.
* All jobs with read recovery enabled succeeded.

These were running concurrently and there were no other problems with EOS.

(Another interesting fact here is that there are apparently some workflows where EOS has errors for nearly every job :(  )

**Comment by simonmichal** [comment] 2017-06-19 13:48
I misunderstood your original post ;-)

So you are reading from a data server and a socket error kicks in, you disabled the read recovery and instead you are using your own logic in CMSSW, right?

Could you give me a log with what the client is actually doing in CMSSW in order to recover from the socket error? Could you check what is the URL you are using for recovery. Most likely you need to drop all opaque info from the URL.

**Comment by bbockelm** [comment] 2017-06-19 13:52
Can you view the log attached here: https://ggus.eu/index.php?mode=ticket_info&ticket_id=128888?  There's a log file attached there.

Now that we can reproduce relatively reliably (well, the reproducer can take ~8 hours...), I can re-run that job if there is insufficient log output there.

**Comment by simonmichal** [comment] 2017-06-19 14:34
No, I cannot download the attachment.

**Comment by simonmichal** [comment] 2017-07-04 08:53
Can we close this one, as the problem is in the CMSSW recovery mechanism not the client itself ?

**Comment by bbockelm** [comment] 2017-07-07 02:33
Hi Simon,

I don't see any indication it's in the CMSSW recovery mechanism; as far as I can tell, the client is unusable after the errors if read recovery is disabled.

That said, I'm starting to get pulled away to fight other fires within CMS.  If I don't have an update on this ticket within 7 days, feel free to go ahead and close.

Brian

**Comment by simonmichal** [comment] 2017-07-07 07:54
@bbockelm : allow me to disagree about the client being unusable with the recovery turned off ;-)  the best proof that it is possible to implement the recovery correctly is that in the client it works ;-) Most likely the problem is in how you handle opaque info during recovery !

OK, let's wait for 7 days.

Michal

**Closed** 2017-07-14 08:28 UTC
