### ISSUE TITLE
could not instantiate session cipher using cipher public info from server

### ISSUE THREAD

**Issue by chaen** [xrootd/xrootd#2086] opened 2023-09-14 09:39 UTC
We can't seem to be able to talk to CTA anymore.
The error we got was the same as here: https://github.com/xrootd/xrootd/issues/2014

```bash
bash-5.1$ gfal-stat root://eosctalhcb.cern.ch//eos/ctalhcb/archive/grid/lhcb/data/2018/RAW/FULL/LHCb/COLLISION18/217081/217081_0000000983.raw
230914 11:21:52 175503 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
230914 11:21:52 175503 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
gfal-stat error: 52 (Invalid exchange) - Failed to stat file (Invalid exchange)
```

However, for us it happens with any client OS (CC7, RedHat 9). 

Unfortunately, because we silently fallback on another protocol where it does not happen (https), I can't trace the beginning exactly. I would guess that it is when we moved to openss3.

This are the versions we use on the client side 

```
bash-5.1$ gfal-stat --version
gfal2-util version 1.8.0 (gfal2 2.21.3)
        dcap-2.21.3
        file-2.21.3
        gridftp-2.21.3
        http-2.21.3
        sftp-2.21.3
        srm-2.21.3
        xrootd-2.21.3
bash-5.1$ xrdcp --version
v5.5.5
bash-5.1$ openssl version
OpenSSL 3.1.2 1 Aug 2023 (Library: OpenSSL 3.1.2 1 Aug 2023)
```

On the server side, I was told that they use `xrootd-4.12.8`

This is the output with `XrdSecDEBUG=1`

```
sec_Client: protocol request for host eosctalhcb.cern.ch token='&P=krb5,xrootd/eosctalhcb.cern.ch@CERN.CH&P=gsi,v:10400,c:ssl,ca:5168735f.0|4339b4bc.0&P=sss,0.13:/etc/eos_eosctalhcb
.keytab'                                                                                                                                                                             
sec_PM: Skipping krb5 only want gsi,unix                                                                                                                                             
sec_PM: Loaded gsi protocol object from libXrdSecgsi.so                                                                                                                              
Secgsi -------------------------------------------------------------------                                                                                                           
Secgsi Mode: client                                                                                                                                                                  
Secgsi Debug: 1                                                                                                                                                                      
Secgsi CA dir: /etc/grid-security/certificates                                                                                                                                       
Secgsi CA verification level: verifyss                                                                                                                                               
Secgsi CRL dir: /etc/grid-security/certificates
Secgsi CRL extension: .r0
Secgsi CRL check level: try
Secgsi CRL refresh time: 86400
Secgsi Certificate: /home/dirac/.globus/usercert.pem
Secgsi Key: /home/dirac/.globus/userkey.pem
Secgsi Proxy file: /opt/dirac/work/Transformation/TransformationCleaningAgent/.shifterCred 
Secgsi Proxy validity: 12:00
Secgsi Proxy dep length: 0
Secgsi Proxy bits: 512
Secgsi Proxy sign option: 1
Secgsi Proxy delegation option: 0
Secgsi Pure Cert/Key authentication allowed
Secgsi Allowed server names: [*/]<target host name>[/*]
Secgsi Crypto modules: ssl
Secgsi Ciphers: aes-128-cbc:bf-cbc:des-ede3-cbc
Secgsi MDigests: sha1:md5
Secgsi Trusting DNS for hostname checking
Secgsi -------------------------------------------------------------------
sec_PM: Using gsi protocol, args='v:10400,c:ssl,ca:5168735f.0|4339b4bc.0'
230914 11:26:18 29692 cryptossl_X509::CertType: certificate has 10 extensions
230914 11:26:18 29692 secgsi_VerifyCA: Warning: CA certificate not self-signed and integrity not checked: assuming OK (5168735f.0)
230914 11:26:18 29692 cryptossl_X509::CertType: certificate has 10 extensions
230914 11:26:18 29692 cryptossl_X509::CertType: certificate has 2 extensions
230914 11:26:18 29692 cryptossl_X509::CertType: certificate has 4 extensions
230914 11:26:18 29692 cryptossl_X509::CertType: certificate has 3 extensions
230914 11:26:18 29692 cryptossl_X509::CertType: certificate has 2 extensions
230914 11:26:18 29692 cryptossl_X509::CertType: certificate has 12 extensions
230914 11:26:18 29692 cryptossl_X509::CertType: certificate has 10 extensions
230914 11:26:18 29692 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
sec_Client: protocol request for host eosctalhcb.cern.ch token='&P=krb5,xrootd/eosctalhcb.cern.ch@CERN.CH&P=gsi,v:10400,c:ssl,ca:5168735f.0|4339b4bc.0&P=sss,0.13:/etc/eos_eosctalhcb.keytab'
sec_PM: Skipping krb5 only want gsi,unix
sec_PM: Using gsi protocol, args='v:10400,c:ssl,ca:5168735f.0|4339b4bc.0'
230914 11:26:19 29692 cryptossl_X509::CertType: certificate has 10 extensions
230914 11:26:19 29692 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
gfal-stat error: 52 (Invalid exchange) - Failed to stat file (Invalid exchange)
```

Any idea what can be causing this ? 
Thanks a lot !

**Comment by amadio** [comment] 2023-09-14 09:57
Could you please try with XRootD 5.6.x? The fix for #2014 was added in [v5.6.0](https://github.com/xrootd/xrootd/releases/tag/v5.6.0).

**Comment by chaen** [comment] 2023-09-14 20:08
Same I am afraid

```
sec_Client: protocol request for host eosctalhcb.cern.ch token='&P=krb5,xrootd/eosctalhcb.cern.ch@CERN.CH&P=gsi,v:10400,c:ssl,ca:5168735f.0|4339b4bc.0&P=sss,0.13:/etc/eos_eosctalhcb.keytabty.sshd:/sbi%'
sec_PM: Skipping krb5 only want gsi,unix
sec_PM: Loaded gsi protocol object from libXrdSecgsi.so
Secgsi -------------------------------------------------------------------
Secgsi Mode: client
Secgsi Debug: 1
Secgsi CA dir: /etc/grid-security/certificates
Secgsi CA verification level: verifyss
Secgsi CRL dir: /etc/grid-security/certificates
Secgsi CRL extension: .r0
Secgsi CRL check level: try
Secgsi CRL refresh time: 86400
Secgsi Certificate: /afs/cern.ch/user/c/chaen/.globus/usercert.pem
Secgsi Key: /afs/cern.ch/user/c/chaen/.globus/userkey.pem
Secgsi Proxy file: /tmp/x509up_u56212
Secgsi Proxy validity: 12:00
Secgsi Proxy dep length: 0
Secgsi Proxy bits: 512
Secgsi Proxy sign option: 1
Secgsi Proxy delegation option: 0
Secgsi Pure Cert/Key authentication allowed
Secgsi Allowed server names: [*/]<target host name>[/*]
Secgsi Crypto modules: ssl
Secgsi Ciphers: aes-128-cbc:bf-cbc:des-ede3-cbc
Secgsi MDigests: sha256
Secgsi Trusting DNS for hostname checking
Secgsi -------------------------------------------------------------------
sec_PM: Using gsi protocol, args='v:10400,c:ssl,ca:5168735f.0|4339b4bc.0'
230914 22:07:24 565422 cryptossl_X509::CertType: certificate has 10 extensions
230914 22:07:24 565422 secgsi_VerifyCA: Warning: CA certificate not self-signed and integrity not checked: assuming OK (5168735f.0)
230914 22:07:24 565422 cryptossl_X509::CertType: certificate has 10 extensions
230914 22:07:24 565422 cryptossl_X509::CertType: certificate has 4 extensions
230914 22:07:24 565422 cryptossl_X509::CertType: certificate has 3 extensions
230914 22:07:24 565422 cryptossl_X509::CertType: certificate has 12 extensions
230914 22:07:24 565422 cryptossl_X509::CertType: certificate has 10 extensions
230914 22:07:24 565422 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
sec_Client: protocol request for host eosctalhcb.cern.ch token='&P=krb5,xrootd/eosctalhcb.cern.ch@CERN.CH&P=gsi,v:10400,c:ssl,ca:5168735f.0|4339b4bc.0&P=sss,0.13:/etc/eos_eosctalhcb.keytabsbin/nologin%'
sec_PM: Skipping krb5 only want gsi,unix
sec_PM: Using gsi protocol, args='v:10400,c:ssl,ca:5168735f.0|4339b4bc.0'
230914 22:07:24 565423 cryptossl_X509::CertType: certificate has 10 extensions
230914 22:07:24 565423 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
gfal-stat error: 52 (Invalid exchange) - Failed to stat file (Invalid exchange)
```

```
(/tmp/chaen/xroottest) [chaen@lxplus900 ~]$ openssl version
OpenSSL 3.1.2 1 Aug 2023 (Library: OpenSSL 3.1.2 1 Aug 2023)
(/tmp/chaen/xroottest) [chaen@lxplus900 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.2 (Plow)
(/tmp/chaen/xroottest) [chaen@lxplus900 ~]$ xrdcp --version
v5.6.1
```

**Comment by amadio** [comment] 2023-09-14 20:51
Thank you for the extra information. I will try to reproduce and investigate tomorrow, but a fix for this will probably not make it into the 5.6.2 release coming out tomorrow, but into 5.6.3 some time later. It could also be that a patch release is required for the server, though, not the client. To be seen.

**Comment by chaen** [comment] 2023-09-15 08:20
Thanks a lot !

**Comment by amadio** [comment] 2023-09-15 09:47
I can reproduce this problem, and it does look like it's a similar issue to #2014 with the roles of the client and server exchanged. This likely needs a similar patch to update the 4.x server to generate DH parameters that OpenSSL 3.x can trust. Unfortunately, the patch from #2026 is not so easy to apply to XRootD 4.x. Alternatively, I tried linking XRootD 4.x against OpenSSL 1.1 in CentOS 7, which solves the problem reported in #2014, but does not solve the problem with XRootD 4.x, unfortunately. The easiest option would likely be to update eosctalhcb.cern.ch to XRootD 5.x.

**Comment by beer4duke** [comment] 2023-09-21 08:21
> The easiest option would likely be to update eosctalhcb.cern.ch to XRootD 5.x.

This will be performed after HI run.

**Comment by amadio** [comment] 2023-10-12 11:06
Ok, since this is a problem with XRootD 4.x, which is out of support, Andy and I decided it's best to close the ticket as won't fix since the patch with a fix is not easy to backport to version 4.x. This should be resolved when CTA moves to EOS 5.x.

**Closed by amadio** 2023-10-12 11:06 UTC
Labels: Under Investigation
