### ISSUE TITLE
Socket errors leading to missed callbac (new deadlock in 4.6.1?)

### ISSUE THREAD

**Issue by bbockelm** [xrootd/xrootd#526] opened 2017-06-06 14:35 UTC
Hi,

CMS is now seeing a new pattern of deadlocks after the upgrade to 4.6.1:

https://github.com/cms-sw/cmssw/issues/14952#issuecomment-306488392

Does this look familiar to anyone?  Basically, it seems that the read callback isn't triggering...

Brian

**Comment by bbockelm** [comment] 2017-06-09 16:31
Any updates here?  This is starting to affect the release process, which subsequently starts to affect data taking...

**Comment by abh3** [comment] 2017-06-09 17:59
Not yet. However, it would be helpful if you tell us what thread is holding the lock that everyone is waiting on in the trace back you provided.

**Comment by bbockelm** [comment] 2017-06-11 06:46
Hi @abh3 -

Unfortunately, I don't have a good way to determine that - I only know it started to crop up in the latest release.  Did any of the lock ordering change then?

Brian

**Comment by abh3** [comment] 2017-06-11 14:37
There were some changes regarding how certain events are processed which was causing other problems. That may have inverted some locks. Next time this happens, could you get a gcore? This kind of stuff is hard to reproduce. We really need to know who has that lock because it will likely lead to the code path that's causing the problem.

**Comment by abh3** [comment] 2017-06-12 14:01
OK, I tracked this down as we have a reproducible case here. The problem s really a deadlock between file request tieout and file destruction. If a file is being closed and it so happens that the filetimer::Run() starts and calls FileStateHandler::Tick() at the moment the file is being closed, the whole thing deadlocks. It would seem hte simplest solution is to to simply do a trylock() in the Tick() method and if you can't get the lock then skip handling he timed out (it will be tried then interval if he file is still alive). Timeout can be triggered by a lot of things, socket errors is one of them. I don't see any changes in this code path but it might have changed in some related code path dealing with the FileStateHandler object lock.

**Comment by abh3** [comment] 2017-06-19 20:10
Hi Brian,

I put in a couple of patches that address deadlocks. These may or may not be the same deadlocks you saw but it was the ones that I saw. Could you give githead a try to see if this solves your problem?

Andy

**Comment by bbockelm** [comment] 2017-07-03 13:29
Hi Andy,

(Coming back from vacation - catching up on a few old threads.)

To try it in a CMS integration build (where this originally was spotted), we'd need a specific tag or a SHA1 hash.  What would you recommend?

Brian

**Comment by simonmichal** [comment] 2017-07-03 13:32
Would the bi-weekly build be OK ? I can set it up today / tomorrow if it helps ;-)

**Comment by bbockelm** [comment] 2017-07-03 13:38
Yeah, that would be perfect!

**Comment by simonmichal** [comment] 2017-07-04 08:36
Here it is:

slc6 repo:
http://xrootd.org/binaries/xrootd-experimental-slc6.repo

cc7 repo:
http://xrootd.org/binaries/xrootd-experimental-slc7.repo

(The URL of the repo will likely change in the future as we will be migrating from jenkins to gitlab)

Enjoy ;-)

**Comment by abh3** [comment] 2017-09-28 09:48
This should be fixed in 4.7. We'll reopen this if we get a new report.

**Closed by abh3** 2017-09-28 09:48 UTC
