### ISSUE TITLE
Unexpected XrdHttp behavior

### ISSUE THREAD

**Issue by jthiltges** [xrootd/xrootd#596] opened 2017-10-02 21:22 UTC
(Copying the email into an issue to hopefully make it easier to track. @abh3 @bbockelm @ffurano )

We are seeing unusual behavior from XRootD's HTTP interface. I'm suspecting that HTTP implementation is calling xrootd functions, then unintentionally getting behavior only intended for the xrootd protocol. I'm finding both unexpected output as well as a leak in XrdLink objects and file descriptors.

The samples below were run with xrootd-4.7.0-1.osg33.el7.x86_64 and a minimal configuration:

    xrd.port 1094
    all.role server
    all.export /tmp
    xrd.protocol http:8000 libXrdHttp.so

For a curl web request of a short file (12 bytes of "Hello world\n"), XrdHttp appears to return the content twice. From tcpdump (or sending the request with telnet):

    > GET /tmp/hello.txt HTTP/1.1
    > Host: xrootd-itb.unl.edu:8000
    > User-Agent: curl/7.47.1
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < Content-Length: 12
    <
    < Hello world
    < Hello world

The connection remains open as expected with HTTP/1.1, but trying to submit a second request triggers the server to close the connection.

For a longer file (60kB, 10000 lines), the content is not sent twice, but 12 nulls and what looks like a kXR_stat response (inode, size, flags, and mtime fields) are appended to the reply:

    > GET /tmp/test.10000L HTTP/1.1
    > Host: xrootd-itb.unl.edu:8000
    > User-Agent: curl/7.47.1
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < Content-Length: 60000
    <
    < 00001
    < 00002
    < 00003
    [snip]
    < 09998
    < 09999
    < 10000
    < ............193273593089 60000 16 1506616974.

Again, the connection remains open, but trying to submit a second request triggers the server to close the connection. Note that for the larger file, sendfile() is used to deliver the data. The change in code path might account for the different behavior.

Oddly enough, enabling request logging with "http.trace request" changes the server behavior for the larger 60kB file (but not the 12 byte one). The replies look fine (no additional kXR_stat data) and multiple requests can be submitted in the same HTTP connection. Is there a timing issue exposed by the logging overhead?

It also appears that XrdHttp sometimes holds onto XrdLink objects, particularly if the connection is not cleanly closed. This issue also appears to be timing related, with the problem showing up most easily by testing from localhost or a client on the same network. I first noticed the XrdLink counts (from xrdfs <hostname> query stats l) and open file descriptors steadily increasing for the xrootd process. It turns out that Nagios check_http is particularly good at triggering the issue.

    check_http --IP-address=127.0.0.1 --port=8000 --url=/tmp/hello.txt --no-body

The following python program should replicate the behavior of Nagios check_http. It does an HTTP request then immediately closes the connection. When requesting a small (~100 byte) file, it causes an XrdLink object to be left open roughly half the time.

```python
    import socket

    for i in range(1, 50):
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(1)

        s.connect(('127.0.0.1', 8000))

        s.send("GET /tmp/hello.txt HTTP/1.1\r\n")
        s.send("Host: localhost:8000\r\n")
        s.send("\r\n")

        resp = s.recv(8192)
        print len(resp)

        s.close()
```

**Comment by abh3** [comment] 2017-10-03 05:14
I've reproduced both conditions; hank you for reporting them along with test cases we can run. The double send seems to be related to http post-processing during file close. It's weird. The lost file descriptor is indeed timing dependent and appears to be incorrect handling of a broken pipe error. I don't yet know whether it's the http protocol not handling this correctly or some deeper systemic problem. More as we figure all this out.

**Comment by abh3** [comment] 2017-10-04 04:39
Hi jthiltges,

We have found the source of the FD leak and have a patch ready. It was a combination of a misunderstanding of what the HTTP plugin should do when a socket error is encountered (98% of the cases) and a systemic error that didn't deal with an unexpected error presentation peculiar to the Linux kernel (2% of the cases).

As for the oddity of not being able to send multiple HTTP requests on an open socket; do you have a small test program that demonstrates this behavior? It would speed thing along.

So, two issues still outstanding.

Andy

**Comment by jthiltges** [comment] 2017-10-04 14:42
I appreciate your help. To replicate the persistent connection issue, either telnet or the short python script below should work.

```python
import requests
import logging

logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)

s = requests.Session()

url = 'http://hcc-stash.unl.edu:8000/user/bbockelm/public/testfile'

for i in range(0, 3):
    print "Request #%d" % i
    r = s.get(url)
    print "Status = %d\n" % r.status_code
```

In the sample output below, we see "Resetting dropped connection", showing where the server disconnected. The requests are still successful due to error handling in the HTTP client.

```
Request #0
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): hcc-stash.unl.edu
DEBUG:requests.packages.urllib3.connectionpool:"GET /user/bbockelm/public/testfile HTTP/1.1" 200 1048576
Status = 200

Request #1
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: hcc-stash.unl.edu
DEBUG:requests.packages.urllib3.connectionpool:"GET /user/bbockelm/public/testfile HTTP/1.1" 200 1048576
Status = 200

Request #2
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: hcc-stash.unl.edu
DEBUG:requests.packages.urllib3.connectionpool:"GET /user/bbockelm/public/testfile HTTP/1.1" 200 1048576
Status = 200
```

**Comment by ffurano** [comment] 2017-10-04 14:56
Hi, and thank you very much for helping reproducing the issue. I run your little script on a server that has pull request #598, and I am getting a sane result. Would you like to try it out ?

-------------------------
$ python /tmp/test.py
Request #0
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): littlexrdhttp.cern.ch
DEBUG:requests.packages.urllib3.connectionpool:"GET /testfile HTTP/1.1" 200 11
Status = 200

Request #1
DEBUG:requests.packages.urllib3.connectionpool:"GET /testfile HTTP/1.1" 200 11
Status = 200

Request #2
DEBUG:requests.packages.urllib3.connectionpool:"GET /testfile HTTP/1.1" 200 11
Status = 200
---------------

I also tried with a file 1MB long, with the same result.

**Comment by jthiltges** [comment] 2017-10-05 15:58
From some quick tests, PR #598 seems to have fixed the persistent connections issue. Thank you!

If I can help with testing the FD leak issue, please let me know.

**Comment by xrootd-dev** [comment] 2017-10-06 23:20
OK, the file descripot leak patch is completely pushed. Please do check if 
this solves the problem.

Andy

**Comment by abh3** [comment] 2017-10-11 14:56
Any news on whether our final set of pathes solved all of the issues (including FD leaks)? We'd like to close this.

**Comment by jthiltges** [comment] 2017-10-11 20:20
@abh3 I've rebuilt xrootd from master and updated the server that was showing the problem. All the tests so far look good: HTTP output issues appear to be resolved and file descriptor counts look good. Thanks very much for your help.

**Comment by simonmichal** [comment] 2017-10-27 14:17
Any results from 4.7.1 RC2 tests?

**Comment by jthiltges** [comment] 2017-10-27 18:22
Same as Marian mentioned in #606, we're running it on our stashcache server and things are looking good. Thank you for your help.

**Closed** 2017-10-30 12:45 UTC
