### ISSUE TITLE
xrootd.tls all, gsi, and --tlsnodata not working together

### ISSUE THREAD

**Issue by wyang007** [xrootd/xrootd#1214] opened 2020-06-14 09:24 UTC
I have a setup with "xrootd.tls all" and GSI authentication. With that at the server side, a client using  "xrdcp --tlsnodata" will get an error 

[0B/0B][100%][==================================================][0B/s]
Run: [ERROR] Invalid response:  (source)

Obviously the client doesn't know how the server was setup. We may want a better error message, and also guidance on how to setup TLS with GSI authentication (and other authentications).

**Comment by simonmichal** [comment] 2020-06-16 12:59
@wyang007 : thanks for reporting it, though I cannot reproduce it, are you running with latest RC? It sounds a bit like the problem we fixed in: ccde53a953bba34a657b043abb78b38d9dc52872

**Comment by wyang007** [comment] 2020-06-18 06:50
@simonmichal: I tried both v5.0.0-rc4 and the current githead and they have the same issue. The problem doesn't show up when I set it up as a regular data server. But it shows up when my setup is a proxy server. 

I can enable your or @abh to login for debugging.

**Comment by simonmichal** [comment] 2020-06-18 08:04
@wyang007 : that's marvellous ;-) the kind of problem I like the best ;-) so the problem appears if the transfer is executed against a proxy server, right? If you could point me to an proxy server endpoint that I can use to reproduce the problem this would be superb!

**Comment by simonmichal** [comment] 2020-06-19 12:10
@wyang007 : this should fix the problem with `--tlnodata`: https://github.com/xrootd/xrootd/commit/1499b758b3888b9c8e6d8218910874b650228f76

However, the problem remains for transfers with data streams, e.g.: `xrdcp -S 1`

```
[2020-06-19 03:46:51.071785 -0700][Dump   ][AsyncSock         ] [griddev06.slac.stanford.edu:1094.1] Received message header for 0x440438c0 size: 8
[2020-06-19 03:46:51.071825 -0700][Dump   ][XRootD            ] [griddev06.slac.stanford.edu:1094] Got unrecognized response 4007 to message kXR_read (handle: 0x00000000, offset: 0, size: 1000000)
[2020-06-19 03:46:51.071851 -0700][Error  ][AsyncSock         ] [griddev06.slac.stanford.edu:1094.1] Socket error encountered: [ERROR] TLS error
[2020-06-19 03:46:51.071925 -0700][Debug  ][ExDbgMsg          ] [griddev06.slac.stanford.edu:1094] Calling MsgHandler: 0x1184db0 (message: kXR_read (handle: 0x00000000, offset: 0, size: 1000000) ) with status: [ERROR] Invalid response.
```

The code `4007` corresponds to `kXR_status`, which is not yet supported in the client.

To be investigated.

**Comment by abh3** [comment] 2020-06-19 19:40
Wierd, where do that status code come from? It wasn't suppose to be 
returned to old clients at all. I will need to look to see what happened 
(and review the ticket once again).

**Comment by simonmichal** [comment] 2020-06-22 19:45
@abh: have a look at:

```
[2020-06-22 12:08:08.603391 -0700][Dump   ][XRootD            ] [griddev06.slac.stanford.edu:1094] Sending message kXR_read (handle: 0x00000000, offset: 0, size: 1000000)
[2020-06-22 12:08:08.603452 -0700][Debug  ][ExDbgMsg          ] [griddev06.slac.stanford.edu:1094] MsgHandler created: 0x15c8ee0 (message: kXR_read (handle: 0x00000000, offset: 0, size: 1000000) ).
[2020-06-22 12:08:08.603580 -0700][Dump   ][PostMaster        ] [griddev06.slac.stanford.edu:1094] Sending message kXR_read (handle: 0x00000000, offset: 0, size: 1000000) (0x15c87b0) through substream 0 expecting answer at 1
[2020-06-22 12:08:08.603693 -0700][Dump   ][AsyncSock         ] [griddev06.slac.stanford.edu:1094.0] Wrote a message: kXR_read (handle: 0x00000000, offset: 0, size: 1000000) (0x15c87b0), 32 bytes
[2020-06-22 12:08:08.603762 -0700][Dump   ][AsyncSock         ] [griddev06.slac.stanford.edu:1094.0] Successfully sent message: kXR_read (handle: 0x00000000, offset: 0, size: 1000000) (0x15c87b0).
[2020-06-22 12:08:08.603783 -0700][Dump   ][XRootD            ] [griddev06.slac.stanford.edu:1094] Message kXR_read (handle: 0x00000000, offset: 0, size: 1000000) has been successfully sent.
[2020-06-22 12:08:08.603798 -0700][Debug  ][ExDbgMsg          ] [griddev06.slac.stanford.edu:1094] Moving MsgHandler: 0x15c8ee0 (message: kXR_read (handle: 0x00000000, offset: 0, size: 1000000) ) from out-queu to in-queue.
[2020-06-22 12:08:08.603838 -0700][Dump   ][PostMaster        ] [griddev06.slac.stanford.edu:1094.0] All messages consumed, disable uplink
[2020-06-22 12:08:08.610479 -0700][Dump   ][XRootDTransport   ] [msg: 0xa80437e0] Expecting 24 bytes of message body
[2020-06-22 12:08:08.610522 -0700][Dump   ][AsyncSock         ] [griddev06.slac.stanford.edu:1094.1] Received message header for 0xa80437e0 size: 8
[2020-06-22 12:08:08.610550 -0700][Dump   ][AsyncSock         ] [griddev06.slac.stanford.edu:1094.1] Received message 0xa80437e0 of 32 bytes
[2020-06-22 12:08:08.610570 -0700][Dump   ][PostMaster        ] [griddev06.slac.stanford.edu:1094] Handling received message: 0xa80437e0.
[2020-06-22 12:08:08.610647 -0700][Dump   ][XRootDTransport   ] [msg: 0xa804d230] Expecting -81562187 bytes of message body
[2020-06-22 12:08:08.610667 -0700][Dump   ][AsyncSock         ] [griddev06.slac.stanford.edu:1094.1] Received message header for 0xa804d230 size: 8
[2020-06-22 12:08:08.610724 -0700][Error  ][AsyncSock         ] [griddev06.slac.stanford.edu:1094.1] Socket error encountered: [ERROR] TLS error
[2020-06-22 12:08:08.610806 -0700][Debug  ][AsyncSock         ] [griddev06.slac.stanford.edu:1094.1] Closing the socket
[2020-06-22 12:08:08.610724 -0700][Dump   ][XRootD            ] [griddev06.slac.stanford.edu:1094] Got unrecognized response 4007 to message kXR_read (handle: 0x00000000, offset: 0, size: 1000000)
```

It's a response `kXR_read`.

**Comment by xrootd-dev** [comment] 2020-06-22 19:48
Could you give me a test case so I can reproduce this? First time i've 
seen this but maybe I haven't been testing the same thing.

**Comment by simonmichal** [comment] 2020-10-16 09:20
The issue has been fixed.

**Closed by simonmichal** 2020-10-16 09:20 UTC
Labels: bug (non-critical)
