### ISSUE TITLE
pip install xrootd error (but installed succesfully)

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#1114] opened 2020-01-15 12:11 UTC
trying a pip install --user xrootd on fedora 31 python 3.7 i got this : 
```
pip3 install --upgrade --user xrootd
Collecting xrootd
  Downloading https://files.pythonhosted.org/packages/35/37/5e49b5b682f535105e1532cf8860624b8aa6d04846fdbee99bf974a31728/xrootd-4.11.1.tar.gz (2.5MB)
     |████████████████████████████████| 2.5MB 995kB/s
Building wheels for collected packages: xrootd
  Building wheel for xrootd (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/home/ionelstan/tmp/pip-install-qcw6me4_/xrootd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /home/ionelstan/tmp/pip-wheel-xoypeylx --python-tag cp37:
  ERROR: [I] No git repository info found. Trying to interpret VERSION_INFO
  [!] VERSION_INFO file invalid. Unable to determine the version. Using "unknown"
  /usr/lib/python3.7/site-packages/setuptools/dist.py:474: UserWarning: Normalizing '4.11.1
  ' to '4.11.1'
    normalized_version,
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: option --python-tag not recognized
  ----------------------------------------
  ERROR: Failed building wheel for xrootd
  Running setup.py clean for xrootd
Failed to build xrootd
Installing collected packages: xrootd
  Running setup.py install for xrootd ... done
Successfully installed xrootd-4.11.1
```

**Comment by simonmichal** [comment] 2020-01-21 10:06
@adriansev : thanks for reporting this issue! I managed to reproduce it and although bdist_wheel indeed failed the overall process was successful. The bdist_wheel step is in fact non-operation and it is failing only because there is a wheel.bdist_wheel and distutils.command.bdist mismatch. Fixed in: c0849fe36ea353c8a922dd7ffa7e66d22c537a86

**Closed by simonmichal** 2020-01-21 10:06 UTC
