### ISSUE TITLE
Curl used by XrdHttpTpc fails depending on the CRLfile being used

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#2065] opened 2023-07-28 08:45 UTC
This is happening on CentOS7 running the following package versions:
```
rpm -qa | grep "openssl\|curl"
libcurl-7.29.0-59.el7_9.1.x86_64
curl-7.29.0-59.el7_9.1.x86_64
openssl-libs-1.0.2k-26.el7_9.x86_64
python-pycurl-7.19.0-19.el7.x86_64
openssl-1.0.2k-26.el7_9.x86_64
```

We saw in our EOSATLAS instance failed HTTP TPC pull transfers with the following signature:
```
230727 17:27:23 32353 TPC_PushRequest: event=TRANSFER_FAIL, local=/eos/atlas/<some>/<path>, user=(anonymous), bytes_transferred=0; HTTP library failure: Failed to load CRL file (path? access rights?, format?)
```

The reason for this failure seems to be the fact that the OpenSSL library can not handle CRL files that are larger than 100kB - and truncating the data that it reads. In this particular case the CRLfile constructed by the XRootD daemon [1] and passed as an argument to the curl library is just above the 100kB limit:
```
# ls -lrt /tmp/fst/.xrdtls/
total 1184
-rw-------. 1 daemon daemon  151532 Jul 28 10:31 ca_file.pem
-rw-------. 1 daemon daemon 1058459 Jul 28 10:31 crl_file.pem
```
For all other nodes where this CRLfile is below the 100kB limit the XRootD HTTP TPC transfers are successful. This seems to be a known limitation in that particular version of OpenSSL:
`https://github.com/openssl/openssl/blob/081314d07705aa58912845c213a48414d8f616a9/crypto/ocsp/ocsp_ht.c#L87C9-L87C29`

As a (dev) workaround XRootD could append CRL to this file taking into account this limitation. Operationally we'll try to limit the number of CRLs that go into this file for the time being.
There are other variations of a similar problem reported on the OpenSSL bug tracker. [2]

[1] https://github.com/xrootd/xrootd/blob/master/src/XrdTls/XrdTlsTempCA.cc#L178
[2] https://github.com/openssl/openssl/issues/8581

**Comment by esindril** [comment] 2023-07-28 09:57
Ok, actually things are more twisted than that. The error above is thrown when the following CRL is the first in the bundle:
```
 openssl crl -in /etc/grid-security/certificates/8dd53007.r0 -text 
Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: /DC=com/DC=DigiCert-Grid/O=DigiCert Grid/CN=DigiCert Grid CA-1 G2
        Last Update: Jul 26 20:32:27 2023 GMT
        Next Update: Aug 25 20:32:27 2023 GMT
        CRL extensions:
            X509v3 Authority Key Identifier: 
                keyid:36:59:CC:DF:3C:3A:E2:49:93:4F:25:12:42:B6:CF:E9:19:1F:32:B4

            X509v3 CRL Number: 
                3031
            X509v3 Issuing Distrubution Point: critical
                Full Name:
                  URI:http://crl3.digicert.com/DigiCertGridCA-1-G2.crl
                  URI:http://crl4.digicert.com/DigiCertGridCA-1-G2.crl

No Revoked Certificates.
    Signature Algorithm: sha256WithRSAEncryption
         4a:81:65:46:dc:72:17:ec:c5:3f:8a:1d:1c:af:e0:37:e0:f6:
         27:ae:5f:f2:9d:01:9e:e5:a4:69:42:46:98:17:15:88:6c:90:
         34:ba:36:5d:5a:1e:41:98:7a:01:42:2f:f8:63:72:b8:4b:6b:
         5c:44:8c:e3:1d:30:5b:8d:ee:b9:6c:98:70:e8:57:dd:57:7c:
         f6:6f:f1:c6:5f:be:c8:69:9e:61:98:1b:a0:ed:c0:ab:f5:7c:
         8d:ea:75:45:b4:a5:1c:87:38:c2:59:b6:6d:4d:06:1c:8c:26:
         4f:28:71:f9:3a:af:1d:cf:8c:59:2c:32:e7:71:e0:bd:ee:3a:
         e5:34:d0:7e:d6:fb:ec:db:55:2c:8b:da:c9:f8:7d:d2:95:87:
         a7:3a:22:50:9c:df:39:08:21:87:32:0c:e3:4e:2b:07:79:db:
         d8:bf:18:97:3a:c4:8f:94:76:df:b5:bd:7b:cb:e9:48:66:2d:
         2c:1f:06:40:45:c3:b3:e2:b3:b7:7b:88:38:75:d4:ba:5a:5b:
         b5:ee:44:35:4f:11:b9:db:f7:db:57:89:af:a0:88:0c:75:a1:
         25:6f:eb:29:b3:ae:24:60:68:3b:15:6d:4d:eb:a7:71:2b:b3:
         a5:22:8f:eb:f6:45:15:1b:22:a6:6f:c5:1e:5f:57:92:70:eb:
         a4:ec:c5:e1
```

In case it's not the first entry in the CRL bundle then things work fine - even if the full size of the file is bigger than 100kB.
Most likely the CRL extensions are playing a role here ...

**Comment by ccaffy** [comment] 2023-07-28 10:09
Just a note here, the following curl command does not work for the CRL described above:
[root@st-096-hh1516bd ~]# curl -v --cacert /tmp/fst/.xrdtls/ca_file.pem --crlfile bad_crl.pem https://storage01.lcg.cscs.ch:2880/pnfs/lcg.cscs.ch/atlas/atlasdatadisk/rucio/mc23_13p6TeV/a6/65
* About to connect() to storage01.lcg.cscs.ch port 2880 (#0)
*   Trying 2001:620:808:4321::181...
* Connected to storage01.lcg.cscs.ch (2001:620:808:4321::181) port 2880 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /tmp/fst/.xrdtls/ca_file.pem
  CApath: none
* Closing connection 0
curl: (82) Failed to load CRL file (path? access rights?, format?)

So it's not related to xrootd, but something twisted with curl and its internal usage of openssl...

**Comment by esindril** [comment] 2023-07-28 12:14
For reference this is the certificate/CRL that breaks curl:
```
# cat /etc/grid-security/certificates/DigiCertGridCA-1G2-Classic-2015.crl_url
http://crl4.digicert.com/DigiCertGridCA-1-G2.crl
http://crl3.digicert.com/DigiCertGridCA-1-G2.crl

# rpm -qf /etc/grid-security/certificates/DigiCertGridCA-1G2-Classic-2015.crl_url
ca_DigiCertGridCA-1G2-Classic-2015-1.121-1.noarch

# wget http://crl4.digicert.com/DigiCertGridCA-1-G2.crl

# openssl crl -in DigiCertGridCA-1-G2.crl -inform DER -outform PEM -text -noout
Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: /DC=com/DC=DigiCert-Grid/O=DigiCert Grid/CN=DigiCert Grid CA-1 G2
        Last Update: Jul 27 20:32:45 2023 GMT
        Next Update: Aug 26 20:32:45 2023 GMT
        CRL extensions:
            X509v3 Authority Key Identifier: 
                keyid:36:59:CC:DF:3C:3A:E2:49:93:4F:25:12:42:B6:CF:E9:19:1F:32:B4

            X509v3 CRL Number: 
                3032
            X509v3 Issuing Distrubution Point: critical
                Full Name:
                  URI:http://crl3.digicert.com/DigiCertGridCA-1-G2.crl
                  URI:http://crl4.digicert.com/DigiCertGridCA-1-G2.crl

No Revoked Certificates.
    Signature Algorithm: sha256WithRSAEncryption
         2a:3f:f0:e5:0f:41:ef:90:4d:f5:65:de:1b:9c:c5:79:86:88:
         21:36:ac:61:2d:85:53:6c:c3:98:38:9d:59:43:ba:ed:76:60:
         bb:8b:35:30:f7:5e:a2:d1:bb:6b:c0:67:27:df:63:45:b0:ce:
         38:ff:f1:56:52:2c:1a:08:74:51:53:4f:10:46:c7:0e:4c:40:
         49:28:22:04:bd:c0:7d:7d:34:f4:5a:23:1c:bd:57:7c:28:c7:
         e2:df:50:8a:a6:dc:83:c0:61:a9:98:e9:61:a3:4c:13:dd:2f:
         d6:38:65:06:28:18:7b:13:aa:c9:d6:ee:2c:46:32:36:c7:b7:
         30:3d:ad:e9:94:11:55:fd:55:a7:cd:dc:0a:d8:bc:80:95:92:
         a6:82:43:e5:f3:b5:cc:26:73:39:86:ed:e2:b7:5e:b1:59:8c:
         84:ed:ab:c6:bd:c4:c6:49:f6:0d:c5:14:77:5b:86:28:97:ba:
         bb:10:8b:37:aa:78:fb:ce:54:6e:2d:44:a0:58:5b:2e:36:08:
         f1:12:36:cc:92:1d:d6:58:23:51:e9:2e:a5:f6:97:87:c7:d3:
         d4:0e:33:6e:28:bb:41:f6:d8:bf:b3:83:77:bc:03:00:92:17:
         1c:9c:f1:fc:90:9f:b2:ed:37:e8:ae:ee:7c:9e:5a:9d:5b:01:
         be:04:87:d9
```

**Comment by bbockelm** [comment] 2023-07-31 02:44
@esindril - I'm a bit confused here.  Why are you referencing OpenSSL bugs?  If this is RHEL7, wouldn't it be a NSS bug as that's the library the system libcurl links against?

**Comment by esindril** [comment] 2023-07-31 08:07
I guess it's a bit of both, since the CRL bundle in XRootD is built using OpenSSL and curl uses nss - maybe there is some unhappiness coming from the use of the two ... I just put the reference there since it was looking very similar to the issue we saw. Indeed this is CentOS7.

**Comment by abh3** [comment] 2023-08-03 05:44
We seem to b e missing you post with the start of "Ok, actually things are more twisted than that". So, could you try posting that again? I can also add that as it came through on email but doesn't appear here. It's actually a critical observation. So, what sequence does work?

**Comment by esindril** [comment] 2023-08-03 08:13
Below you have a paste of the previous comment and at the end one more observation:

Ok, actually things are more twisted than that. The error above is thrown when the following CRL is the first in the bundle:

```
openssl crl -in /etc/grid-security/certificates/8dd53007.r0 -text 
Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: /DC=com/DC=DigiCert-Grid/O=DigiCert Grid/CN=DigiCert Grid CA-1 G2
        Last Update: Jul 26 20:32:27 2023 GMT
        Next Update: Aug 25 20:32:27 2023 GMT
        CRL extensions:
            X509v3 Authority Key Identifier: 
                keyid:36:59:CC:DF:3C:3A:E2:49:93:4F:25:12:42:B6:CF:E9:19:1F:32:B4

            X509v3 CRL Number: 
                3031
            X509v3 Issuing Distrubution Point: critical
                Full Name:
                  URI:http://crl3.digicert.com/DigiCertGridCA-1-G2.crl
                  URI:http://crl4.digicert.com/DigiCertGridCA-1-G2.crl

No Revoked Certificates.
    Signature Algorithm: sha256WithRSAEncryption
         4a:81:65:46:dc:72:17:ec:c5:3f:8a:1d:1c:af:e0:37:e0:f6:
         27:ae:5f:f2:9d:01:9e:e5:a4:69:42:46:98:17:15:88:6c:90:
         34:ba:36:5d:5a:1e:41:98:7a:01:42:2f:f8:63:72:b8:4b:6b:
         5c:44:8c:e3:1d:30:5b:8d:ee:b9:6c:98:70:e8:57:dd:57:7c:
         f6:6f:f1:c6:5f:be:c8:69:9e:61:98:1b:a0:ed:c0:ab:f5:7c:
         8d:ea:75:45:b4:a5:1c:87:38:c2:59:b6:6d:4d:06:1c:8c:26:
         4f:28:71:f9:3a:af:1d:cf:8c:59:2c:32:e7:71:e0:bd:ee:3a:
         e5:34:d0:7e:d6:fb:ec:db:55:2c:8b:da:c9:f8:7d:d2:95:87:
         a7:3a:22:50:9c:df:39:08:21:87:32:0c:e3:4e:2b:07:79:db:
         d8:bf:18:97:3a:c4:8f:94:76:df:b5:bd:7b:cb:e9:48:66:2d:
         2c:1f:06:40:45:c3:b3:e2:b3:b7:7b:88:38:75:d4:ba:5a:5b:
         b5:ee:44:35:4f:11:b9:db:f7:db:57:89:af:a0:88:0c:75:a1:
         25:6f:eb:29:b3:ae:24:60:68:3b:15:6d:4d:eb:a7:71:2b:b3:
         a5:22:8f:eb:f6:45:15:1b:22:a6:6f:c5:1e:5f:57:92:70:eb:
         a4:ec:c5:e1
```

In case it's not the first entry in the CRL bundle then things work fine - even if the full size of the file is bigger than 100kB.
Most likely the CRL extensions are playing a role here ...

The only sequence that does not work is when this CRL is the first one in the bundle CRLfile created by the XrdTlsTempCA class.

**Comment by ccaffy** [comment] 2023-08-18 13:55
OK, problem understood:

On the ATLAS instance, we have discovered that plenty of HTTP TPC PUSH transfers are failing on some FSTs.

For example:

```
cat /var/log/eos/fst/xrdlog.fst | grep CRL | tail
230818 10:33:07 864 TPC_PushRequest: event=TRANSFER_FAIL, local=/eos/atlas/atlasdatadisk/rucio/mc16_13TeV/1b/61/HITS.34368181._000586.pool.root.1, remote=https://atlas-google-europe-west1.cern.ch:443/atlas-europe-west1-datadisk/rucio/mc16_13TeV/HITS.34368181._000586.pool.root.1?GoogleAccessId=rucio-service%40rucio-integration-dev.iam.gserviceaccount.com&Expires=1692351187&Signature=LUzLgE5c%2FmARMvQ%2BmVyMQcR1TnDBVT8fjs5h%2F0s7VH8JeWwVp2os8vSG%2BcsfkiOGQvKYZk3NYXbymb30DHbSvCXtkXUb1QxmVentIvmUUA3wBiib03z6DYjxcpFFD6gMr6%2BTyg64iooPWaAXOJ8xyqPahLd%2ByHV%2FHgH9zz9nIj2e7ybWWDY3E71QOZHY1XDcmq%2BrCh9vNFjxsgQhXOZR7Jj5%2B%2FhWir6aq8A7WQZXS7t8S%2BhwVIj2IgG4eg30p8A7YOkT5qx6rrpSmVW7sRLhNE9sI0L%2FFthW6hVFGYELWtGI7cQOOpn8RAWV6%2BJVDJVSsFjAb5XFNBY1Mc02zSXJJA%3D%3D, user=(anonymous), bytes_transferred=0; HTTP library failure: Failed to load CRL file (path? access rights?, format?)
```

After lots of investigation, we found out that the cause of the failure was due to curl that failed load the CRL file coming from URLs contained in the package ca_DigiCertGridCA-1G2-Classic-2015-1.122-1.noarch.

The dump of that CRL file is:

```
$ openssl crl -in /etc/grid-security/certificates/8dd53007.r0 -text
Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: /DC=com/DC=DigiCert-Grid/O=DigiCert Grid/CN=DigiCert Grid CA-1 G2
        Last Update: Aug 16 20:48:10 2023 GMT
        Next Update: Sep 15 20:48:10 2023 GMT
        CRL extensions:
            X509v3 Authority Key Identifier: 
                keyid:36:59:CC:DF:3C:3A:E2:49:93:4F:25:12:42:B6:CF:E9:19:1F:32:B4
            X509v3 CRL Number: 
                3052
            X509v3 Issuing Distrubution Point: critical
                Full Name:
                  URI:http://crl3.digicert.com/DigiCertGridCA-1-G2.crl
                  URI:http://crl4.digicert.com/DigiCertGridCA-1-G2.crl
No Revoked Certificates.
    Signature Algorithm: sha256WithRSAEncryption
         6e:a0:79:2c:dc:e8:6d:74:a9:1d:9e:b6:01:5d:c7:af:b3:64:
         04:80:75:d0:94:c6:10:07:51:37:78:dc:f6:cf:8d:eb:35:1a:
         f8:fc:5f:0e:56:c2:6f:6a:e0:3c:81:ca:77:9a:6b:c8:5a:67:
         ab:71:13:23:2f:06:e1:f7:c2:10:1d:32:e3:d5:44:d6:31:99:
         e1:69:4c:0e:90:ae:c1:99:e2:35:55:88:e1:78:46:9f:10:60:
         9f:43:0b:a8:ce:f5:2e:eb:b9:bd:54:28:07:33:c2:32:7c:a4:
         1b:8e:d6:aa:06:b9:d4:cd:c2:45:2d:76:35:02:60:45:f0:00:
         5f:c3:5d:bf:ff:65:2b:57:f8:bd:ab:ad:32:a8:ae:1c:d0:51:
         4b:d7:92:be:39:2c:ea:e1:9b:d5:66:6b:e4:91:4e:fe:da:9d:
         16:13:b8:7c:a8:92:07:c4:26:35:78:bb:5e:38:a5:11:53:c2:
         6a:54:18:15:75:d6:61:80:83:de:14:d2:ad:96:49:b2:15:06:
         9a:e8:ee:d9:b8:9d:90:3e:74:9d:26:3c:5f:fd:92:7a:1f:5a:
         bf:65:3a:20:b4:0a:cc:c2:00:5c:6a:6f:28:a3:4a:f5:09:fb:
         0a:52:e3:f9:52:00:f5:2d:ee:a2:92:94:bf:24:7b:3c:14:70:
         af:03:f8:4e
-----BEGIN X509 CRL-----
MIICYDCCAUgCAQEwDQYJKoZIhvcNAQELBQAwbDETMBEGCgmSJomT8ixkARkWA2Nv
bTEdMBsGCgmSJomT8ixkARkWDURpZ2lDZXJ0LUdyaWQxFjAUBgNVBAoTDURpZ2lD
ZXJ0IEdyaWQxHjAcBgNVBAMTFURpZ2lDZXJ0IEdyaWQgQ0EtMSBHMhcNMjMwODE2
MjA0ODEwWhcNMjMwOTE1MjA0ODEwWqCBpzCBpDAfBgNVHSMEGDAWgBQ2WczfPDri
SZNPJRJCts/pGR8ytDALBgNVHRQEBAICC+wwdAYDVR0cAQH/BGowaKBmoGSGMGh0
dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdyaWRDQS0xLUcyLmNybIYw
aHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R3JpZENBLTEtRzIuY3Js
MA0GCSqGSIb3DQEBCwUAA4IBAQBuoHks3OhtdKkdnrYBXcevs2QEgHXQlMYQB1E3
eNz2z43rNRr4/F8OVsJvauA8gcp3mmvIWmercRMjLwbh98IQHTLj1UTWMZnhaUwO
kK7BmeI1VYjheEafEGCfQwuozvUu67m9VCgHM8IyfKQbjtaqBrnUzcJFLXY1AmBF
8ABfw12//2UrV/i9q60yqK4c0FFL15K+OSzq4ZvVZmvkkU7+2p0WE7h8qJIHxCY1
eLteOKURU8JqVBgVddZhgIPeFNKtlkmyFQaa6O7ZuJ2QPnSdJjxf/ZJ6H1q/ZTog
tArMwgBcam8oo0r1CfsKUuP5UgD1Le6ikpS/JHs8FHCvA/hO
-----END X509 CRL-----
```

If we follow the URL, this CRL is actually coming from the following page: https://www.digicert-grid.com/ , look for `DigiCert Grid CA-1 G2`

We noticed that if that CRL is NOT the first read by curl, the transfers succeeds. But on the case of the failed transfer above, the bundled CRL file has that CRL in the first position. We only see this problem by chance!

I initially thought that that CRL was badly formed. But why would openssl be able to dump it without any issue?

The fault does not come from the CRL. I tried to use that CRL on our centos 7 machine with the following curl command, and it fails:
```
$ curl -v --cacert /tmp/fst/.xrdtls/ca_file.pem --crlfile /etc/grid-security/certificates/8dd53007.r0 https://storage01.lcg.cscs.ch:2880/pnfs/lcg.cscs.ch/atlas/atlasdatadisk/rucio/mc23_13p6TeV/a6/65
* About to connect() to storage01.lcg.cscs.ch port 2880 (#0)
*   Trying 2001:620:808:4321::181...
* Connected to storage01.lcg.cscs.ch (2001:620:808:4321::181) port 2880 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /tmp/fst/.xrdtls/ca_file.pem
  CApath: none
* Closing connection 0
curl: (82) Failed to load CRL file (path? access rights?, format?)
```

BUT, on a machine which is running Rhel 9, everything works fine.

I managed to find what the problem is. I noticed that the curl installed on Rhel 9 has been compiled with openssl:
```
$ curl -V
curl 7.76.1 (x86_64-redhat-linux-gnu) libcurl/7.76.1 OpenSSL/3.0.7 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.10.4/openssl/zlib nghttp2/1.43.0
```

but on the CentOS 7 machine where the XRootD server is running, it is not the case:

```
$ curl -V
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
```

After having compiled CURL 7.29.0 with openssl on my CentOS 7 dev machine, I managed to make the CRL file loading work.

So, the issue comes from the fact that curl and libcurl coming from CentOS 7 don't use openssl to read CRLs. It instead uses NSS.
According to the website providing that CRL, SHA-2 has been used for its encoding. Probably NSS does not support that type of hash and therefore fails to load the CRL. If that CRL is the first that curl tries to load, it will immediately fail and will not try to load the remaining CRLs in the CRL bundled file...

The following command allows to test, on a machine, which CRL does not work:

```
find  /etc/grid-security/certificates/ -name *.r0 | xargs -i bash -c 'curl -v --capath /etc/grid-security/certificates --crlfile {} https://storage01.lcg.cscs.ch:2880/pnfs/lcg.cscs.ch/atlas/atlasdatadisk/rucio/mc23_13p6TeV/a6/65 2>/dev/null 1>/dev/null || echo {}'
```

**Comment by bbockelm** [comment] 2023-08-18 18:53
To the best of my knowledge, there's O(10) certificates that use DigiCert Grid CA in the US as most universities have an InCommon CA subscription.  These are all host certificate so I'm fairly certain there's minimal risk to do a workaround here.

To avoid dropping it when the OpenSSL backend is in use, what if we simply sort any CRL with this particular OID set as critical to the of the list around here: https://github.com/xrootd/xrootd/blob/master/src/XrdTls/XrdTlsTempCA.cc#L188

I've got no interest in trying to redistribute system libraries... especially considering the enormous patch sets that RHEL runs on these.

**Comment by maarten-litmaath** [comment] 2023-08-18 19:28
Putting such CRLs at the **end** of the list looks a good trick indeed.

**Comment by ccaffy** [comment] 2023-08-21 10:04
I did the following PR so that every CRL containing critical extension will be inserted at the end of the CRL bundle file: https://github.com/xrootd/xrootd/pull/2073

**Comment by esindril** [comment] 2023-08-21 11:33
@amadio could you pick up also this one for the next patch release 5.6.2? Thanks!

**Comment by amadio** [comment] 2023-08-21 12:12
> @amadio could you pick up also this one for the next patch release 5.6.2? Thanks!

Yes, no problem, I will mark it as 5.6.2 to ensure it.

**Comment by amadio** [comment] 2023-09-04 08:41
Fixed by https://github.com/xrootd/xrootd/commit/fd5d2d8b23769971eb62bb111651a0fb693b9292.

**Closed by amadio** 2023-09-04 08:41 UTC
Labels: bug (non-critical)
