### ISSUE TITLE
Occasional 'xrdcp killed by signal 11' during TPC

### ISSUE THREAD

**Issue by rcarpa** [xrootd/xrootd#2164] opened 2024-01-16 13:43 UTC
Hi team. In our dev environment sometimes we get `xrdcp killed by signal 11` . I'm not at all qualified to investigate it. 

Here is the full log (please note that it mixes the logs of the source XRD1 and destination XRD3): 

[xrootd.log](https://github.com/xrootd/xrootd/files/13950692/xrootd.log)

Can you advise on this matter ? 

The configuration is as follows : 
```
all.export /rucio
xrd.tls /etc/grid-security/xrd/xrdcert.pem /etc/grid-security/xrd/xrdkey.pem detail
xrd.tlsca certfile /etc/grid-security/certificates/5fca1cb1.0 certdir /etc/grid-security/certificates/ proxies
xrootd.tls all
if exec xrootd
  xrd.protocol http:1094 /usr/lib64/libXrdHttp.so
  http.exthandler xrdtpc /usr/lib64/libXrdHttpTPC.so
fi

xrd.trace all
xrootd.trace all

acc.authdb /etc/xrootd/Authfile
xrootd.seclib /usr/lib64/libXrdSec.so
ofs.authorize
ofs.authlib ++ libXrdAccSciTokens.so config=/etc/xrootd/scitokens.cfg
sec.protocol /usr/lib64 gsi -dlgpxy:1 -exppxy:=creds
sec.protocol /usr/lib64 ztn -expiry required -maxsz 20k
xrootd.chksum adler32 /usr/local/bin/xrdadler32.sh
ofs.tpc autorm fcreds gsi =X509_USER_PROXY pgm /usr/bin/xrdcp --server

xrd.port 1094
```

```
# xrootd -v
v5.6.3
```

Regards, 
Radu

**Comment by amadio** [comment] 2024-01-16 15:49
If token authentication is involved, it may have been fixed in the latest version (issues #2114 , #2143, 5.6.4). Could you please try again with XRootD 5.6.4? If the problem persists, a core dump might provide more useful information if the process crashing is the one invoked to perform the third-party copy. Thank you!

**Comment by rcarpa** [comment] 2024-01-16 16:00
I just managed to reproduce it with 5.6.4. Sometimes it goes without issues. Sometimes it fails. Token authentication is active, but this particular transfer doesn't use tokens. It relies on GSI authentication (logs show this)

**Comment by amadio** [comment] 2024-01-16 16:27
I can see that GSI protocol is used, but the [fix](https://github.com/xrootd/xrootd/pull/2118) was not in a token specific part of XRootD. In any case, the relevant part of the log for me is:
```
240116 13:28:15 033 XrdTLS: anon.0:34@dev-xrd3-1.dev_default TLS error rc=-1 ec=5 (error_syscall) errno=104.
240116 13:28:15 019 anon.0:34@dev-xrd3-1.dev_default Xrd_Poll: Poller 0 removing FD 34
*** 240116 13:28:15 033 XrdLinkXeq: TLS connection from anon.0:34@dev-xrd3-1.dev_default failed; connection reset by peer
*** 240116 13:28:15 033 XrootdXeq: Unable to enable TLS for anon.0:34@dev-xrd3-1.dev_default
240116 13:28:15 033 XrootdXeq: anon.0:34@dev-xrd3-1.dev_default disc 0:00:00
240116 13:28:15 033 anon.0:34@dev-xrd3-1.dev_default Xrd_Poll: Poller 0 removing FD 34
240116 13:28:15 034 XrdTLS: xrootd.243:33@dev-xrd3-1.dev_default TLS error rc=0 ec=1 (error_ssl) errno=0.
240116 13:28:15 033 anon.0:34@dev-xrd3-1.dev_default Xrd_Poll: FD 34 detached from poller 0; num=1
240116 13:28:15 021 xrootd.243:33@dev-xrd3-1.dev_default Xrd_Poll: Poller 2 removing FD 33
240116 13:28:15 034 XrdTLS: xrootd.243:33@dev-xrd3-1.dev_default 40560DFBE87F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:320:
 
240116 13:28:15 034 XrootdXeq: xrootd.243:33@dev-xrd3-1.dev_default disc 0:00:01
240116 13:28:15 034 xrootd.243:33@dev-xrd3-1.dev_default Xrd_Poll: Poller 2 removing FD 33
240116 13:28:15 034 xrootd.243:33@dev-xrd3-1.dev_default Xrd_Poll: FD 33 detached from poller 2; num=0
*** 240116 13:28:15 242 ofs_Run: /usr/bin/xrdcp killed by signal 11
240116 13:28:15 242 ofs_TPC: fts3.877:27@dev-fts-1.dev_default /rucio/mock/a4/ca/WRBJUR-conveyor-file_exists_handled-file_0a90adadfc7540e0b77df4cbc29b16ab Copy failed with return code 32
```

This only shows that the `xrdcp` which has been called to perform the copy was killed by signal 11, but doesn't give an indication of why the process crashed. Maybe if there's a core dump of the crashing process, could you get a stack trace? Do you see anything with `coredumpctl`? What was the command you used for the TPC?

**Comment by rcarpa** [comment] 2024-01-17 08:08
This is running in docker containers so systemd is not running. If you can assist me on how to configure everything to generate a core dump, I can try reproduce it again.

**Comment by amadio** [comment] 2024-01-17 09:06
I can try to run your container image, or you can send me the command line you used for the TPC transfer and the authentication method, so I can try to reproduce the problem locally. What do you think?

**Comment by rcarpa** [comment] 2024-01-17 12:12
The core dump doesn't seem to be generated at all during this crash. I managed to get core dumps from another software on purpose in the same container to ensure that core dumps are actually generated, but nothing from `xrdcp`. Maybe I'm doing something wrong. 

The crash doesn't always happen. It is quite rare. I don't have an explicit perfectly reproductible command to provide you because this is an FTS submission. I would have to dig into what FTS does to understand it. Moreover, there are multiple concurrent submissions at the same time, which may (or may not) be the cause. The issue was triggered in our (rucio) integration tests. I can "sometimes" manually trigger it with the following commands: 
```
git clone -b patch-0-token_test2 git@github.com:rcarpa/rucio.git
cd rucio/
docker-compose --file etc/docker/dev/docker-compose.yml --profile storage --profile iam up
docker exec -it dev-rucio-1 /bin/bash -c "./tools/run_tests.sh -ira; while pytest tests/test_conveyor.py::test_file_exists_handled; do echo restart; done"
```
A test failure should indicate that the issue was triggered. But it's quite rare.

**Comment by rcarpa** [comment] 2024-01-22 09:39
Did you manage to reproduce the issue on your side with the steps I have written?

**Comment by amadio** [comment] 2024-01-22 13:04
This is what I see, but it's hard to tell if it's a similar problem to what you reported above or not:
```
tests/test_conveyor.py F                                                                                                                                [100%]

========================================================================== FAILURES ===========================================================================
___________________________________________________________ test_file_exists_handled[caches_mock0] ____________________________________________________________

overwrite_on_tape_topology = <function overwrite_on_tape_topology.<locals>.__create_dids at 0x7f3be1a71af0>
caches_mock = [<dogpile.cache.region.CacheRegion object at 0x7f3be1ad4b50>, <dogpile.cache.region.CacheRegion object at 0x7f3be1a3cd...ogpile.cache.region.CacheRegion object at 0x7f3be1a3c910>, <dogpile.cache.region.CacheRegion object at 0x7f3be1a95820>]

    @skip_rse_tests_with_accounts
    @pytest.mark.dirty(reason="leaves files in XRD containers")
    @pytest.mark.noparallel(groups=[NoParallelGroups.SUBMITTER, NoParallelGroups.POLLER])
    @pytest.mark.parametrize("caches_mock", [{"caches_to_mock": [
        'rucio.core.rse.REGION',
        'rucio.core.rse_expression_parser.REGION',  # The list of multihop RSEs is retrieved by an expression
        'rucio.core.config.REGION',
        'rucio.rse.rsemanager.RSE_REGION',  # for RSE info
    ]}], indirect=True)
    def test_file_exists_handled(overwrite_on_tape_topology, caches_mock):
        """
        If a transfer fails because the destination job_params exists, and the size+checksums of that existing job_params
        are correct, the transfer must be marked successful.
        """
        rse1_id, rse2_id, rse3_id, did1, did2 = overwrite_on_tape_topology(did1_corrupted=False, did2_corrupted=False)
        all_rses = [rse1_id, rse2_id, rse3_id]
    
        class _FTSWrapper(FTSWrapper):
            @staticmethod
            def on_receive(job_params):
                for job in (job_params if isinstance(job_params, list) else [job_params]):
                    for file in job.get('files', []):
                        if (file.get('file_metadata', {}).get('dst_type') == 'TAPE'
                                and file.get('file_metadata', {}).get('dst_file', {}).get('file_on_tape') is not None):
                            # Fake that dst_file metadata contains file_on_tape == True
                            # As we don't really have tape RSEs in our tests, file_on_tape is always false
                            file['file_metadata']['dst_file']['file_on_tape'] = True
                return job_params
    
        with patch('rucio.daemons.conveyor.poller.FTS3Transfertool', _FTSWrapper):
            submitter(once=True, rses=[{'id': rse_id} for rse_id in all_rses], group_bulk=10, partition_wait_time=0, transfertype='single', filter_transfertool=None)
    
            request = __wait_for_state_transition(dst_rse_id=rse3_id, **did1)
>           assert request['state'] == RequestState.DONE
E           AssertionError: assert <RequestState.FAILED: 'F'> == <RequestState.DONE: 'D'>
E            +  where <RequestState.DONE: 'D'> = RequestState.DONE

tests/test_conveyor.py:1267: AssertionError
---------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------
WARNING  root:uploadclient.py:363 Scope mock not found for the account root.
WARNING  root:uploadclient.py:363 Scope mock not found for the account root.
====================================================================== warnings summary =======================================================================
tests/test_conveyor.py::test_file_exists_handled[caches_mock0]
  /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'rucio'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
    warnings.warn(

tests/test_conveyor.py::test_file_exists_handled[caches_mock0]
  /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'fts'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================================================================== short test summary info ===================================================================
FAILED tests/test_conveyor.py::test_file_exists_handled[caches_mock0] - AssertionError: assert <RequestState.FAILED: 'F'> == <RequestState.DONE: 'D'>
========================================================== 1 failed, 2 warnings in 74.91s (0:01:14) ===========================================================
```
Isn't there a simpler setup where the failure can be reproduced?

**Comment by rcarpa** [comment] 2024-01-22 13:28
Yes. Most probably this is a sign that the issue was triggered. You can check the logs of the xrootd containers `docker logs dev-xrd1-1` for example. The following 3 containers : `dev-xrd1-1`, `dev-xrd3-1`, dev-xrd4-1`  are involved in the transfers during this test. Check if one of them suffered a segmentation fault. Unfortunately, I don't have a simpler setup to offer.

**Comment by amadio** [comment] 2024-01-22 13:40
I replaced the tpc program with a script, to try to get more information, this is what I saw:
```
xrd1-1                     | 240122 13:28:22 035 anon.0:33@dev-xrd3-1.dev_default TLS_Accept: Accepting a TLS connection...
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default TLS_Read: 24 out of 24 bytes.
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default Xrootd_Protocol: 0100 req=close dlen=0
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default Xrootd_File: serializing access r Ref=0 /rucio/test/f3/14/file2
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default Xrootd_File: File::Ref=1 after +1 /rucio/test/f3/14/file2
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default Xrootd_Protocol: 0100  fh=0 close rc=0
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default Xrootd_File: File::Ref=0 after +-1 /rucio/test/f3/14/file2
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default Xrootd_File: serializing access r Ref=0 /rucio/test/f3/14/file2
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default Xrootd_File: closing r /rucio/test/f3/14/file2
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default Xrootd_Response: 0100 sending OK
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default TLS_Write: 8 out of 8 bytes.
xrd1-1                     | 240122 13:28:22 035 XrdTLS: anon.0:33@dev-xrd3-1.dev_default TLS error rc=-1 ec=1 (error_ssl) errno=0.
xrd1-1                     | 240122 13:28:22 035 XrdTLS: anon.0:33@dev-xrd3-1.dev_default 40965FA7437F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1600:SSL alert number 80
xrd1-1                     | 
xrd1-1                     | 240122 13:28:22 035 XrdLinkXeq: TLS connection from anon.0:33@dev-xrd3-1.dev_default failed; error_ssl
xrd1-1                     | 240122 13:28:22 035 XrootdXeq: Unable to enable TLS for anon.0:33@dev-xrd3-1.dev_default
xrd1-1                     | 240122 13:28:22 035 XrootdXeq: anon.0:33@dev-xrd3-1.dev_default disc 0:00:00
xrd1-1                     | 240122 13:28:22 035 anon.0:33@dev-xrd3-1.dev_default Xrd_Poll: Poller 0 removing FD 33
xrd1-1                     | 240122 13:28:22 035 anon.0:33@dev-xrd3-1.dev_default Xrd_Poll: FD 33 detached from poller 0; num=1
xrd1-1                     | 240122 13:28:22 018 XrdTLS: root.132:32@dev-xrd3-1.dev_default TLS error rc=0 ec=6 (zero_return) errno=0.
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default TLS_Shutdown: Doing fast shutdown.
xrd1-1                     | 240122 13:28:22 018 XrootdXeq: root.132:32@dev-xrd3-1.dev_default disc 0:00:01
xrd1-1                     | 240122 13:28:22 022 root.132:32@dev-xrd3-1.dev_default Xrd_Poll: Poller 2 removing FD 32
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default Xrd_Poll: Poller 2 removing FD 32
xrd1-1                     | 240122 13:28:22 018 root.132:32@dev-xrd3-1.dev_default Xrd_Poll: FD 32 detached from poller 2; num=0
xrd3-1                     | 240122 13:28:22 127 ofs_Run: /etc/xrootd/tpc.sh ended with status 54
xrd3-1                     | 240122 13:28:22 127 ofs_TPC: fts3.475:27@dev-fts-1.dev_default /rucio/test/f3/14/file2 [ERROR] Local error: file exists:  (destination)
xrd3-1                     | 240122 13:28:22 040 Xrd_Sched: running async response inq=0
```

Status 54 indicates redirection error. I don't observe any crashes, however.

**Comment by abh3** [comment] 2024-01-22 16:19
I don't think that this is a good thing. What is going on to provoke this:
xrd1-1                     | 240122 13:28:22 035 XrdTLS: anon.0:33@dev-xrd3-1.dev_default TLS error rc=-1 ec=1 (error_ssl) errno=0.
xrd1-1                     | 240122 13:28:22 035 XrdTLS: anon.0:33@dev-xrd3-1.dev_default 40965FA7437F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1600:SSL alert number 80
xrd1-1                     | 
xrd1-1                     | 240122 13:28:22 035 XrdLinkXeq: TLS connection from anon.0:33@dev-xrd3-1.dev_default failed; error_ssl

Note alert 80 is "internal error". The OpenSSL here appears to be version 3 which is substantially different from previous version (i.e. there is no line 1600 in older versions). Any pointer to the github repo to the version you are using?

**Comment by rcarpa** [comment] 2024-01-22 18:50
we don't do anything fancy. The containers are built from this dockerfile: https://github.com/rucio/containers/blob/master/xrootd/Dockerfile . And then use these files with some minor edits (https://github.com/rucio/rucio/tree/master/etc/docker/dev/xrd) or the xrootd configuration Openssl 3.0 is the default on RHEL9-derivatives. In this particular case, alma9.

**Comment by rcarpa** [comment] 2024-01-23 08:30
Ah, considering the openssl 3.0. Forgot to mention : to be noted that openssl on rhel9 is not really the vanilla 3.0. They have these monsters with hundreds of backports and security patches (the [source rpm](https://mirror.stream.centos.org/9-stream/BaseOS/source/tree/Packages/openssl-3.0.7-25.el9.src.rpm) has literally 130 patches on top of vanilla 3.0.7)

**Comment by abh3** [comment] 2024-01-23 19:44
Doesn't give you a warm fuzzy feeling about security, does it.
________________________________

**Comment by rcarpa** [comment] 2024-01-23 22:12
How else would they handle it? That's the whole point and the whole added benefit of using RHEL. And they reason why people pay for its licence: have somebody maintain a patched (for security reason) version of stable (i.e.:  old) software for a very long time (10+ years). To avoid the need to adapt the in-house software to a new breaking change of some library every 2 months :)

**Comment by abh3** [comment] 2024-01-23 23:35
What I meant by that comment is that given the number of changes that needed to be done you can come to the conclusion a) the original code was badly written, and b) a good probability that not everything is fixed. Hence the no so warm and fuzzy feeling.
________________________________

**Comment by amadio** [comment] 2024-01-24 08:27
Yes, I tend to agree with the comment above, the number of changes is mostly due to 3.0.7 being released a while ago. However, let's please not veer too off-topic lest we lose focus of what this ticket is about. I could reproduce this, just need enough time to get to the underlying cause and create a fix for it.

**Comment by rcarpa** [comment] 2024-01-24 08:30
Did you reproduce it with a simper use-case? or did you still have to use rucios complex test infrastructure ?

**Comment by amadio** [comment] 2024-01-24 08:33
No, I am running your docker-compose setup for now. I do plan to create a specific test once I identify what the problem is, though.

**Comment by smithdh** [comment] 2024-02-01 09:45
I've got a stack trace (and core) from the xrdcp inside one of the containers (e.g. dev_xrd3_1). This container uses alma9, openssl-3.0.7-25:

{code}
#0  0x00007f796eaa5c70 in pthread_rwlock_wrlock@GLIBC_2.2.5 () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f796e1ef640 (LWP 367))]
(gdb) where
#0  0x00007f796eaa5c70 in pthread_rwlock_wrlock@GLIBC_2.2.5 () from /lib64/libc.so.6
#1  0x00007f796e5bda9d in CRYPTO_THREAD_write_lock () from /lib64/libcrypto.so.3
#2  0x00007f796e56bcfc in ENGINE_pkey_asn1_find_str () from /lib64/libcrypto.so.3
#3  0x00007f796e4bd90b in EVP_PKEY_asn1_find_str () from /lib64/libcrypto.so.3
#4  0x00007f796e59e0e4 in find_ameth () from /lib64/libcrypto.so.3
#5  0x00007f796e5b4062 in ossl_namemap_doall_names () from /lib64/libcrypto.so.3
#6  0x00007f796e59f445 in EVP_PKEY_set_type_by_keymgmt () from /lib64/libcrypto.so.3
#7  0x00007f796e5a2ec5 in EVP_PKEY_copy_parameters () from /lib64/libcrypto.so.3
#8  0x00007f796f0930ba in tls_parse_stoc_key_share () from /lib64/libssl.so.3
#9  0x00007f796f086f79 in tls_parse_all_extensions () from /lib64/libssl.so.3
#10 0x00007f796f09d6ed in tls_process_server_hello () from /lib64/libssl.so.3
#11 0x00007f796f09adbf in state_machine.part () from /lib64/libssl.so.3
#12 0x00007f796f13655a in XrdTlsSocket::Connect(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) () from /lib64/libXrdUtils.so.3
#13 0x00007f796f30a9b4 in XrdCl::Tls::Connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, XrdNetAddrInfo*) () from /lib64/libXrdCl.so.3
#14 0x00007f796f30c310 in XrdCl::Socket::TlsHandShake(XrdCl::AsyncSocketHandler*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib64/libXrdCl.so.3
#15 0x00007f796f392bfa in XrdCl::AsyncSocketHandler::DoTlsHandShake() () from /lib64/libXrdCl.so.3
#16 0x00007f796f393999 in XrdCl::AsyncSocketHandler::Event(unsigned char, XrdCl::Socket*) ()
   from /lib64/libXrdCl.so.3
#17 0x00007f796f30c48a in (anonymous namespace)::SocketCallBack::Event(XrdSys::IOEvents::Channel*, void*, int) ()
   from /lib64/libXrdCl.so.3
#18 0x00007f796f12691f in XrdSys::IOEvents::Poller::CbkXeq(XrdSys::IOEvents::Channel*, int, int, char const*) ()
   from /lib64/libXrdUtils.so.3
#19 0x00007f796f126fd0 in XrdSys::IOEvents::PollE::Dispatch(XrdSys::IOEvents::Channel*, unsigned int) ()
   from /lib64/libXrdUtils.so.3
#20 0x00007f796f1271d8 in XrdSys::IOEvents::PollE::Begin(XrdSysSemaphore*, int&, char const**) ()
   from /lib64/libXrdUtils.so.3
#21 0x00007f796f123d31 in XrdSys::IOEvents::BootStrap::Start(void*) () from /lib64/libXrdUtils.so.3
#22 0x00007f796f12bb1c in XrdSysThread_Xeq () from /lib64/libXrdUtils.so.3
#23 0x00007f796ea9f802 in start_thread () from /lib64/libc.so.6
#24 0x00007f796ea3f450 in clone3 () from /lib64/libc.so.6
{code}

seems to be openssl involved. I'll try to trace it through.

**Comment by amadio** [comment] 2024-02-01 12:31
Maybe related: https://github.com/openssl/openssl/issues/22990

**Comment by smithdh** [comment] 2024-02-01 13:16
For completeness, these are the arguments xrdcp was invoked with:

```
/usr/bin/xrdcp --server -S 1 xroot://xrd1:1094///rucio/mock/a9/65/JAWPOC-conveyor-file_exists_handled-file_aa051953d0d54a879fdfb90efc0aa8bb? /rucio/mock/a9/65/JAWPOC-conveyor-file_exists_handled-file_aa051953d0d54a879fdfb90efc0aa8bb
```

I noticed that along with the crashing thread, thread 3 is most likely relevant too:

```
(gdb) thread 3
[Switching to thread 3 (Thread 0x7f796f47f840 (LWP 366))]
#0  0x00007f796e5a7c97 in OPENSSL_LH_doall () from /lib64/libcrypto.so.3
(gdb) where
#0  0x00007f796e5a7c97 in OPENSSL_LH_doall () from /lib64/libcrypto.so.3
#1  0x00007f796e5b4160 in ossl_namemap_free () from /lib64/libcrypto.so.3
#2  0x00007f796e5b6545 in CRYPTO_free_ex_data () from /lib64/libcrypto.so.3
#3  0x00007f796e5b66df in context_deinit.part () from /lib64/libcrypto.so.3
#4  0x00007f796e5b91f2 in OPENSSL_cleanup () from /lib64/libcrypto.so.3
#5  0x00007f796ea574dd in __run_exit_handlers () from /lib64/libc.so.6
#6  0x00007f796ea57620 in exit () from /lib64/libc.so.6
#7  0x00007f796ea3feb7 in __libc_start_call_main () from /lib64/libc.so.6
#8  0x00007f796ea3ff60 in __libc_start_main_impl () from /lib64/libc.so.6
#9  0x0000559474a9faa5 in _start ()
```

so my reading is that the xrdcp is exiting, OPENSSL_cleanup gets called, however there is still another thread that is actively using openssl; so after/during the cleanup bad things happen in the thread which is using openssl. I'm trying to see if I can better understand the overall situation; e.g. why the command is exiting.

**Comment by amadio** [comment] 2024-02-01 14:53
I actually managed to reproduce the crash on my machine now:
```
Core was generated by `xrdcp --server -S 1 xroots://gentoo.cern.ch:9091//file.raw /srv/xrootd/tpc1/fil'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __pthread_rwlock_wrlock_full64 (abstime=0x0, clockid=0, rwlock=0x0) at /usr/src/debug/sys-libs/glibc-2.38-r10/glibc-2.38/nptl/pthread_rwlock_common.c:603
603	  if (__glibc_unlikely (atomic_load_relaxed (&rwlock->__data.__cur_writer)
[Current thread is 1 (Thread 0x7fad664006c0 (LWP 3048024))]
(gdb) bt
#0  __pthread_rwlock_wrlock_full64 (abstime=0x0, clockid=0, rwlock=0x0) at /usr/src/debug/sys-libs/glibc-2.38-r10/glibc-2.38/nptl/pthread_rwlock_common.c:603
#1  ___pthread_rwlock_wrlock (rwlock=0x0) at pthread_rwlock_wrlock.c:26
#2  0x00007fad6960a7f0 in CRYPTO_THREAD_write_lock (lock=<optimized out>) at ../openssl-3.1.5/crypto/threads_pthread.c:110
#3  0x00007fad695b3ba6 in ENGINE_pkey_asn1_find_str (pe=pe@entry=0x7fad663ff3d0, str=str@entry=0x7fad50021480 "1.3.101.110", len=len@entry=11) at ../openssl-3.1.5/crypto/engine/tb_asnmth.c:203
#4  0x00007fad694d0701 in EVP_PKEY_asn1_find_str (pe=pe@entry=0x7fad663ff438, str=str@entry=0x7fad50021480 "1.3.101.110", len=len@entry=11) at ../openssl-3.1.5/crypto/asn1/ameth_lib.c:117
#5  0x00007fad695e5e85 in pkey_set_type (pkey=pkey@entry=0x0, e=<optimized out>, e@entry=0x0, type=type@entry=0, str=str@entry=0x7fad50021480 "1.3.101.110", len=11, keymgmt=keymgmt@entry=0x0)
    at ../openssl-3.1.5/crypto/evp/p_lib.c:1539
#6  0x00007fad695e62ff in find_ameth (name=0x7fad50021480 "1.3.101.110", data=0x7fad663ff530) at ../openssl-3.1.5/crypto/evp/p_lib.c:1618
#7  0x00007fad695fa5b6 in ossl_namemap_doall_names (namemap=<optimized out>, number=number@entry=113, fn=fn@entry=0x7fad695e62c5 <find_ameth>, data=data@entry=0x7fad663ff530) at ../openssl-3.1.5/crypto/core_namemap.c:166
#8  0x00007fad695d7a98 in evp_names_do_all (prov=<optimized out>, number=113, fn=fn@entry=0x7fad695e62c5 <find_ameth>, data=data@entry=0x7fad663ff530) at ../openssl-3.1.5/crypto/evp/evp_fetch.c:643
#9  0x00007fad695e0063 in EVP_KEYMGMT_names_do_all (keymgmt=keymgmt@entry=0x7fad500531b0, fn=fn@entry=0x7fad695e62c5 <find_ameth>, data=data@entry=0x7fad663ff530) at ../openssl-3.1.5/crypto/evp/keymgmt_meth.c:292
#10 0x00007fad695e622a in EVP_PKEY_set_type_by_keymgmt (pkey=pkey@entry=0x7fad50104060, keymgmt=0x7fad500531b0) at ../openssl-3.1.5/crypto/evp/p_lib.c:1642
#11 0x00007fad695e74ae in EVP_PKEY_copy_parameters (to=to@entry=0x7fad50104060, from=from@entry=0x7fad50062ed0) at ../openssl-3.1.5/crypto/evp/p_lib.c:155
#12 0x00007fad699e6397 in tls_parse_stoc_key_share (s=0x7fad500febd0, pkt=<optimized out>, context=<optimized out>, x=<optimized out>, chainidx=<optimized out>) at ../openssl-3.1.5/ssl/statem/extensions_clnt.c:1840
#13 0x00007fad699e0f8e in tls_parse_extension (s=s@entry=0x7fad500febd0, idx=idx@entry=TLSEXT_IDX_key_share, context=context@entry=512, exts=exts@entry=0x7fad5006e390, x=x@entry=0x0, chainidx=chainidx@entry=0)
    at ../openssl-3.1.5/ssl/statem/extensions.c:719
#14 0x00007fad699e104b in tls_parse_all_extensions (s=s@entry=0x7fad500febd0, context=context@entry=512, exts=0x7fad5006e390, x=x@entry=0x0, chainidx=chainidx@entry=0, fin=fin@entry=1) at ../openssl-3.1.5/ssl/statem/extensions.c:752
#15 0x00007fad699f29bb in tls_process_server_hello (s=0x7fad500febd0, pkt=<optimized out>) at ../openssl-3.1.5/ssl/statem/statem_clnt.c:1657
#16 0x00007fad699f5714 in ossl_statem_client_process_message (s=0x7fad500febd0, pkt=<optimized out>) at ../openssl-3.1.5/ssl/statem/statem_clnt.c:1027
#17 0x00007fad699eca54 in read_state_machine (s=s@entry=0x7fad500febd0) at ../openssl-3.1.5/ssl/statem/statem.c:647
#18 0x00007fad699ed695 in state_machine (s=0x7fad500febd0, server=server@entry=0) at ../openssl-3.1.5/ssl/statem/statem.c:442
#19 0x00007fad699ed93a in ossl_statem_connect (s=<optimized out>) at ../openssl-3.1.5/ssl/statem/statem.c:265
#20 0x00007fad699bdd91 in SSL_do_handshake (s=s@entry=0x7fad500febd0) at ../openssl-3.1.5/ssl/ssl_lib.c:3957
#21 0x00007fad699bf2c9 in SSL_connect (s=0x7fad500febd0) at ../openssl-3.1.5/ssl/ssl_lib.c:1779
#22 0x00007fad69f3f678 in XrdTlsSocket::Connect (this=0x7fad50114490, thehost=0x7fad500fc4a0 "gentoo.cern.ch", eWhy=eWhy@entry=0x7fad663ff9a0) at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdTls/XrdTlsSocket.cc:275
#23 0x00007fad6a12f00d in XrdCl::Tls::Connect (this=0x7fad500f89d0, thehost="gentoo.cern.ch", netInfo=<optimized out>) at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdCl/XrdClTls.cc:138
#24 0x00007fad6a12bf73 in XrdCl::Socket::TlsHandShake (this=0x7fad50113990, socketHandler=socketHandler@entry=0x7fad500fc330, thehost="gentoo.cern.ch") at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdCl/XrdClSocket.cc:851
#25 0x00007fad6a1c1b71 in XrdCl::AsyncSocketHandler::DoTlsHandShake (this=this@entry=0x7fad500fc330) at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdCl/XrdClAsyncSocketHandler.cc:778
#26 0x00007fad6a1c6531 in XrdCl::AsyncSocketHandler::OnTLSHandShake (this=this@entry=0x7fad500fc330) at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdCl/XrdClAsyncSocketHandler.cc:802
#27 0x00007fad6a1c6dee in XrdCl::AsyncSocketHandler::EventRead (this=this@entry=0x7fad500fc330, type=type@entry=1 '\001') at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdCl/XrdClAsyncSocketHandler.cc:243
#28 0x00007fad6a1c3142 in XrdCl::AsyncSocketHandler::Event (this=0x7fad500fc330, type=1 '\001') at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdCl/XrdClAsyncSocketHandler.cc:224
#29 0x00007fad6a134c81 in (anonymous namespace)::SocketCallBack::Event (this=0x555a65b25240, chP=<optimized out>, cbArg=<optimized out>, evFlags=<optimized out>)
    at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdCl/XrdClPollerBuiltIn.cc:83
#30 0x00007fad69f33974 in XrdSys::IOEvents::Poller::CbkXeq (this=this@entry=0x555a65ac1520, cP=cP@entry=0x7fad500fc560, events=1, eNum=<optimized out>, eTxt=0x0)
    at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdSys/XrdSysIOEvents.cc:721
#31 0x00007fad69f34829 in XrdSys::IOEvents::PollE::Dispatch (this=this@entry=0x555a65ac1520, cP=0x7fad500fc560, pollEv=<optimized out>) at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdSys/XrdSysIOEventsPollE.icc:275
#32 0x00007fad69f34ad7 in XrdSys::IOEvents::PollE::Begin (this=0x555a65ac1520, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>)
    at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdSys/XrdSysIOEventsPollE.icc:230
#33 0x00007fad69f3196d in XrdSys::IOEvents::BootStrap::Start (parg=0x7ffe5fd57380) at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdSys/XrdSysIOEvents.cc:149
#34 0x00007fad69f3915d in XrdSysThread_Xeq (myargs=0x555a65ac5ac0) at /usr/src/debug/net-libs/xrootd-5.6.6/xrootd-5.6.6/src/XrdSys/XrdSysPthread.cc:86
#35 0x00007fad69abb199 in start_thread (arg=<optimized out>) at pthread_create.c:444
#36 0x00007fad69b31998 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by abh3** [comment] 2024-02-01 19:31
Looks like a known issue: https://github.com/openssl/openssl/issues/11144
________________________________

**Closed** 2024-02-06 08:46 UTC
Labels: bug (critical)
