### ISSUE TITLE
Crash XrdCryptoX509Chain::EECname()

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#645] opened 2018-01-16 10:53 UTC
This was submitted to the EOS tracker, I've moved it here as it seems to be a XRootD generic issue:

```c++
Thread 1 (Thread 0x7fccc7893880 (LWP 216)):
#0  0x00007fccc6d2ea0b in do_futex_wait.constprop.1 ()
   from /lib64/libpthread.so.0
#1  0x00007fccc6d2ea9f in __new_sem_wait_slow.constprop.0 ()
   from /lib64/libpthread.so.0
#2  0x00007fccc6d2eb3b in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x000000000040c7f8 in mainAccept(void*) ()
#4  0x00000000004065ad in main ()

#########################################################################
# -----------------------------------------------------------------------
# Responsible thread =>
# -----------------------------------------------------------------------
# Thread 43 (Thread 0x7fc75c4f5700 (LWP 19655)):
#########################################################################
#4  <signal handler called>
#5  0x00007fccbe783dc5 in XrdCryptoX509Chain::EECname() ()
   from /lib64/libXrdCrypto.so.1
#6  0x00007fccbe784af7 in XrdCryptoX509Chain::XrdCryptoX509Chain(XrdCryptoX509Chain*) () from /lib64/libXrdCrypto.so.1
#7  0x00007fccbe99b4ab in XrdSecProtocolgsi::ServerDoCert(XrdSutBuffer*, XrdSutBuffer**, XrdOucString&) () from /lib64/libXrdSecgsi-4.so
#8  0x00007fccbe9a94f5 in XrdSecProtocolgsi::ParseServerInput(XrdSutBuffer*, XrdSutBuffer**, XrdOucString&) () from /lib64/libXrdSecgsi-4.so
#9  0x00007fccbe9a98a6 in XrdSecProtocolgsi::Authenticate(XrdSecBuffer*, XrdSecBuffer**, XrdOucErrInfo*) () from /lib64/libXrdSecgsi-4.so
#10 0x00007fccc7430352 in XrdXrootdProtocol::do_Auth() ()
   from /lib64/libXrdServer.so.2
#11 0x00007fccc71aca78 in XrdLink::DoIt() () from /lib64/libXrdUtils.so.2
#12 0x00007fccc71b000f in XrdScheduler::Run() () from /lib64/libXrdUtils.so.2
#13 0x00007fccc71b0159 in XrdStartWorking(void*) ()
   from /lib64/libXrdUtils.so.2
#14 0x00007fccc716c627 in XrdSysThread_Xeq () from /lib64/libXrdUtils.so.2
#15 0x00007fccc6d28e25 in start_thread () from /lib64/libpthread.so.0
#16 0x00007fccc602e34d in clone () from /lib64/libc.so.6

```

**Comment by gganis** [comment] 2018-02-09 15:18
Hi Elvin,
Which version was this with?
Can you check if with this patch 

https://github.com/xrootd/xrootd/commit/2752b602c0e7d7b2aa8f5117fa1d2c536005a400

the problem is still happening?
Gerri

**Comment by esindril** [comment] 2018-02-12 08:42
Hi Gerri,

The crash happened with 4.7.0. And we haven't seen it with latest 4.8.* so I think you can close it. 
If there is something new I will let you know.

Thanks,
Elvin

**Comment by gganis** [comment] 2018-02-12 10:10
Ok, I close it and we monitor how it goes.
Thank you for the feedback.
Gerri

**Closed by gganis** 2018-02-12 10:10 UTC
