### ISSUE TITLE
xrdcp crash under CRYPTO_THREAD_read_lock 

### ISSUE THREAD

**Issue by jmuf** [xrootd/xrootd#2387] opened 2024-12-12 08:28 UTC
FYI - we've seen 2 `xrdcp` client crashes during a time when the target server was unavailable/very slow (i.e likely to trigger weird timing issues). The client is authenticating via GSI.
```
        Signal: 11 (SEGV)
     Timestamp: Thu 2024-12-12 01:17:09 CET (8h ago)
  Command Line: xrdcp -d 1 -v -f -DIReadCacheSize 0 -DIConnectTimeout 30 -DITransactionTimeout 60 -DIRequestTimeout 60 -DIRedirCntTimeout 60 /tmp/sls-xrdcp-in.2UczeXt0 root://128.142.52.32//eos/project-i02/opstest/slstest-eosproject-i02/test-eosproject-i02.cern.ch-from-eoshomemon01.cern.ch-xrdcp.static
    Executable: /usr/bin/xrdcp
                Stack trace of thread 1000200:
                #0  0x00007f09a2c8f69c pthread_rwlock_rdlock@GLIBC_2.2.5 (libc.so.6 + 0x8f69c)
                #1  0x00007f09a27e105d CRYPTO_THREAD_read_lock (libcrypto.so.3 + 0x1e105d)
                #2  0x00007f09a2806eb8 RAND_get_rand_method (libcrypto.so.3 + 0x206eb8)
                #3  0x00007f09a2807505 RAND_seed (libcrypto.so.3 + 0x207505)
                #4  0x00007f099f3277c7 _ZN19XrdCryptosslFactoryC2Ev (libXrdCryptossl-5.so + 0x247c7)
                #5  0x00007f099f3278b2 XrdCryptosslFactoryObject (libXrdCryptossl-5.so + 0x248b2)
                #6  0x00007f09a2e1b216 _ZN16XrdCryptoFactory16GetCryptoFactoryEPKc (libXrdCrypto.so.2 + 0xf216)
                #7  0x00007f09a2e450c9 _ZN17XrdSecProtocolgsi11ParseCryptoE12XrdOucString (libXrdSecgsi-5.so + 0x1d0c9)
                #8  0x00007f09a2e47286 _ZN17XrdSecProtocolgsi12ClientDoInitEP12XrdSutBufferPS1_R12XrdOucString (libXrdSecgsi-5.so + 0x1f286)
                #9  0x00007f09a2e4894d _ZN17XrdSecProtocolgsi16ParseClientInputEP12XrdSutBufferPS1_R12XrdOucString (libXrdSecgsi-5.so + 0x2094d)
                #10 0x00007f09a2e3a17a _ZN17XrdSecProtocolgsi14getCredentialsEP12XrdSecBufferP13XrdOucErrInfo (libXrdSecgsi-5.so + 0x1217a)
                #11 0x00007f09a351e8ec _ZN5XrdCl15XRootDTransport14GetCredentialsERP12XrdSecBufferPNS_13HandShakeDataEPNS_17XRootDChannelInfoE (libXrdCl.so.3 + 0x11e8ec)
                #12 0x00007f09a35212d5 _ZN5XrdCl15XRootDTransport16DoAuthenticationEPNS_13HandShakeDataEPNS_17XRootDChannelInfoE (libXrdCl.so.3 + 0x1212d5)
                #13 0x00007f09a3514d53 _ZN5XrdCl15XRootDTransport13HandShakeMainEPNS_13HandShakeDataERNS_9AnyObjectE (libXrdCl.so.3 + 0x114d53)
                #14 0x00007f09a351547e _ZN5XrdCl15XRootDTransport9HandShakeEPNS_13HandShakeDataERNS_9AnyObjectE (libXrdCl.so.3 + 0x11547e)
                #15 0x00007f09a3592edb _ZN5XrdCl18AsyncSocketHandler15HandleHandShakeESt10unique_ptrINS_7MessageESt14default_deleteIS2_EE (libXrdCl.so.3 + 0x192edb)
                #16 0x00007f09a359348b _ZN5XrdCl18AsyncSocketHandler22OnReadWhileHandshakingEv (libXrdCl.so.3 + 0x19348b)
                #17 0x00007f09a3593abd _ZN5XrdCl18AsyncSocketHandler5EventEhPNS_6SocketE (libXrdCl.so.3 + 0x193abd)
                #18 0x00007f09a350c86a _ZN12_GLOBAL__N_114SocketCallBack5EventEPN6XrdSys8IOEvents7ChannelEPvi (libXrdCl.so.3 + 0x10c86a)
                #19 0x00007f09a375d8ff _ZN6XrdSys8IOEvents6Poller6CbkXeqEPNS0_7ChannelEiiPKc (libXrdUtils.so.3 + 0x478ff)
                #20 0x00007f09a375dfb0 _ZN6XrdSys8IOEvents5PollE8DispatchEPNS0_7ChannelEj (libXrdUtils.so.3 + 0x47fb0)
                #21 0x00007f09a375e1b8 _ZN6XrdSys8IOEvents5PollE5BeginEP15XrdSysSemaphoreRiPPKc (libXrdUtils.so.3 + 0x481b8)
                #22 0x00007f09a375ad11 _ZN6XrdSys8IOEvents9BootStrap5StartEPv (libXrdUtils.so.3 + 0x44d11)
                #23 0x00007f09a3762afc XrdSysThread_Xeq (libXrdUtils.so.3 + 0x4cafc)
                #24 0x00007f09a2c89d22 start_thread (libc.so.6 + 0x89d22)
                #25 0x00007f09a2d0ed40 __clone3 (libc.so.6 + 0x10ed40)
                
                Stack trace of thread 1000209:
                #0  0x00007f09a2cd4175 clock_nanosleep@GLIBC_2.2.5 (libc.so.6 + 0xd4175)
                #1  0x00007f09a2cd8d87 __nanosleep (libc.so.6 + 0xd8d87)
                #2  0x00007f09a37663c0 _ZN11XrdSysTimer4WaitEi (libXrdUtils.so.3 + 0x503c0)
                #3  0x00007f09a352222d _ZN5XrdCl11TaskManager8RunTasksEv (libXrdCl.so.3 + 0x12222d)
                #4  0x00007f09a352237d RunRunnerThread (libXrdCl.so.3 + 0x12237d)
                #5  0x00007f09a2c89d22 start_thread (libc.so.6 + 0x89d22)
                #6  0x00007f09a2d0ed40 __clone3 (libc.so.6 + 0x10ed40)
                
                Stack trace of thread 1000198:
                #0  0x00007f09a2c868ba __futex_abstimed_wait_common (libc.so.6 + 0x868ba)
                #1  0x00007f09a2c91d68 __new_sem_wait_slow64.constprop.0 (libc.so.6 + 0x91d68)
                #2  0x00007f09a375e78e _ZN6XrdSys8IOEvents6Poller7SendCmdERNS1_8PipeDataE (libXrdUtils.so.3 + 0x4878e)
                #3  0x00007f09a375e843 _ZN6XrdSys8IOEvents6Poller4StopEv (libXrdUtils.so.3 + 0x48843)
                #4  0x00007f09a350bb69 _ZN5XrdCl13PollerBuiltIn4StopEv (libXrdCl.so.3 + 0x10bb69)
                #5  0x00007f09a350d74e _ZN5XrdCl10PostMaster4StopEv (libXrdCl.so.3 + 0x10d74e)
                #6  0x00007f09a3505aa2 _ZN5XrdCl10DefaultEnv8FinalizeEv (libXrdCl.so.3 + 0x105aa2)
                #7  0x00007f09a3505df1 _ZN14EnvInitializerD1Ev (libXrdCl.so.3 + 0x105df1)
                #8  0x00007f09a2c412e7 __cxa_finalize (libc.so.6 + 0x412e7)
                #9  0x00007f09a34ed687 __do_global_dtors_aux (libXrdCl.so.3 + 0xed687)
                #10 0x00007f09a38592ce _dl_fini (ld-linux-x86-64.so.2 + 0x52ce)
                #11 0x00007f09a2c40e2d __run_exit_handlers (libc.so.6 + 0x40e2d)
                #12 0x00007f09a2c40f70 exit (libc.so.6 + 0x40f70)
                #13 0x00007f09a2c295d7 __libc_start_call_main (libc.so.6 + 0x295d7)
                #14 0x00007f09a2c29680 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x29680)
                #15 0x000055b8477d5af5 _start (xrdcp + 0xdaf5)
                
                Stack trace of thread 1000199:
                #0  0x00007f09a2d0e37e epoll_wait (libc.so.6 + 0x10e37e)
                #1  0x00007f09a375e154 _ZN6XrdSys8IOEvents5PollE5BeginEP15XrdSysSemaphoreRiPPKc (libXrdUtils.so.3 + 0x48154)
                #2  0x00007f09a375ad11 _ZN6XrdSys8IOEvents9BootStrap5StartEPv (libXrdUtils.so.3 + 0x44d11)
                #3  0x00007f09a3762afc XrdSysThread_Xeq (libXrdUtils.so.3 + 0x4cafc)
                #4  0x00007f09a2c89d22 start_thread (libc.so.6 + 0x89d22)
                #5  0x00007f09a2d0ed40 __clone3 (libc.so.6 + 0x10ed40)
                ELF object binary architecture: AMD x86-64
```

Version: xrootd-client-5.6.9-1.el9.x86_64

**Comment by amadio** [comment] 2024-12-12 08:32
Duplicate of #2164, fixed by https://github.com/xrootd/xrootd/commit/3c21b23a8929040dc432aa6944e8678395e2367b in v5.7.0. Please upgrade.

**Closed by amadio** 2024-12-12 08:32 UTC
Labels: duplicate
