### ISSUE TITLE
Bug in (tcp?) connection handling

### ISSUE THREAD

**Issue by rob-c** [xrootd/xrootd#1266] opened 2020-07-30 16:57 UTC
As per discussions on #1251 there is a connection bug in xrootd impacting storage at ECDF.

GGUS:   https://ggus.eu/index.php?mode=ticket_info&ticket_id=146771

The key part of the bug here is that xrootd will reach a state where a growing large percentage of connections will fail with a connection reset.

We observe that this bug happens a lot less when we have deactivated an external tcp probe of the xrootd service.
(There are functional tests that others run, as a site admin I just care if xrootd has crashed)

The tcp probe we're using on an external host is the tcp probe within blackbox_exporter:   https://github.com/prometheus/blackbox_exporter

(Aside:
The xrootd service which fails is configured as part of DPM and has both xrootd and http on at the same time. xrootd protocol being used to serve data and the http side parsing/sending DPM-DOME commands.)

After some period of time the problem presents itself such that a curl against the service will receive a connection reset rather than a reply:
```
[root@pool7 ~]# curl -vvvk localhost:1095
* About to connect() to localhost port 1095 (#0)
* Trying ::1...
* Connected to localhost (::1) port 1095 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:1095
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
[root@pool7 ~]# curl -vvvk localhost:1095
* About to connect() to localhost port 1095 (#0)
* Trying ::1...
* Connected to localhost (::1) port 1095 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:1095
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

From the xrootd logs the error presents itself as the following:
```
200727 18:38:30 4359 XrdAccept: Unable to allocate new link for srm.glite.ecdf.ed.ac.uk; cannot allocate memory
200727 18:38:47 8213 XrdLink: attempt to reuse active link
200727 18:38:47 8213 XrdAccept: Unable to allocate new link for srm.glite.ecdf.ed.ac.uk; cannot allocate memory
200727 18:39:10 8225 cms_Finder: Waiting for cms path /var/spool/xrootd/dpmdisk/.olb/olbd.admin
200727 18:39:31 8213 XrdLink: attempt to reuse active link
200727 18:39:31 8213 XrdAccept: Unable to allocate new link for srm.glite.ecdf.ed.ac.uk; cannot allocate memory
200727 18:39:48 8213 XrdLink: attempt to reuse active link
200727 18:39:48 8213 XrdAccept: Unable to allocate new link for srm.glite.ecdf.ed.ac.uk; cannot allocate memory
200727 18:40:20 8225 cms_Finder: Waiting for cms path /var/spool/xrootd/dpmdisk/.olb/olbd.admin
200727 18:40:49 8813 XrdLink: attempt to reuse active link
```

It has been suggested that this could be a malloc related problem, unfortunately on both machines there are several Gb of free RAM and no anomalously high load which could suggest the RAM being constantly allocated/deallocated.

This has been observed on a system using glibc-malloc as well as a system running xrootd with tcmalloc. It is possible this could be fixed by switching to jemalloc which hasn't been tested. This has been observed on 3 of our newer CentOS7 storage deployments.

We've mitigated this for the time being by not using the above tcp probe. Since then the xrootd services on our storage nodes have not had to restart for a few days.

**Comment by abh3** [comment] 2020-07-30 19:49
Could you send you config file? There is an obvious issue since the message

cms_Finder: Waiting for cms path /var/spool/xrootd/dpmdisk/.olb/olbd.admin

should not be there if this is a DPM setup as you would not be using native xrootd clustering. So, there may be other issues and I want to make sure that this is not a config problem. Also, what release are you using?

**Comment by bbockelm** [comment] 2020-07-30 21:02
> It has been suggested that this could be a malloc related problem, unfortunately on both machines there are several Gb of free RAM and no anomalously high load which could suggest the RAM being constantly allocated/deallocated.

Luckily, there is about a 0% chance this is the issue.  That reference to out-of-memory happens for _any_ error generated by the prior function.  This is the real issue:

```
200727 18:39:31 8213 XrdLink: attempt to reuse active link
```

Your hint about the TCP probe is perhaps a good place to start.  What's the maximum number of file descriptors set for `xrootd` (look at `/proc/$PID/limits`)?  I wonder if something is churning through FDs rapidly...

**Comment by abh3** [comment] 2020-07-31 00:00
Indeed, something is amiss. I checked the code. As Brian points out, the "memory" error is misleading and we will substitute something better. Indeed, the error is that the incoming file descriptor is still assigned to an existing socket. The code doesn't appear to have any race conditions. There are two "close socket" paths but both appear to hold on to the file descriptor while the file descriptor is unassigned and only then closes the socket to free up the file descriptor. So, the question is why is accept() returning a file descriptor that is ostensibly still in use. 

Still outstanding: a) what version of xrootd are you using? b) could you provide access to the config file (likely a bad idea to post it here), c) what is the file descriptor limit for the process, d) is this running in a container, vm, or bare hardware? We really need this information to start diagnosing the issue and will likely have follow-up questions.

**Comment by rob-c** [comment] 2020-07-31 11:11
Hi,

This error has been verified at least in xrootd 4.11.3 and I suspect it's also in 4.12.3 as we were seeing the same problem when debugging something else.

The problem has been verified on both our head-node (VM hosted on a libvirtd+CentOS8 host) and on a bare metal `Dell Inc. PowerEdge R510` both running CentOS7.8
Unfortunately the problem of connection resets happens for both local and remote connections to the same service which rules out most of the kernel settings I would normally check.

```
[root@srm ~]# cat /proc/`pidof xrootd`/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             30000                128301               processes
Max open files            65536                65536                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       128301               128301               signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

Additionally the following have been set in the override.conf (probably unrelated but for sake of clarity):
```
Environment=MALLOC_ARENA_MAX=4
Environment=XRD_MAXREDIRECTCOUNT=1

LimitCORE=infinity
Environment=DAEMON_COREFILE_LIMIT=unlimited
```

I've attached the xrootd config (minus-secrets) from one of the disk nodes (bare metal) which have had this problem.
Unfortunately this is as deployed by puppet for DPM modulo some reduction in whitespace.
[xrootd.cfg.txt](https://github.com/xrootd/xrootd/files/5006696/xrootd.cfg.txt)

**Comment by bbockelm** [comment] 2020-07-31 18:53
Shoot, I was hoping something would jump out in the max open files or processes.  Those settings look reasonable.  Maybe Andy will spot something in the config file?

**Comment by abh3** [comment] 2020-11-13 10:35
Is this still an issue? It might not be as the complaints have not mounted! Unless I hear otherwise, I will close this ticket within a week.

**Comment by abh3** [comment] 2020-11-20 00:42
OK, I am closing this issue as I have not heard any response. We could not reproduce it here. According to the code, the only way this could happen is if the socket were closed by an external party and the server still thinks this is an active socket but is being used for a new connection.

**Closed by abh3** 2020-11-20 00:42 UTC
