### ISSUE TITLE
Fstream operation time

### ISSUE THREAD

**Issue by biozit** [xrootd/xrootd#1988] opened 2023-04-04 19:48 UTC
Hi All, 

   Please, can the operation time be 0 with a file of ~ 4GB?

{
  "_index": "monit_prod_cms_raw_aaa-ng-2023-04-04",
  "_id": "c76882fe-b57b-4835-bc57-eca9fe16b7a2",
  "_version": 1,
  "_score": null,
  "_source": {
    "data": {
      "site_name": "T2_US_Florida",
      "fallback": true,
      "user_dn": "",
      "client_host": "st-096-dd904d00.cern.ch",
      "client_domain": "cern.ch",
      "server_host": "cmsio6.rc.ufl.edu",
      "server_domain": "ufl.edu",
      "server_ip": "2620:104:1f:1000:92e2:baff:fe2b:9538",
      "unique_id": "c76882fe-b57b-4835-bc57-eca9fe16b7a2",
      "file_lfn": "/store/data/Run2022C/EGamma/ALCARECO/HcalCalIterativePhiSym-10Dec2022-v1/2810000/93f1a566-e2a2-4d2b-bb54-d62b8e72a96e.root",
      "file_size": 4255943309,
      "read_bytes": 4255943309,
      "read_single_bytes": 4255943309,
      "read_vector_bytes": 0,
      "ipv6": true,
      "start_time": 1680637218000,
      "end_time": 1680637218000,
      "operation_time": 0,
      "operation": "read",
      "server_site": "T2_US_Florida",
      "user_protocol": "https",
      "write_bytes": 0,
      "read_average": 1048520.1549642769,
      "read_bytes_at_close": 4255943309,
      "read_max": 1048576,
      "read_min": 0,
      "read_operations": 4059,
      "read_sigma": 0,
      "read_single_average": 1048520.1549642769,
      "read_single_max": 1048576,
      "read_single_min": 821901,
      "read_single_operations": 4059,
      "read_single_sigma": 0,
      "read_vector_average": 0,
      "read_vector_count_average": 0,
      "read_vector_count_max": 0,
      "read_vector_count_min": 0,
      "read_vector_count_sigma": 0,
      "read_vector_max": 0,
      "read_vector_min": 0,
      "read_vector_operations": 0,
      "read_vector_sigma": 0,
      "throughput": 0,
      "write_average": 0,
      "write_bytes_at_close": 0,
      "write_max": 0,
      "write_min": 0,
      "write_operations": 0,
      "write_sigma": 0,
      "metadata": {}
    },
    "metadata": {
      "hostname": "monit-amqsource-13198c030f.cern.ch",
      "partition": "1",
      "type_prefix": "raw",
      "kafka_timestamp": 1680637278978,
      "host": "xrootd-mon-collector-bb4cb9cb9-2t7lc",
      "topic": "cms_raw_aaa-ng",
      "producer": "cms",
      "_id": "c76882fe-b57b-4835-bc57-eca9fe16b7a2",
      "type": "aaa-ng",
      "timestamp": 1680637278402
    }
  },
  "fields": {
    "metadata.kafka_timestamp": [
      "2023-04-04T19:41:18.978Z"
    ],
    "metadata.timestamp": [
      "2023-04-04T19:41:18.402Z"
    ]
  },
  "sort": [
    1680637278402,
    4255943309
  ]
}

**Comment by bbockelm** [comment] 2023-04-04 20:18
Hi @biozit -

This appears to be what occurs when the collector sees a file close record but not a file open record:

https://github.com/opensciencegrid/xrootd-monitoring-collector/blob/master/Collectors/DetailedCollector.py#L507-L517

So, where'd the file open record go?

**Comment by biozit** [comment] 2023-04-04 20:37
Hi @bbockelm 

  Good catch! Probably the collector lost a few UDP pkgs. We do have a shoveler, and this kind of thing should be small. I will check this Collector.

**Comment by osschar** [comment] 2023-04-04 20:44
It stayed in Florida?

It might make more sense to either drop such packets or add a field saying does-not-have-open-record so one can filter them out without throwing away actual really brief file accesses.

i-th record should also really have time t_i = t_beg + i*(t_end - t_beg)/(N - 1)

**Comment by biozit** [comment] 2023-04-04 20:47
Ops, wrong button!

Let me check the installation, and I will check about creating a new field on the collector.

**Comment by biozit** [comment] 2023-04-20 00:46
I created a "debug" field on the collector to show when it lost the "file to close" the stream below shows the file open and close (file_close_found": 1), and the operation time is 0. 

`{"timestamp": 1681846060000, "start_time": 1681846060000, "end_time": 1681846060000, "file_close_found": 1, "operation_time": 0, "server_hostname": "10.244.112.250", "server_ip": "10.244.112.250", "server": "10.244.112.250", "user": "fandri", "host": "login05.osgconnect.net", "user_domain": "osgconnect.net", "protocol": "xroot", "ipv6": false, "filename": "/osdftest/test667", "filesize": 2000000000, "dirname1": "/osdftest", "dirname2": "/osdftest/test667", "logical_dirname": "unknown directory", "read": 498439168, "readv": 0, "write": 0, "read_average": 8307319.466666667, "read_bytes_at_close": 498439168, "read_max": 0, "read_min": 0, "read_operations": 60, "read_single_average": 8307319.466666667, "read_single_bytes": 498439168, "read_single_max": 0, "read_single_min": 2147483647, "read_single_operations": 60, "read_vector_average": 0, "read_vector_count_average": 0, "read_vector_count_max": 0, "read_vector_count_min": 0, "read_vector_max": 0, "read_vector_min": 0, "read_vector_operations": 0, "throughput": 0, "write_average": 0, "write_bytes_at_close": 0, "write_max": 0, "write_min": 0, "write_operations": 0}`

**Comment by KatyEllis** [comment] 2023-04-21 12:56
So are Shoveler developers concerned by this or not? Does this zero operation_time not affect plots of rates/throughput?
@djw8605

**Comment by xrootd-dev** [comment] 2023-04-21 21:21
Indeed they are and will be tracking down where this occurs. At least 
that's how we left it at our Thursday meeting.

**Comment by biozit** [comment] 2023-05-03 21:08
Hi all,

  I have been trying to find the source of this problem, here are some facts:

 - On the XrootD Monitoring collector, there is no time "creating". All the time is from XrootD
 - The Open and close are here: XrdClFileStateHandler.cc, the open time is on a var called pOpenTime and the close is handled inside a struct XrdClFileStateHandler.cc:3204, Why is that? is not better to set the openTime here (in this srtuct) https://github.com/xrootd/xrootd/blob/25f83842def6df191ea9b7e1bea6319c75c87d91/src/XrdCl/XrdClFileStateHandler.cc#L2433?
 - There just a few of file_close_found": 0, in other words, there is just a few cases where there is no open withtout close (less than 1%). 
 
 Any pointers @djw8605 @abh3 @bbockelm  ?

**Comment by xrootd-dev** [comment] 2023-05-03 21:53
What happens in the client is immaterial to the fstream. The servers sets 
the time of the open and the close. So, the pointer here, as we discussed, 
is to track how this is actually handled in the collector (I think we 
absolved the shoveler). For instance, what would happen is either the open 
or close record were missing.

Andy

**Comment by biozit** [comment] 2023-05-03 22:04
On the collector:

 - if the Open event is missing, we mark the entry and set the start and end time the same:
    - https://github.com/biozit/xrootd-monitoring-collector/blob/7c8a738f9faea1a7e0766d07c87081e7d9982271/Collectors/DetailedCollector.py#L521
    - https://github.com/biozit/xrootd-monitoring-collector/blob/7c8a738f9faea1a7e0766d07c87081e7d9982271/Collectors/DetailedCollector.py#L95
    
    
 - if close is missing, the entry stays on the dict

We are marking the record with Open event missing, that could be a pkg drop or somehting, but this case is very rare. The most comom case is when we have the Open and the close event, but the open time and the close time are the same. The open time and close time are both on the past.

**Comment by xrootd-dev** [comment] 2023-05-03 23:04
As a reality check -- how much data was claimed to have been read by this 
zero time action?

**Comment by biozit** [comment] 2023-05-03 23:18
2GB, but it happens with other file sizes, such as 10GB files

**Comment by abh3** [comment] 2023-05-03 23:35
OK, I have no explanation at the moment. One would have to actually capture the original binary fstream records to verify that start and end times were the same. Then we would know where the problem is.

**Comment by biozit** [comment] 2023-05-04 05:13
Sure, let me get this!

**Comment by biozit** [comment] 2023-05-04 23:52
I instrumented the funtion XrdXrootdMonFile::Flush() to show the the repTOD->tBeg and instrumented the Collector to show this time received and with operation is related to that timestamp. 

[fandri@login05 ~]$ xrdcopy -f root://singapore.nationalresearchplatform.org:1094//osdftest/test661 .
[1000MB/1000MB][100%][==================================================][166.7MB/s]  


The data from the XrootD (it was just one):

 timeEND 1683243738
 timeBeg 1683243704
 
 On the Collector:
 
 2023-05-04 23:42:18,835 - 485690 - DetailedCollector.stdout - DEBUG - OPEN --------------------------  aaaaaaaaaaaaaaaaaaaaaaaa **1683243704**
2023-05-04 23:42:18,835 - 485690 - DetailedCollector - DEBUG - 0 fileOpen(rectype=1, recFlag=1, recSize=44, fileID=34, fileSize=1048576000, userID=33, fileName=b'/osdftest/test661')

2023-05-04 23:42:18,835 - 485690 - DetailedCollector.stdout - DEBUG - CLOSE --------------------------  aaaaaaaaaaaaaaaaaaaaaaaa **1683243704**
2023-05-04 23:42:18,835 - 485690 - DetailedCollector - DEBUG - OSG record to send: {'timestamp': **1683243704000**, 'start_time': **1683243704000**, 'end_time': **1683243704000**, '


Another case:


[fandri@login05 ~]$ xrdcopy -f root://singapore.nationalresearchplatform.org:1094//osdftest/test661 .
[1000MB/1000MB][100%][==================================================][166.7MB/s]  


Collector:

2023-05-04 23:51:17,228 - 485690 - DetailedCollector.stdout - DEBUG - OPEN --------------------------  aaaaaaaaaaaaaaaaaaaaaaaa **1683244226**
2023-05-04 23:51:17,229 - 485690 - DetailedCollector.stdout - DEBUG - CLOSE --------------------------  aaaaaaaaaaaaaaaaaaaaaaaa **1683244226**


Xrootd:


  timeEND 1683244277
 timeBeg **1683244226**

**Comment by xrootd-dev** [comment] 2023-05-05 03:27
So, it would appear that the collector is doing something strange. Do you 
agree?

**Comment by biozit** [comment] 2023-05-05 03:32
I am not sure yet. I think the XrootD is sending only one timestamp for the FileOpen and for the FileClose. 

2023-05-04 23:42:18,835 - 485690 - DetailedCollector.stdout - DEBUG - OPEN -------------------------- aaaaaaaaaaaaaaaaaaaaaaaa 1683243704
2023-05-04 23:42:18,835 - 485690 - DetailedCollector - DEBUG - 0 fileOpen(rectype=1, recFlag=1, recSize=44, fileID=34, fileSize=1048576000, userID=33, fileName=b'/osdftest/test661')

2023-05-04 23:42:18,835 - 485690 - DetailedCollector.stdout - DEBUG - CLOSE -------------------------- aaaaaaaaaaaaaaaaaaaaaaaa 1683243704

What do you think @djw8605 ?

**Comment by xrootd-dev** [comment] 2023-05-05 03:47
Didn't print the record field that contained the timestamp that was sent 
out?

**Comment by biozit** [comment] 2023-05-05 03:54
Derek told me, if I got it right, each "record" send a timestamp. This "record" could be a fileOpen, fileClose, user info and other things.

 This case, show one timestemp for the fileOpen and fileClose (disregard the 000).

PS: who is xrootd-dev?

**Comment by abh3** [comment] 2023-05-05 04:26
Then what does this mean:

The data from the XrootD (it was just one):

  timeEND 1683243738
  timeBeg 1683243704

Where dd the end come from?

Andy

**Comment by xrootd-dev** [comment] 2023-05-05 23:12
OK, so my assumption is that at the point you indicated you print out
repTOD->tBeg and repTOD->tEnd and if that is the case then you displayed 
that they were never the same based on my view of the output. Right?

These are the values that are sent to the recipient.

**Comment by biozit** [comment] 2023-05-05 23:36
Hi, not exactly. I printed the tBeg and tEnd. However, xrootd sends only one of those.

**Comment by abh3** [comment] 2023-05-06 00:54
Well, that's not really true. I have a feeling there is a misunderstanding 
of the documentation:
https://xrootd.slac.stanford.edu/doc/dev55/xrd_monitoring.htm#_Toc99653755

Note that the following timing structure is always sent in each packet:

struct XrdXrootdMonFileTOD
{
XrdXrootdMonFileHdr Hdr;   // recType == isTime
int                 tBeg;  // time(0) of following record
int                 tEnd;  // time(0) when packet was sent
kXR_int64           sID;   // Server identifier lower 48 bits
};

So, tBeg &and* tEnd are always sent that this established the time window 
of the packet. So, you mant to print both of those just before the packet 
is sent out.

**Comment by abh3** [comment] 2023-10-12 11:41
I think this problem is now understood and mitigations have been implemented so I am closing this ticket.

**Closed by abh3** 2023-10-12 11:41 UTC
Labels: Discussion
