### ISSUE TITLE
Some HTTP `Range` requests fail with `Read vector is too long`

### ISSUE THREAD

**Issue by masonproffitt** [xrootd/xrootd#1976] opened 2023-03-23 20:24 UTC
The log file below shows what I'm trying to do, including the HTTP request headers. It seems that when the sum of the byte ranges requested in `Range` gets long enough, there's a `Read vector is too long` error that gets propagated as a `500 Internal Server Error`. This is quite surprising, as the total data requested here is not particularly large at all (130 MiB).

```
230323 20:08:36 3065540 http_Protocol:  rc:81 got hdr line: GET //home/mproffit/iris/tmp/00DF0A73-17C2-E511-B086-E41D2D08DE30.root HTTP/1.1^M

230323 20:08:36 3065540 http_Protocol:  Parsing first line: GET //home/mproffit/iris/tmp/00DF0A73-17C2-E511-B086-E41D2D08DE30.root HTTP/1.1^M

230323 20:08:36 3065540 http_Protocol:  rc:22 got hdr line: Host: localhost:1094^M

230323 20:08:36 3065540 http_Protocol:  rc:27 got hdr line: Accept-Encoding: identity^M

230323 20:08:36 3065540 http_Protocol:  rc:136 got hdr line: Range: bytes=53445211-77058188, 77130795-100499541, 100572148-124999036, 125071643-148689343, 148761950-170010705, 170083313-190163055^M

230323 20:08:36 3065540 http_Protocol:  rc:2 got hdr line: ^M

230323 20:08:36 3065540 http_Protocol:  rc:2 detected header end.
230323 20:08:36 3065540 XrootdBridge: unknown.7:22@localhost login as nobody
230323 20:08:36 3065540 unknown.7:22@localhost http_Protocol:  Process. lp:0x7fb80c0051b8 reqstate: 0
230323 20:08:36 3065540 unknown.7:22@localhost XrootdProtocol: 0000 Bridge req=3017 dlen=67 blen=67
230323 20:08:36 3065540 unknown.7:22@localhost http_Protocol: Process is exiting rc:0
230323 20:08:36 3065540 unknown.7:22@localhost XrootdProtocol: 0000 rc=0 stat /home/mproffit/iris/tmp/00DF0A73-17C2-E511-B086-E41D2D08DE30.root
230323 20:08:36 3065540 unknown.7:22@localhost XrootdResponse: 0000 sending 88 data bytes
230323 20:08:36 3065540 http_Req:  XrdHttpReq::Data! final=False
230323 20:08:36 3065540 unknown.7:22@localhost http_Req: PostProcessHTTPReq req: 2 reqstate: 0
230323 20:08:36 3065540 unknown.7:22@localhost http_Req: Stat for GET /home/mproffit/iris/tmp/00DF0A73-17C2-E511-B086-E41D2D08DE30.root stat=243313213033154561 212708063 48 1679595730 1679595730 1679595722 0644 mproffit mproffit
230323 20:08:36 3065540 unknown.7:22@localhost http_Protocol:  Process. lp:(nil) reqstate: 0
230323 20:08:36 3065540 unknown.7:22@localhost XrootdProtocol: 0000 Bridge req=3010 dlen=67 blen=67
230323 20:08:36 3065540 unknown.7:22@localhost http_Protocol: Process is exiting rc:0
230323 20:08:36 3065540 unknown.7:22@localhost XrootdProtocol: 0000 open rt //home/mproffit/iris/tmp/00DF0A73-17C2-E511-B086-E41D2D08DE30.root
230323 20:08:36 3065540 unknown.7:22@localhost XrootdResponse: 0000 sending 100 data bytes; status=0
230323 20:08:36 3065540 http_Req:  XrdHttpReq::Data! final=True
230323 20:08:36 3065540 unknown.7:22@localhost http_Req: PostProcessHTTPReq req: 2 reqstate: 1
230323 20:08:36 3065540 unknown.7:22@localhost http_Req: fhandle:0:0:0:0
230323 20:08:36 3065540 unknown.7:22@localhost http_Protocol: Sending resp: 206 header len:159
230323 20:08:36 3065540 http_Protocol: Sending 159 bytes
230323 20:08:36 3065540 unknown.7:22@localhost http_Protocol:  Process. lp:(nil) reqstate: 1
230323 20:08:36 3065540 unknown.7:22@localhost XrootdProtocol: 0000 Bridge req=3025 dlen=16720 blen=16720
230323 20:08:36 3065540 unknown.7:22@localhost http_Protocol: Process is exiting rc:0
230323 20:08:36 3065540 unknown.7:22@localhost XrootdResponse: 0000 sending err 3002: Read vector is too long
230323 20:08:36 3065540 http_Req:  XrdHttpReq::Error
230323 20:08:36 3065540 unknown.7:22@localhost http_Req: PostProcessHTTPReq req: 2 reqstate: 2
230323 20:08:36 3065540 unknown.7:22@localhost http_Req: PostProcessHTTPReq mapping Xrd error [3002] to status code [500]
230323 20:08:36 3065540 unknown.7:22@localhost http_Protocol: Sending resp: 500 header len:100
230323 20:08:36 3065540 http_Protocol: Sending 100 bytes
230323 20:08:36 3065540 http_Protocol: Sending 24 bytes
230323 20:08:36 3065540 http_Req:  XrdHttpReq request ended.
230323 20:08:36 3065540 http_Protocol:  Cleanup
230323 20:08:36 3065540 http_Protocol:  Reset
230323 20:08:36 3065540 http_Req:  XrdHttpReq request ended.
230323 20:08:36 3065540 XrootdXeq: unknown.7:22@localhost disc 0:00:00 (send failure)
```

This is with XRootD v5.5.3. I first saw this on the UNL server and then tested that I could reproduce it locally.

**Comment by abh3** [comment] 2023-03-23 20:33
How many byte ranges did you specify? The server has a maximum limit of no 
more than 1024 elements (i.e. byte ranges).

**Comment by masonproffitt** [comment] 2023-03-23 20:36
In this case, it's just those six ranges that you can see in the headers from that log output.

**Comment by ffurano** [comment] 2023-06-05 15:50
AFAIR the max vector chunk sizes come from the xrootd protocol, and the HTTP code tries to fit the more
liberal HTTP specs into that, limiting the overhead. I am puzzled by the idea to work around the vector size limitations imposed (and well documented) by the xrootd protocol

Which client is generating these requests? I don't think that a vector read makes too much sense for large chunks

**Comment by ccaffy** [comment] 2023-06-05 15:58
> AFAIR the max vector chunk sizes come from the xrootd protocol, and the HTTP code tries to fit the more liberal HTTP specs into that, limiting the overhead. I am puzzled by the idea to work around the vector size limitations imposed (and well documented) by the xrootd protocol
> 
> Which client is generating these requests? I don't think that a vector read makes too much sense for large chunks

That's correct, that's why I'm asking what is wrong with the algorithm : its behavior, or its shape? Thanks for your comment @ffurano !

**Comment by abh3** [comment] 2023-06-05 16:13
This comes from @bbockelm comment that the code breaks up the vector read into 128KB chunks which is far smaller than what the server allows. The maximum read per element is 2MB-16 which comes from the largest buffer allowed less the vector read header length that is echoed back in the response. So, the complaint is that 128KB is arbitrary and far too small for certain reads, especially ones that come from Xcache. So, the question iis why that value was chosen and what should the blocking length be? Finally, at some point the http side should simply not use vector read if the range length is greater than some size but what should that be?

**Comment by ccaffy** [comment] 2023-06-06 07:07
> This comes from @bbockelm comment that the code breaks up the vector read into 128KB chunks which is far smaller than what the server allows. The maximum read per element is 2MB-16 which comes from the largest buffer allowed less the vector read header length that is echoed back in the response. So, the complaint is that 128KB is arbitrary and far too small for certain reads, especially ones that come from Xcache. So, the question iis why that value was chosen and what should the blocking length be? Finally, at some point the http side should simply not use vector read if the range length is greater than some size but what should that be?

Thanks for your reply. I now understand what the problem is. It's the fact that 128KB is too small. The maximum read per element comes from the size of the buffer, which now is configurable via `maxbsz`  It can be between 2Mb to 1Gb. So I believe I can take this number - 16?

**Comment by abh3** [comment] 2023-06-06 13:47
No, that is not the solution and that value should not change. It is set to that value for a very critical reason and changing it would cause a number of really more serious issues. The 2MB default is calculated to be the best value for most cases. The correct solution is to fix this on he http side. This is an HTTP side problem not a server side problem. In fact a read element can be 2MB-now but the http side insists on 128KB which is here the problem comes from. Also, mind you the value for xrd.buffers you saw is specific to EOS the common use case is much smaller and changing it has very serious side-effects outside of EOS. Why don't we discuss this when I am at CERN next week.

**Comment by ccaffy** [comment] 2023-06-06 13:58
OK thanks for your additional input. I will put 2MB-16 for now on the HTTP side and push something to a specific branch from which we can talk about next week when you are at CERN ;)

Thanks and see you next week!

**Comment by bbockelm** [comment] 2023-06-06 16:29
Sorry for being terse on the original comment -- sometimes I have to squeeze these thoughts between other duties.

My insight is the problem is because we try and execute the HTTP response as part of a single vector IO request to the XRootD layer.  There's no need for that!  For example, when we read the whole file, we simply repeat 128KB (non-vector) read requests to XRootD until we get to the end of the file.  There's no need to have a 1-to-1 relationship; it can be 1-to-N.

We can do the same thing here:
1.  Based on the remaining, unfilled HTTP range requests, create a vector read that is no more than 1024 xrootd requests.  You can even keep the current size limits of 128kb (or pick any arbitrary size limit that Andy thinks would align well).
      - May be a good idea to keep a queue-like structure of unfilled range request so you're simply popping things off the queue.
3.  Issue the vector read, push the data down the socket.
4. If there's remaining data requested by the client, go back to 1.  Repeat until all requested data is sent.

@ccaffy, if you want to tackle this, I'd suggest taking a look at https://github.com/xrootd/xrootd/pull/1957/commits/36df693600a5bb9d98a2421ad239115aefdf9dad; ignore the new feature that was working on but I'd suggest copying the cleanup of the state machine into a standalone commit, then try to build the above algorithm on the cleaner state machine.

**Comment by ccaffy** [comment] 2023-06-07 07:17
Thanks @bbockelm for your idea! I like it :)
So I'll first push the refactoring of the user-provided range requests that I did (and unit-tested) and I will try to integrate the cleanup of the state machine in a separate commit.

**Comment by smithdh** [comment] 2023-09-20 08:13
hello @masonproffitt , this should be fixed in xrootd release 5.6.2 and later. I checked that similar requests to what you describe are now working, but I was wondering if you would like to check with your application, if you have opportunity; probably we'll close this ticket soon if this appears solved. Thank you for your original report!

**Comment by amadio** [comment] 2023-09-21 04:51
Fixed in #2072.

**Closed by amadio** 2023-09-21 04:51 UTC
Labels: enhancement, bug (non-critical)

**Comment by amadio** [comment] 2023-09-21 20:18
@masonproffitt Did you try your test against a server running XRootD 5.6.2?

**Comment by masonproffitt** [comment] 2023-09-21 22:54
Yes, I was running the 5.6.2 server executable, but I see what happened now. My config file was pointing to an old version of the `XrdHttp` library. It works correctly after updating the config file.

**Comment by amadio** [comment] 2023-09-23 10:23
@masonproffitt I see. Good to know that the fix works as expected. Thank you!
