### ISSUE TITLE
Segfault in XrdSecProtocolgsi::AuthzFunCheck() if AuthzFun fails

### ISSUE THREAD

**Issue by jthiltges** [xrootd/xrootd#595] opened 2017-10-02 21:05 UTC
After updating from xrootd 4.6 to 4.7.0, a site using GSI authentication with LCMAPS and GUMS reported xrootd segfaults:

```
Program terminated with signal 11, Segmentation fault.
#0  AuthzFunCheck (this=0x7f2fe4002560, cred=<value optimized out>, parms=0x7f30497ff588, ei=0x7f30497ff590) at /usr/src/debug/xrootd-4.7.0/src/XrdSecgsi/XrdSecProtocolgsi.cc:1558
```
Source line: https://github.com/xrootd/xrootd/blob/771dbc31b2/src/XrdSecgsi/XrdSecProtocolgsi.cc#L1558

Looking at the core file, the variable notafter (e->buf2.buf) was null, and accessing the null pointer triggered the segfault:

    (gdb) info locals
    expired = false
    notafter = <error reading variable notafter (Cannot access memory at address 0x0)>
    st_ref = 2
    ts_ref = 1506456799
    to_ref = 43200
    st_exp = -1 

My guess as to what's happening in XrdSecProtocolgsi::Authenticate():
buf2 is [free()d](https://github.com/xrootd/xrootd/blob/771dbc31b21f1312fa6a95d8ffb7eb983d3cf1a2/src/XrdSecgsi/XrdSecProtocolgsi.cc#L1869) and then there happens to be a failure in the [AuthzFun LCMAPS callout](https://github.com/xrootd/xrootd/blob/771dbc31b21f1312fa6a95d8ffb7eb983d3cf1a2/src/XrdSecgsi/XrdSecProtocolgsi.cc#L1873). Authenticate() breaks out of the block and buf2 is never reassigned. A later authorization call with the same DN will retrieve the same cache entry and trigger the segfault in AuthzFunCheck().

This guess is supported by log entries of "ERROR: the authorization plug-in reported a failure for this handshake" shortly before the segfaults.

I'm not sure of the best place to fix it. Maybe just "if (e && e->buf2.buf)" in AuthzFunCheck(), similar to the [recent fix](https://github.com/xrootd/xrootd/commit/771dbc31b2) in QueryProxyCheck()?

**Comment by simonmichal** [comment] 2017-10-04 15:24
Thanks for reporting this issue.

Can you reproduce this issue reliably, and if yes, does reverting to 4.6.1 fixes the problem?
I'm asking because in 4.6.1 we had a very similar statement without any additional guards:
https://github.com/xrootd/xrootd/blob/a9430a260d6e11435ea117918e539525f9700f8d/src/XrdSecgsi/XrdSecProtocolgsi.cc#L1903

**Comment by jthiltges** [comment] 2017-10-04 16:01
I've opened this issue on behalf of CMS site T2_US_Florida. After upgrading to 4.7.0, they reported frequent segfaults at the same offset (XrdSecProtocolgsi.cc#L1558). They downgraded back to 4.6.1 and the service runs normally.

**Comment by simonmichal** [comment] 2017-10-06 14:46
OK, thanks :-)
Just for the record I was able to reproduce it.

**Comment by simonmichal** [comment] 2017-10-06 15:58
I think that this part of code from 4.6.1:
https://github.com/xrootd/xrootd/blob/a9430a260d6e11435ea117918e539525f9700f8d/src/XrdSecgsi/XrdSecProtocolgsi.cc#L1907-L1913
corresponds to this one from 4.7.0:
https://github.com/xrootd/xrootd/blob/master/src/XrdSecgsi/XrdSecProtocolgsi.cc#L1865-L1870

In 4.7.0 the lines that remove the entry after deletion from cache disappeared (also the new XrdSutCache doesn't have the Remove method ;-).

**Comment by gganis** [comment] 2017-10-10 09:49
Hi,
I have just submitted a pull request addressing this issue.
@jthiltges would it be possible to test it?

**Comment by simonmichal** [comment] 2017-10-10 10:17
The PR fixes the problem in my test-bed.

**Comment by simonmichal** [comment] 2017-10-11 15:04
@jthiltges : any news?

**Comment by jthiltges** [comment] 2017-10-11 20:23
Marian is working toward an OSG build of xrootd that can hopefully be tested at Florida. Thank you both.

**Comment by zvada** [comment] 2017-10-17 20:41
I'd like to engage Florida to test this where we originally discovered the issue. While RC1 should cover fix for this particular issue I'd prefer to move on to OSG build from RC2 coming this week (?) which should include even more (interesting) patches. That way I save one iteration asking Florida update to RC1 and right after that to RC2. Is that acceptable we wait for RC2 or are you insisting on the testing of RC1? By the time we know results of RC1 testing there will be RC2 out of the door I believe.

**Comment by simonmichal** [comment] 2017-10-18 07:49
If it's a hassle for you then don't bother with RC1, as I tested it in my test-bed I have a high degree of confidence in this patch ;-) I can wait few more days for confirmation :-)

**Comment by simonmichal** [comment] 2017-10-27 14:15
Any news? (preferably good news ;-)

**Comment by simonmichal** [comment] 2017-10-30 12:47
As far as I understood the conversation in #606, we can close this one.

**Closed by simonmichal** 2017-10-30 12:47 UTC
