### ISSUE TITLE
XrdClXRootDTransport: client cleans up authentication data even if authentication was successful (REVIEW)

### ISSUE THREAD

**Issue by simonmichal** [xrootd/xrootd#278] opened 2015-08-17 09:01 UTC
Review if the the following behaviour is correct:
the client cleans up the authentication protocol even in the case of a successful authentication (line 1563 in XrdClXRootDTransport.cc)

**Comment by esindril** [comment] 2015-09-28 13:55
@ljanyst, any reason why this is done here? https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClXRootDTransport.cc#L1563
Shouldn't we keep the credentials around in case we need to re-authenticate? The lifetime of this information should be tied to the lifetime of the physical connection, right?

**Comment by ljanyst** [comment] 2015-09-28 14:23
AFAIR, these objects keep the state of the authentication framework for the given interaction and are not re-usable. This is fine because the parallel data streams are not authenticated but rather bound to the existing session (established by the main stream) using a different mechanism and on the re-establishment of the main stream the authentication procedure needs to be re-done from scratch anyways.

**Comment by ljanyst** [comment] 2015-09-28 14:32
Ie. they depend on the authentication preference settings returned by `kXR_login`:

https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClXRootDTransport.cc#L1500
https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClXRootDTransport.cc#L1658

**Comment by esindril** [comment] 2015-09-28 17:32
Thanks for the explanation, @ljanyst. I am trying to understand this as CMS had some problems related to authentication with the following signature:

```bash
First successfull attempt is at 21:13, then 21:39

150529 21:39:09 23053 secgsi_getCredentials: certificate chain verification failed: EEC or sub-CA: signature verification failed CF: 0x2b3827f4cdd0
150529 21:39:09 23053 secgsi_ErrF: Secgsi: ErrParseBuffer: certificate chain verification failed: EEC or sub-CA: signature verification failed: kXGS_cert
```

Then @gganis had a look and proposed to increase the TTL which apparently proved to be a satisfying temporary solution for the CMS people. But we are still trying to get to the bottom of it ...

**Comment by ljanyst** [comment] 2015-09-28 18:35
Good luck! If I was to bet blind, I would say it's a CRL issue.

**Comment by bbockelm** [comment] 2015-09-28 18:44
I took point from the CMS side in debugging this issue - indeed, it seems that when re-connecting to servers after the idle connection timeout is up, the GSI authentication fails.

We did verify it's not a CRL issue on the worker node filesystem - it's possible some problem in the in-memory representation of the CRLs, I suppose.

Brian

**Comment by ljanyst** [comment] 2015-09-28 22:38
This is just an educated guess. In any case, quite a bit of crypto and security stuff was refactored when we changed how the plug-ins are handled, so this would be the first place I would look at. We have TTLs since some time and, to my knowledge, this issue has never surfaced.

**Comment by esindril** [comment] 2016-05-17 07:02
The authentication information related to the connection can be safely deleted once the authentication is done. In case of  any subsequent reconnect, all the initial steps are done - including the loading of the krb5 info or gsi certificate. Therefore, clearing the auth info even in successful situation is not an issue.

I tried to reproduce this, but without luck. Unless this is still happening and there is a way to reproduce it, I will close it. Feel free to reopen if this is still an issue.

**Closed by esindril** 2016-05-17 07:02 UTC
Labels: question
