### ISSUE TITLE
Eventstream notifications are space-separated and may contain spaces

### ISSUE THREAD

**Issue by olifre** [xrootd/xrootd#1200] opened 2020-05-20 01:08 UTC
I just encountered in real life that the event stream default "notifymsg" for `chmod`:
https://github.com/xrootd/xrootd/blob/cfdc6aca0bde74f7b65000987f846512c42a87ab/src/XrdOfs/XrdOfsEvs.cc#L139-L141
produces something not cleanly parseable, The reason is that the {{TID}} may contain spaces, such as {{Robot: ATLAS Data Management}} does, and worst case this might also happen with the path. 

Since I'm only interested in the {{LFN}} anyways, I'm now just looking at the last column in my script (hoping the path does not contain spaces), but I wonder if the format should be changed in general (enquoting the separate tokens? escaping spaces? Using {{\t}} or {{\0}} to separate the tokens?).

**Comment by abh3** [comment] 2020-05-20 01:52
Huh? That this is certianly not one that xroot would ever conjure up. If 
this is being generated by EOS then it's an EOS problem and this should be 
refered to them. In native xroot land, the tid *never* has spaces exactly 
for this reason.

**Comment by olifre** [comment] 2020-05-20 02:02
I'm using pure XRootD here. Will add some log lines tomorrow, I actually only found that the Eventstream-script was given some TID with spaces, but did not correlate that to what XRootD itself has logged yet.

**Comment by abh3** [comment] 2020-05-20 02:30
Please do as I don't see how that string would ever get there. That is not 
a valid trace identifier for native xrootd. Do you have a log I can look 
at as the trace identifier would be sprinkled throughout.

**Comment by olifre** [comment] 2020-05-20 09:32
Here you go:
```
200520 01:45:40 3230225 XrootdBridge: /DC=ch/D.4917:33@atlas-rucio-int-01-someHash-node-3.cern.ch login as /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management
200520 01:45:40 3230225 acc_Audit: http grant  /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management@[::ffff:THIS.IS.THE.IP] stat /cephfs/grid/atlas/atlaslocalgroupdisk/rucio/tests/9e/f2/file41_31068ef9-33c3-4d88-8688-bf127939adb6
200520 01:45:40 3230225 ofs_stat: /DC=ch/D.4917:33@atlas-rucio-int-01-someHash-node-3.cern.ch Unable to locate /cephfs/grid/atlas/atlaslocalgroupdisk/rucio/tests/9e/f2/file41_31068ef9-33c3-4d88-8688-bf127939adb6; no such file or directory
200520 01:45:40 3230225 XrootdXeq: /DC=ch/D.4917:33@atlas-rucio-int-01-someHash-node-3.cern.ch disc 0:00:00 (send failure)
```
In parallel to such messages, I find in `journalctl -u xrootd@grid`:
```
Mai 20 01:54:17 osd001.example.com xrootd[2841977]: chmod: cannot access ‘Data Management create 644 /cephfs/grid/atlas/atlaslocalgroupdisk/rucio/tests/70/98/file40_e992aeb9-35d9-4470-9e5e-5aa279842d96’: No such file or directory
```
I'm using:
```
ofs.notify mkdir create |/usr/local/bin/xrootd-eventstream-permission-fix
```
with the following script content:
```
#!/bin/bash

while read TID OP MODE LFN; do
        chmod go+rX "${LFN}"
done < /dev/stdi
```

Maybe this is an http-only issue?

**Comment by abh3** [comment] 2020-06-25 05:19
Actually, if the message format is bothersome, you can define your own. See
https://xrootd.slac.stanford.edu/doc/dev50/ofs_config.htm#_Toc43842829

Will that solve the problem here?

**Comment by olifre** [comment] 2020-06-27 18:21
Hi Andy,
actually, I'm now using this`to explicitly get the last component of the output, which also seems to work well:
```
while read -r -a line; do
        # Default format is: "TID OP MODE LFN", note TID may contain spaces.
        # Just take last column!
        num_cols=${#line[@]}
        LFN=${line[$((num_cols - 1))]}
        chmod go+rX "${LFN}"
done < /dev/stdin
```
So this fixed my issue, and redefining the format would likely fix it, too (i.e. this is now "WORKSFORME"). I still wonder if the TID containing spaces is a wanted behaviour, though. If that's acceptable, we can close the issue, but if the TID should never contain spaces, we should probably keep it open to fix that.

**Comment by abh3** [comment] 2020-06-28 05:13
Hi Oliver,

No the TID should not have spaces not any other character that is invalid
for a Unix ID. So, I am wondering where that is being injected into the 
system as the TID is normally "cleaned".

Andy

**Comment by olifre** [comment] 2020-06-28 12:25
Hi Andy,

the example log you see above shows the TID with spaces, it seems that TID might be created by `XrdHttpVOMS`:
```
200520 01:45:40 3230225 acc_Audit: http grant  /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management@[::ffff:THIS.IS.THE.IP] stat /cephfs/grid/atlas/atlaslocalgroupdisk/rucio/tests/9e/f2/file41_31068ef9-33c3-4d88-8688-bf127939adb6
```

Cheers,
Oliver

**Comment by abh3** [comment] 2020-06-30 06:01
This has now been fixed in R5 so I am closing it. Generally, there should be no spaces in items placed in the event stream. This particular bug was caused by not screening http stuff injected into the stream.

**Closed by abh3** 2020-06-30 06:01 UTC

**Comment by olifre** [comment] 2020-06-30 12:53
@abh3 Thanks! :-)
For future reference, in case somebody stumbles upon this, the commit which should fix this is:
https://github.com/xrootd/xrootd/commit/7de9a03f7a8fecd9a5b8ea7e0414e766d9fe09c5

**Comment by simonmichal** [comment] 2020-06-30 14:26
@olifre : it is already ported to `stable-4.12.x` ;-)

**Comment by olifre** [comment] 2020-06-30 17:21
@simonmichal Thanks! 
While we will likely be fast to upgrade to R5, I'll of course give that a go in the upcoming 4.12.4 :-).
